// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package postgres

import (
	"errors"
	"time"
)

// providerSecretAADPrefix is the AAD scheme+version tag for provider-config
// secrets, matching the epic #4962 shared crypto contract exactly:
// "eshu:provider-secret:v1|<provider_config_id>|<revision_id>". AAD is never
// stored; every Seal/Open call reconstructs it from the row being sealed or
// opened, which is what makes a ciphertext copied into a different revision
// row fail to decrypt (a cut-and-paste / confused-deputy defense).
const providerSecretAADPrefix = "eshu:provider-secret:v1"

// ErrProviderSecretKeyringUnavailable is returned by any provider-config write
// that carries a plaintext secret when no DEK is configured
// (SetProviderSecretKeyring was never called, or ESHU_AUTH_SECRET_ENC_KEY(_FILE)
// is unset). Provider-config writes fail closed rather than silently
// persisting an unsealed secret or dropping it.
var ErrProviderSecretKeyringUnavailable = errors.New("identity subject store: provider secret keyring is not configured")

// ErrProviderConfigNotFound is returned by an update, revert, enable, or
// disable call that targets a provider_config_id absent (or tombstoned) in
// the caller's tenant.
var ErrProviderConfigNotFound = errors.New("identity subject store: provider config not found")

// ErrProviderConfigDuplicateKey is returned by CreateProviderConfig when the
// tenant already has a live (non-tombstoned) provider of the same kind and
// key hash — the identity_provider_configs_tenant_kind_key_idx unique index.
var ErrProviderConfigDuplicateKey = errors.New("identity subject store: provider config already exists for this tenant/kind/key")

// ErrProviderConfigRevisionNotFound is returned by RevertProviderConfig when
// the target revision does not belong to the provider config.
var ErrProviderConfigRevisionNotFound = errors.New("identity subject store: provider config revision not found")

// ProviderConfigCreate is the input to CreateProviderConfig. ProviderConfigID
// and RevisionID are generated by the caller (query layer) before the call so
// the AAD can be constructed deterministically; the store never invents an
// id. PlaintextSecret is the caller-assembled secret JSON blob (e.g.
// `{"client_secret":"..."}` for OIDC, `{"sp_private_key":"...","sp_certificate":"..."}`
// for SAML) and is sealed by this call — it is never persisted or logged in
// plaintext, and this store never returns it. Configuration is the
// caller-assembled non-secret settings JSON (issuer, client_id, scopes,
// group_claim for OIDC; metadata_url, metadata_xml, entity_id,
// group_attribute for SAML). The *_hash fields are the dedup/correlation
// hashes for the provider's identity key; they are set once at creation and
// are immutable afterward — see identity_provider_config_writes.go's package
// doc comment for why editing the identity key is out of scope for Update.
type ProviderConfigCreate struct {
	ProviderConfigID  string
	TenantID          string
	ProviderKind      string // "external_oidc" | "external_saml"
	ProviderKeyHash   string
	IssuerHash        string
	ClientIDHash      string
	MetadataURLHash   string
	EntityIDHash      string
	RevisionID        string
	Configuration     string
	ConfigurationHash string
	MetadataHash      string
	PlaintextSecret   string
	Now               time.Time
}

// ProviderConfigUpdate is the input to UpdateProviderConfig: it always
// creates a new active revision (superseding the current one) and always
// requires the full plaintext secret to be resupplied — see
// identity_provider_config_writes.go's package doc comment for why partial
// (secret-omitted) edits are not supported.
type ProviderConfigUpdate struct {
	ProviderConfigID  string
	TenantID          string
	RevisionID        string
	Configuration     string
	ConfigurationHash string
	MetadataHash      string
	PlaintextSecret   string
	Now               time.Time
}

// ProviderConfigRevert activates a prior revision, restoring its sealed
// secret automatically (the target revision's sealed_secret was already
// correctly sealed under its own (provider_config_id, revision_id) AAD when
// it was created — reactivating it requires no Seal/Open call at all).
type ProviderConfigRevert struct {
	ProviderConfigID string
	TenantID         string
	TargetRevisionID string
	Now              time.Time
}

// ProviderConfigEnable transitions a provider config from draft to active.
// The caller (query-layer handler) is responsible for confirming a passing
// test-connection result before calling this — this store does not run or
// know about connection tests.
type ProviderConfigEnable struct {
	ProviderConfigID string
	TenantID         string
	Now              time.Time
}

// ProviderConfigDisable transitions a provider config from active back to
// draft. Idempotent: disabling an already-draft config is a no-op.
type ProviderConfigDisable struct {
	ProviderConfigID string
	TenantID         string
	Now              time.Time
}

// ProviderConfigWriteResult is returned by every provider-config write.
type ProviderConfigWriteResult struct {
	ProviderConfigID string
	RevisionID       string
	Status           string
	Found            bool // false only for Update/Revert/Enable/Disable against a missing config
	Changed          bool // false for a true no-op (e.g. revert to the already-active revision, disable of an already-draft config)
}

// ProviderConfigDetail is the metadata-only admin view of one provider config
// and its active revision. It never carries sealed_secret; HasSecret,
// SecretFingerprint, and SecretKeyID are derived from the envelope's
// structure and a hash of its ciphertext, never from opening it — this type
// is populated without ever calling (*secretcrypto.Keyring).Open.
type ProviderConfigDetail struct {
	ProviderConfigID  string
	TenantID          string
	ProviderKind      string
	Status            string
	ActiveRevisionID  string
	Configuration     string
	HasSecret         bool
	SecretFingerprint string
	SecretKeyID       string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

// ProviderConfigRevisionItem is one row of a provider config's revision
// history. It never carries sealed_secret.
type ProviderConfigRevisionItem struct {
	RevisionID   string
	Status       string
	HasSecret    bool
	CreatedAt    time.Time
	ActivatedAt  time.Time
	SupersededAt time.Time
}

// ProviderConfigConnectionTestMaterial is the ciphertext-plus-configuration
// bundle handed to the test-connection orchestration path (cmd/api), which
// passes it to a login/authn package (oidclogin, samlauth) to Open
// transiently and validate. This method exists ONLY for that orchestration
// path; its result — sealed ciphertext, not plaintext — must never be
// serialized into any API response, audit event, log line, or metric label.
// This store itself never calls Open.
type ProviderConfigConnectionTestMaterial struct {
	ProviderConfigID string
	RevisionID       string
	ProviderKind     string
	SealedSecret     string
	Configuration    string
}
