// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package postgres

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"sort"
	"testing"
)

// TestIncidentRoutingSQLProjectedFieldsAreSchemaDeclared closes the payload-usage
// manifest gate's blind spot for the incident family (Contract System v1 Wave 4a,
// coordinator handoff §1). The #4573 payload-usage manifest gate is generated by
// scanning the reducer's factschema Decode* call sites, so it can only see fields
// a reducer decodes through the typed seam. The two incident raw-SQL-JSONB
// loaders below read source-fact payload fields with `fact.payload->>'field'`
// straight in the query text — invisible to that gate. If a future contracts
// change drops one of those fields from the incident schemas, the manifest gate
// would stay green while the SQL silently read a missing column.
//
// This test is the compile-adjacent lockstep that prevents it: every incident
// source-fact payload field these two SQL constants read MUST appear as a declared
// property in one of the generated incident/v1 JSON Schemas. It excludes the
// reducer-OWNED correlation fact kinds (reducer_service_catalog_correlation,
// reducer_incident_repository_correlation) — those are reducer output, not
// collector-emitted incident source facts, and are not part of the incident
// contract. It follows the compile-time-lockstep precedent in
// incident_repository_correlation_loader.go's trailing `var _ =
// facts.IncidentRoutingAppliedPagerDutyResourceFactKind` reference.
func TestIncidentRoutingSQLProjectedFieldsAreSchemaDeclared(t *testing.T) {
	t.Parallel()

	declared := incidentSchemaDeclaredProperties(t)

	// Fields these SQL constants read from incident SOURCE fact kinds. Fields read
	// from the reducer-owned correlation kinds (provider_service_id,
	// repository_id, provenance_only, outcome) are intentionally excluded: they
	// are reducer output, not a typed incident source payload. Keep this set in
	// lockstep with the incident-source `payload->>'...'` reads in the two SQL
	// constants; a drift here is the signal to update the schema or the reads.
	sourceFields := []string{
		// incident_repository_correlation_loader.go — applied_pagerduty_resource.
		"backend_kind",
		"locator_hash",
		"name_fingerprint",
		"provider_object_id",
		"resource_class",
		// service_incident_evidence_loader.go — incident.record and routing kinds.
		"provider",
		"provider_incident_id",
		"service_id",
		// service is the nested object serviceIncidentEvidenceQuery reads via
		// `payload->'service'->>'id'` (COALESCE-falling back to service_id) to
		// resolve an incident.record's PagerDuty service reference (#4683).
		"service",
		"declared_match_state",
		"redaction_state",
	}

	// Prove the field literals we assert are actually present in the SQL text, so
	// this test cannot pass by asserting a stale field the query no longer reads.
	sqlText := listAppliedPagerDutyServiceRoutingQuery + serviceIncidentEvidenceQuery
	fieldRef := regexp.MustCompile(`payload->>?'([a-z_]+)'`)
	referenced := map[string]bool{}
	for _, m := range fieldRef.FindAllStringSubmatch(sqlText, -1) {
		referenced[m[1]] = true
	}

	for _, field := range sourceFields {
		if !referenced[field] {
			t.Errorf("field %q is asserted here but no longer read by the incident SQL constants; update this test", field)
			continue
		}
		if !declared[field] {
			t.Errorf("incident SQL reads payload field %q but no incident/v1 schema declares it as a property; a dropped/renamed field would silently break the SQL read", field)
		}
	}
}

// incidentSchemaDeclaredProperties reads every generated incident/v1 JSON Schema
// and returns the union of their declared property names, so the lockstep test
// can assert a SQL-read field is declared by at least one incident schema.
func incidentSchemaDeclaredProperties(t *testing.T) map[string]bool {
	t.Helper()

	schemaDir := incidentSchemaDir(t)
	entries, err := os.ReadDir(schemaDir)
	if err != nil {
		t.Fatalf("read incident schema dir %q: %v", schemaDir, err)
	}

	declared := map[string]bool{}
	found := 0
	for _, entry := range entries {
		name := entry.Name()
		if !isIncidentSchemaFile(name) {
			continue
		}
		found++
		raw, err := os.ReadFile(filepath.Join(schemaDir, name))
		if err != nil {
			t.Fatalf("read schema %q: %v", name, err)
		}
		var doc struct {
			Properties map[string]json.RawMessage `json:"properties"`
		}
		if err := json.Unmarshal(raw, &doc); err != nil {
			t.Fatalf("unmarshal schema %q: %v", name, err)
		}
		for prop := range doc.Properties {
			declared[prop] = true
		}
	}
	if found == 0 {
		t.Fatalf("no incident schema files found under %q", schemaDir)
	}
	return declared
}

// incidentSchemaDir resolves the checked-in incident schema directory relative to
// this test file, walking up to the repo root so the test does not depend on the
// working directory.
func incidentSchemaDir(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	// go/internal/storage/postgres/<file> -> repo root is four levels up.
	repoRoot := filepath.Join(filepath.Dir(thisFile), "..", "..", "..", "..")
	return filepath.Join(repoRoot, "sdk", "go", "factschema", "schema")
}

// isIncidentSchemaFile reports whether a schema file belongs to the incident
// family (its dotted kind starts with an incident namespace).
func isIncidentSchemaFile(name string) bool {
	for _, prefix := range incidentSchemaPrefixes {
		if len(name) >= len(prefix) && name[:len(prefix)] == prefix {
			return true
		}
	}
	return false
}

// incidentSchemaPrefixes are the incident-family schema filename prefixes.
var incidentSchemaPrefixes = func() []string {
	prefixes := []string{"incident.", "change.record", "incident_routing."}
	sort.Strings(prefixes)
	return prefixes
}()
