// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package postgres

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"testing"
)

// TestPackageRegistrySQLProjectedFieldsAreSchemaDeclared closes the
// payload-usage manifest gate's blind spot for the package_registry family
// (Contract System v1 Wave 4c). The #4573 payload-usage manifest gate is
// generated by scanning the reducer's and projector's factschema Decode*
// call sites, so it can only see fields a decode seam actually decodes. Two
// raw-SQL-JSONB queries read package_registry source-fact payload fields with
// `fact.payload->>'field'` straight in the query text — invisible to that
// gate:
//
//   - listActiveSupplyChainImpactFactsQuery
//     (facts_active_supply_chain_impact.go) reads package_id (among other
//     kinds' fields) against package_registry.vulnerability_hint, a
//     typed-but-not-yet-consumed kind (packageregistry/v1/doc.go).
//   - registryMetadataTargetStatusQuery (status_registry.go) reads ecosystem
//     and warning_code against package_registry.warning, also
//     typed-but-not-yet-consumed.
//
// If a future contracts change dropped one of those fields from the
// package_registry schemas, the manifest gate would stay green (neither field
// is read through a decode seam) while the SQL silently read a missing
// column. This test is the compile-adjacent lockstep that prevents it: every
// package_registry payload field these two SQL constants read MUST appear as
// a declared property in one of the generated packageregistry/v1 JSON
// Schemas. It follows the incident family's precedent
// (TestIncidentRoutingSQLProjectedFieldsAreSchemaDeclared,
// incident_routing_sql_schema_lockstep_test.go).
func TestPackageRegistrySQLProjectedFieldsAreSchemaDeclared(t *testing.T) {
	t.Parallel()

	declared := packageRegistrySchemaDeclaredProperties(t)

	// Fields these SQL constants read from package_registry SOURCE fact kinds.
	// Keep this set in lockstep with the package_registry `payload->>'...'`
	// reads in the two SQL constants; a drift here is the signal to update the
	// schema or the reads.
	sourceFields := []string{
		// facts_active_supply_chain_impact.go — package_registry.vulnerability_hint.
		"package_id",
		// status_registry.go — package_registry.warning.
		"ecosystem",
		"warning_code",
	}

	// Prove the field literals we assert are actually present in the SQL text,
	// so this test cannot pass by asserting a stale field the query no longer
	// reads.
	sqlText := listActiveSupplyChainImpactFactsQuery + registryMetadataTargetStatusQuery
	fieldRef := regexp.MustCompile(`payload->>?'([a-z_]+)'`)
	referenced := map[string]bool{}
	for _, m := range fieldRef.FindAllStringSubmatch(sqlText, -1) {
		referenced[m[1]] = true
	}

	for _, field := range sourceFields {
		if !referenced[field] {
			t.Errorf("field %q is asserted here but no longer read by the package_registry SQL constants; update this test", field)
			continue
		}
		if !declared[field] {
			t.Errorf("package_registry SQL reads payload field %q but no packageregistry/v1 schema declares it as a property; a dropped/renamed field would silently break the SQL read", field)
		}
	}
}

// packageRegistrySchemaDeclaredProperties reads every generated
// package_registry.* JSON Schema and returns the union of their declared
// property names, so the lockstep test can assert a SQL-read field is
// declared by at least one package_registry schema.
func packageRegistrySchemaDeclaredProperties(t *testing.T) map[string]bool {
	t.Helper()

	schemaDir := packageRegistrySchemaDir(t)
	entries, err := os.ReadDir(schemaDir)
	if err != nil {
		t.Fatalf("read package_registry schema dir %q: %v", schemaDir, err)
	}

	declared := map[string]bool{}
	found := 0
	for _, entry := range entries {
		name := entry.Name()
		if !isPackageRegistrySchemaFile(name) {
			continue
		}
		found++
		raw, err := os.ReadFile(filepath.Join(schemaDir, name))
		if err != nil {
			t.Fatalf("read schema %q: %v", name, err)
		}
		var doc struct {
			Properties map[string]json.RawMessage `json:"properties"`
		}
		if err := json.Unmarshal(raw, &doc); err != nil {
			t.Fatalf("unmarshal schema %q: %v", name, err)
		}
		for prop := range doc.Properties {
			declared[prop] = true
		}
	}
	if found == 0 {
		t.Fatalf("no package_registry schema files found under %q", schemaDir)
	}
	return declared
}

// packageRegistrySchemaDir resolves the checked-in factschema schema
// directory relative to this test file, walking up to the repo root so the
// test does not depend on the working directory.
func packageRegistrySchemaDir(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	// go/internal/storage/postgres/<file> -> repo root is four levels up.
	repoRoot := filepath.Join(filepath.Dir(thisFile), "..", "..", "..", "..")
	return filepath.Join(repoRoot, "sdk", "go", "factschema", "schema")
}

// isPackageRegistrySchemaFile reports whether a schema file belongs to the
// package_registry family (its dotted kind starts with the package_registry.
// namespace).
func isPackageRegistrySchemaFile(name string) bool {
	const prefix = "package_registry."
	return len(name) >= len(prefix) && name[:len(prefix)] == prefix
}
