// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package postgres

var orderedBootstrapDefinitionNames = []string{
	"ingestion_scopes",
	"scope_generations",
	"fact_records",
	"service_catalog_fact_record_indexes",
	"fact_record_sbom_attestation_indexes",
	"eshu_search_index",
	"eshu_search_vector_metadata",
	"eshu_search_vector_values",
	"content_store",
	"fact_work_items",
	"fact_work_item_audit",
	"semantic_extraction_jobs",
	"collector_generation_dead_letters",
	"governance_audit_events",
	"tenant_workspace_grants",
	"generation_retention_events",
	"scoped_api_tokens",
	"identity_subjects",
	"browser_sessions",
	"identity_oidc_login",
	"projection_decisions",
	"admission_decisions",
	"shared_projection_intents",
	"runtime_ingester_control",
	"relationship_tables",
	"shared_projection_acceptance",
	"graph_projection_phase_state",
	"graph_projection_phase_repair_queue",
	"workflow_control_plane",
	"workflow_coordinator_state",
	"deferred_maintenance_barriers",
	"iac_reachability",
	"webhook_refresh_triggers",
	"aws_pagination_checkpoints",
	"aws_scan_status",
	"aws_freshness_triggers",
	"graph_schema_applications",
	"vulnerability_source_states",
	"incident_freshness_triggers",
	"graph_endpoint_presence",
	"service_materialization_generations",
	"service_evidence_snapshots",
	"code_reachability",
	"function_summaries",
	"function_sources",
	"function_graph_ids",
	"admin_replay_requests",
	"value_flow_fixpoint_components",
	"supply_chain_impact_canonical_winners",
	"supply_chain_impact_winners_materialization",
	"content_entities_repo_entity_idx",
	"collector_evidence_summary",
	"eshu_search_index_terms_doc_idx",
	"drop_eshu_search_index_terms_lookup_idx",
	"drop_eshu_search_index_terms_doc_idx",
	"gcp_freshness_triggers",
	"search_vector_build_materialization",
	"aws_gcp_freshness_claim_lease",
	"deferred_backfill_partition_memo",
	"dead_letter_poison_idx",
	"code_interproc_projected_edge",
}
