package query

func deadCodeGraphPolicyPredicate() string {
	return `
		AND NOT (toLower(f.relative_path) CONTAINS '/test/'
			OR toLower(f.relative_path) CONTAINS '/tests/'
			OR toLower(f.relative_path) CONTAINS '/__tests__/'
			OR toLower(f.relative_path) CONTAINS '/cypress/'
			OR toLower(f.relative_path) STARTS WITH 'test/'
			OR toLower(f.relative_path) STARTS WITH 'tests/'
			OR toLower(f.relative_path) STARTS WITH '__tests__/'
			OR toLower(f.relative_path) STARTS WITH 'cypress/'
			OR toLower(f.relative_path) ENDS WITH '_test.go'
			OR toLower(f.relative_path) ENDS WITH '_test.py'
			OR toLower(f.relative_path) ENDS WITH '.lab.js'
			OR toLower(f.relative_path) ENDS WITH '.lab.jsx'
			OR toLower(f.relative_path) ENDS WITH '.lab.ts'
			OR toLower(f.relative_path) ENDS WITH '.lab.tsx'
			OR toLower(f.relative_path) ENDS WITH '.test.js'
			OR toLower(f.relative_path) ENDS WITH '.test.jsx'
			OR toLower(f.relative_path) ENDS WITH '.test.ts'
			OR toLower(f.relative_path) ENDS WITH '.test.tsx'
			OR toLower(f.relative_path) ENDS WITH '.spec.js'
			OR toLower(f.relative_path) ENDS WITH '.spec.jsx'
			OR toLower(f.relative_path) ENDS WITH '.spec.ts'
			OR toLower(f.relative_path) ENDS WITH '.spec.tsx'
			OR toLower(f.relative_path) ENDS WITH '.cy.js'
			OR toLower(f.relative_path) ENDS WITH '.cy.jsx'
			OR toLower(f.relative_path) ENDS WITH '.cy.ts'
			OR toLower(f.relative_path) ENDS WITH '.cy.tsx'
			OR toLower(f.relative_path) ENDS WITH 'cypress.config.js'
			OR toLower(f.relative_path) ENDS WITH 'cypress.config.jsx'
			OR toLower(f.relative_path) ENDS WITH 'cypress.config.ts'
			OR toLower(f.relative_path) ENDS WITH 'cypress.config.tsx'
			OR toLower(f.relative_path) ENDS WITH '.config.js'
			OR toLower(f.relative_path) ENDS WITH '.config.jsx'
			OR toLower(f.relative_path) ENDS WITH '.config.ts'
			OR toLower(f.relative_path) ENDS WITH '.config.tsx'
			OR toLower(f.relative_path) ENDS WITH '.config.mjs'
			OR toLower(f.relative_path) ENDS WITH '.config.cjs'
			OR toLower(f.relative_path) ENDS WITH '.config.mts'
			OR toLower(f.relative_path) ENDS WITH '.config.cts')
		AND NOT (toLower(f.relative_path) CONTAINS '/gen/'
			OR toLower(f.relative_path) CONTAINS '/generated/'
			OR toLower(f.relative_path) CONTAINS '/.generated/'
			OR toLower(f.relative_path) ENDS WITH '.pb.go'
			OR toLower(f.relative_path) ENDS WITH '.gen.go'
			OR toLower(f.relative_path) ENDS WITH '_generated.go')
		AND coalesce(e.enclosing_function, '') = ''
`
}
