package query

import (
	"slices"
	"strings"
)

func buildDeadCodeAnalysis(results []map[string]any, excluded []string, stats deadCodePolicyStats) map[string]any {
	frameworks := make([]string, 0)
	seenFrameworks := make(map[string]struct{})
	for _, result := range results {
		metadata, _ := result["metadata"].(map[string]any)
		framework := strings.TrimSpace(StringVal(metadata, "framework"))
		if framework == "" {
			continue
		}
		if _, ok := seenFrameworks[framework]; ok {
			continue
		}
		seenFrameworks[framework] = struct{}{}
		frameworks = append(frameworks, framework)
	}
	slices.Sort(frameworks)

	return map[string]any{
		"root_categories_used": []string{
			"language_entrypoints",
			"generated_and_tool_owned",
			"library_public_api",
			"cli_command_roots",
			"http_and_rpc_roots",
			"framework_callback_roots",
		},
		"frameworks_recognized":                  frameworks,
		"reflection_modeled":                     true,
		"tests_excluded":                         true,
		"generated_code_excluded":                true,
		"framework_roots_from_parser_metadata":   stats.ParserMetadataFrameworkRoots,
		"framework_roots_from_source_fallback":   stats.SourceFallbackFrameworkRoots,
		"go_semantic_roots_from_parser_metadata": stats.GoSemanticRootsFromMetadata,
		"roots_skipped_missing_source":           stats.RootsSkippedMissingSource,
		"user_overrides_applied":                 len(excluded) > 0,
		"iac_reachability_mode":                  "not_modeled_by_code_dead_code",
		"iac_deadness_capability":                "iac_usage.reachability",
		"dead_code_language_maturity":            deadCodeLanguageMaturityReport(),
		"dead_code_language_exactness_blockers":  deadCodeLanguageExactnessBlockerReport(),
		"dead_code_observed_exactness_blockers":  deadCodeObservedExactnessBlockerReport(results),
		"modeled_entrypoints": []string{
			"go.main",
			"go.init",
			"python.__main__",
			"java.main_method",
			"c.main_function",
			"cpp.main_function",
		},
		"modeled_framework_roots": []string{
			"go.cobra_run_registration",
			"go.cobra_run_signature",
			"go.net_http_handler_registration",
			"go.net_http_handler_signature",
			"go.controller_runtime_reconcile_signature",
			"python.fastapi_route_decorator",
			"python.flask_route_decorator",
			"python.celery_task_decorator",
			"python.click_command_decorator",
			"python.typer_command_decorator",
			"python.typer_callback_decorator",
			"python.script_main_guard",
			"python.aws_lambda_handler",
			"python.dataclass_model",
			"python.dataclass_post_init",
			"python.property_decorator",
			"python.module_all_export",
			"python.package_init_export",
			"python.dunder_method",
			"python.public_api_member",
			"python.public_api_base",
			"c.main_function",
			"c.public_header_api",
			"c.signal_handler",
			"c.callback_argument_target",
			"c.function_pointer_target",
			"cpp.main_function",
			"cpp.public_header_api",
			"cpp.virtual_method",
			"cpp.override_method",
			"cpp.callback_argument_target",
			"cpp.function_pointer_target",
			"cpp.node_addon_entrypoint",
			"java.constructor",
			"java.override_method",
			"java.ant_task_setter",
			"java.gradle_plugin_apply",
			"java.gradle_task_action",
			"java.gradle_task_property",
			"java.gradle_task_setter",
			"java.gradle_task_interface_method",
			"java.gradle_dsl_public_method",
			"java.method_reference_target",
			"java.spring_component_class",
			"java.spring_configuration_properties_class",
			"java.spring_request_mapping_method",
			"java.spring_bean_method",
			"java.spring_event_listener_method",
			"java.spring_scheduled_method",
			"java.lifecycle_callback_method",
			"java.junit_test_method",
			"java.junit_lifecycle_method",
			"java.jenkins_extension_class",
			"java.jenkins_symbol_class",
			"java.jenkins_symbol_method",
			"java.jenkins_initializer_method",
			"java.jenkins_databound_setter_method",
			"java.stapler_web_method",
			"java.serialization_hook_method",
			"java.externalizable_hook_method",
			"java.reflection_class_reference",
			"java.reflection_method_reference",
			"java.service_loader_provider",
			"java.spring_autoconfiguration_class",
			"javascript.nextjs_route_export",
			"javascript.nextjs_app_export",
			"javascript.express_route_registration",
			"javascript.express_middleware_registration",
			"javascript.koa_middleware_registration",
			"javascript.koa_route_registration",
			"javascript.fastify_hook_registration",
			"javascript.fastify_route_registration",
			"javascript.fastify_plugin_registration",
			"javascript.nestjs_controller_method",
			"javascript.commonjs_default_export",
			"javascript.commonjs_mixin_export",
			"javascript.node_package_export",
			"javascript.node_seed_execute",
			"javascript.node_migration_export",
			"javascript.hapi_amqp_consumer",
			"javascript.hapi_handler_export",
			"javascript.hapi_plugin_register",
			"javascript.hapi_route_config_handler",
			"javascript.hapi_proxy_callback",
			"rust.main_function",
			"rust.test_function",
			"rust.tokio_main",
			"rust.tokio_test",
			"rust.public_api_item",
			"rust.trait_impl_method",
			"rust.benchmark_function",
			"typescript.interface_method_implementation",
			"typescript.module_contract_export",
			"typescript.static_registry_member",
		},
		"modeled_public_api": []string{
			"go.exported_non_internal_package_symbol",
			"python.module_all_export",
			"python.package_init_export",
			"python.public_api_member",
			"python.public_api_base",
			"c.public_header_api",
			"cpp.public_header_api",
			"rust.public_api_item",
			"typescript.public_api_export",
			"typescript.public_api_reexport",
			"typescript.public_api_type_reference",
		},
		"modeled_go_semantic_roots": []string{
			"go.dependency_injection_callback",
			"go.direct_method_call",
			"go.fmt_stringer_method",
			"go.function_literal_reachable_call",
			"go.function_value_reference",
			"go.generic_constraint_method",
			"go.imported_direct_method_call",
			"go.imported_fmt_stringer_method",
			"go.interface_implementation_type",
			"go.interface_method_implementation",
			"go.interface_type_reference",
			"go.method_value_reference",
			"go.type_reference",
		},
		"notes": []string{
			"dead-code remains derived until broader framework, public-API, and reflection root models land",
			"go CLI registrations/signatures, stdlib HTTP registrations/signatures, controller-runtime reconcile signatures, C c.main_function, c.public_header_api, c.signal_handler, c.callback_argument_target, and c.function_pointer_target roots, C++ cpp.main_function, cpp.public_header_api, cpp.virtual_method, cpp.override_method, cpp.callback_argument_target, cpp.function_pointer_target, and cpp.node_addon_entrypoint roots, Python FastAPI/Flask/Celery/Click/Typer decorator roots, Python AWS Lambda handler roots, Python dataclass/property roots, Java main/constructor/override/Ant task setter/Gradle plugin and DSL roots, and JavaScript/TypeScript Next.js, Express, Koa, Fastify, NestJS, Node, Hapi, migration, interface, module-contract, and static-registry roots are modeled as derived roots",
			"go same-package and imported-package direct method calls, fmt Stringer hooks, generic constraint methods, function-value references, function-literal reachable calls, dependency-injection callbacks, type references, interface type references, interface implementation types, interface method implementations, and method values are honored when parser or reducer metadata marks them explicitly",
			"analysis reports whether a modeled framework root came from parser metadata or the legacy source fallback path",
			"go framework-root signature checks require entity source; missing source leaves those roots unevaluated",
			"go exported symbols outside cmd/, internal/, and vendor/ are treated as public API roots by default; Python public API roots are bounded to __all__ and package __init__.py reexports",
			"IaC deadness is not inferred by the code dead-code analyzer; use the IaC usage/reachability capability once available",
		},
	}
}
