package query

import (
	"path/filepath"
	"slices"
	"strings"
)

func filterResultsByDecoratorExclusions(results []map[string]any, excluded []string) []map[string]any {
	if len(results) == 0 || len(excluded) == 0 {
		return results
	}

	normalizedExcluded := make([]string, 0, len(excluded))
	for _, decorator := range excluded {
		if normalized := normalizeDecoratorName(decorator); normalized != "" {
			normalizedExcluded = append(normalizedExcluded, normalized)
		}
	}
	if len(normalizedExcluded) == 0 {
		return results
	}

	filtered := make([]map[string]any, 0, len(results))
	for _, result := range results {
		metadata, ok := result["metadata"].(map[string]any)
		if !ok {
			filtered = append(filtered, result)
			continue
		}
		if !resultMatchesDecoratorExclusion(metadata, normalizedExcluded) {
			filtered = append(filtered, result)
		}
	}

	return filtered
}

func resultMatchesDecoratorExclusion(metadata map[string]any, excluded []string) bool {
	rawDecorators, ok := metadata["decorators"].([]any)
	if !ok {
		return false
	}

	for _, raw := range rawDecorators {
		decorator, ok := raw.(string)
		if !ok {
			continue
		}
		if slices.Contains(excluded, normalizeDecoratorName(decorator)) {
			return true
		}
	}

	return false
}

func normalizeDecoratorName(value string) string {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return ""
	}
	return strings.TrimPrefix(trimmed, "@")
}

func deadCodeIsTestFile(result map[string]any, entity *EntityContent) bool {
	path := strings.ToLower(deadCodeEntityPath(result, entity))
	base := filepath.Base(path)
	switch {
	case strings.HasSuffix(path, "_test.go"):
		return true
	case strings.Contains(path, "/__tests__/"),
		strings.Contains(path, "/cypress/"),
		strings.Contains(path, "/tests/"),
		strings.Contains(path, "/test/"),
		strings.HasPrefix(path, "__tests__/"),
		strings.HasPrefix(path, "cypress/"),
		strings.HasPrefix(path, "tests/"),
		strings.HasPrefix(path, "test/"):
		return true
	case deadCodeIsJavaTestSourceSetPath(path):
		return true
	case strings.HasPrefix(base, "test_"),
		strings.HasPrefix(base, "cypress.config."),
		deadCodeIsJavaScriptConfigFile(base),
		strings.HasSuffix(base, ".cy.js"),
		strings.HasSuffix(base, ".cy.jsx"),
		strings.HasSuffix(base, ".cy.ts"),
		strings.HasSuffix(base, ".cy.tsx"),
		strings.HasSuffix(base, ".lab.js"),
		strings.HasSuffix(base, ".lab.jsx"),
		strings.HasSuffix(base, ".lab.ts"),
		strings.HasSuffix(base, ".lab.tsx"),
		strings.HasSuffix(base, "_test.py"),
		strings.HasSuffix(base, ".test.js"),
		strings.HasSuffix(base, ".test.jsx"),
		strings.HasSuffix(base, ".test.ts"),
		strings.HasSuffix(base, ".test.tsx"),
		strings.HasSuffix(base, ".spec.js"),
		strings.HasSuffix(base, ".spec.jsx"),
		strings.HasSuffix(base, ".spec.ts"),
		strings.HasSuffix(base, ".spec.tsx"):
		return true
	default:
		return false
	}
}

func deadCodeIsJavaTestSourceSetPath(path string) bool {
	parts := strings.Split(path, "/")
	for i := 0; i+1 < len(parts); i++ {
		if parts[i] != "src" {
			continue
		}
		sourceSet := parts[i+1]
		if sourceSet == "testfixtures" || strings.HasSuffix(sourceSet, "test") {
			return true
		}
	}
	return false
}

func deadCodeIsJavaScriptConfigFile(base string) bool {
	for _, suffix := range []string{
		".config.js",
		".config.jsx",
		".config.ts",
		".config.tsx",
		".config.mjs",
		".config.cjs",
		".config.mts",
		".config.cts",
	} {
		if strings.HasSuffix(base, suffix) {
			return true
		}
	}
	return false
}

func deadCodeIsGeneratedCode(result map[string]any, entity *EntityContent) bool {
	path := strings.ToLower(deadCodeEntityPath(result, entity))
	base := filepath.Base(path)
	switch {
	case strings.Contains(path, "/gen/"),
		strings.Contains(path, "/generated/"),
		strings.Contains(path, "/.generated/"),
		strings.HasSuffix(base, ".pb.go"),
		strings.HasSuffix(base, ".gen.go"),
		strings.HasSuffix(base, "_generated.go"):
		return true
	}

	source := ""
	if entity != nil {
		source = strings.ToLower(entity.SourceCache)
	}
	return strings.Contains(source, "code generated by") ||
		strings.Contains(source, "do not edit") ||
		strings.Contains(source, "@generated")
}
