// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package query

import "github.com/eshu-hq/eshu/go/internal/query/querycontract"

// canonicalCapabilityOrder mirrors capability-matrix.v1.yaml followed by its
// fragments in filename order. The contract test locks this snapshot to the
// same loader used for matrix parity, and querycontract fails closed if this
// order is not an exact permutation of the live registry.
var canonicalCapabilityOrder = []string{
	"code_search.exact_symbol",
	"code_search.fuzzy_symbol",
	"code_search.symbol_lookup",
	"code_inventory.structural",
	"code_flow.taint_path",
	"code_flow.reaching_def",
	"code_flow.cfg_summary",
	"code_flow.pdg_summary",
	"code_search.variable_lookup",
	"code_search.content_search",
	"code_search.topic_investigation",
	"graph_query.read_only_cypher",
	"symbol_graph.decorators",
	"symbol_graph.argument_names",
	"symbol_graph.class_methods",
	"symbol_graph.imports",
	"symbol_graph.import_dependencies",
	"symbol_graph.inheritance",
	"code_quality.complexity",
	"code_quality.refactoring",
	"security.hardcoded_secrets",
	"call_graph.direct_callers",
	"call_graph.direct_callees",
	"call_graph.relationship_story",
	"call_graph.metrics",
	"call_graph.transitive_callers",
	"call_graph.transitive_callees",
	"call_graph.call_chain_path",
	"call_graph.route_to_caller",
	"code_to_cloud.trace_exposure_path",
	"code_quality.dead_code",
	"iac_quality.dead_iac",
	"iac_management.find_unmanaged_resources",
	"iac_management.get_status",
	"iac_management.explain_status",
	"iac_management.propose_terraform_import_plan",
	"aws_runtime_drift.findings.list",
	"terraform_config_state_drift.findings.list",
	"iac_inventory.resources.list",
	"platform_impact.deployment_chain",
	"platform_impact.deployment_config_influence",
	"platform_impact.context_overview",
	"platform_impact.graph_summary_packet",
	"platform_impact.relationships_catalog",
	"platform_impact.infra_resource_aggregate",
	"platform_impact.container_image_list",
	"platform_impact.cloud_resource_list",
	"platform_impact.catalog",
	"relationship_evidence.drilldown",
	"evidence_citation.packet",
	"documentation_findings.list",
	"documentation_findings.aggregate",
	"documentation_facts.list",
	"documentation_evidence_packet.read",
	"documentation_evidence_packet.freshness",
	"package_registry.packages.list",
	"package_registry.versions.list",
	"package_registry.dependencies.list",
	"package_registry.correlations.list",
	"package_registry.dependency_chains.list",
	"package_registry.packages.aggregate",
	"dependencies.list",
	"ci_cd.run_correlations.list",
	"ci_cd.run_correlations.aggregate",
	"service_catalog.correlations.list",
	"kubernetes.correlations.list",
	"observability.coverage.correlations.list",
	"secrets_iam.identity_trust_chains.list",
	"secrets_iam.privilege_posture_observations.list",
	"secrets_iam.secret_access_paths.list",
	"secrets_iam.posture_gaps.list",
	"secrets_iam.posture_summary.read",
	"supply_chain.sbom_attestation_attachments.list",
	"supply_chain.sbom_attestation_attachments.aggregate",
	"supply_chain.container_image_identities.list",
	"supply_chain.container_image_identities.aggregate",
	"supply_chain.advisory_evidence.list",
	"supply_chain.advisory_catalog.list",
	"supply_chain.vulnerability_scanner.contract.read",
	"supply_chain.impact_findings.list",
	"supply_chain.impact_findings.aggregate",
	"supply_chain.impact_explanation.read",
	"supply_chain.security_alert_reconciliations.list",
	"supply_chain.security_alert_reconciliations.aggregate",
	"platform_impact.resource_to_code",
	"platform_impact.resource_investigation",
	"platform_impact.dependency_path",
	"platform_impact.environment_compare",
	"platform_impact.change_surface",
	"platform_impact.pre_change",
	"platform_impact.developer_change_plan",
	"platform_impact.contract_impact",
	"platform_impact.entity_map",
	"platform_impact.blast_radius",
	"incident.context.read",
	"work_item.evidence.list",
	"operator.dead_letters.list",
	"operator.reducer_input_invalid_facts.list",
	"freshness.generation_lifecycle",
	"freshness.changed_since",
	"freshness.service_changed_since",
	"admission_decisions.list",
	"answer_narration.status",
	"ask.natural_language_answer",
	"cloud_inventory.readback.list",
	"cloud_runtime_drift.readback.list",
	"codeowners.ownership.list",
	"collector_extraction_readiness.list",
	"collector_extraction_readiness.family",
	"component_extensions.inventory",
	"component_extensions.diagnostics",
	"platform_impact.container_image_tag_history",
	"fact_schema_version.list",
	"fact_schema_version.detail",
	"hosted_governance.status",
	"query.investigation_workflows",
	"symbol_graph.language_entities",
	"operations.status",
	"surface_inventory.list",
	"capability_catalog.list",
	"platform_metrics.timeseries",
	"query.playbooks",
	"reachability.go.govulncheck",
	"reachability.python.value_flow",
	"reachability.typescript.value_flow",
	"reachability.javascript.value_flow",
	"reachability.java.value_flow",
	"reachability.csharp.value_flow",
	"reachability.jvm.bounded",
	"replatforming.ownership.candidates",
	"replatforming.rollups.readiness",
	"replatforming.selector_inventory",
	"replatforming.plan.readiness",
	"semantic_extraction.status",
	"semantic_evidence.documentation_observations.list",
	"semantic_evidence.code_hints.list",
	"semantic_search.curated_retrieval",
	"visualization.packet_derivation",
	"visualization.graph_query",
}

func init() {
	// Keep this final capability row in the lexically last matrix file so the
	// canonical order is installed only after every earlier matrix fragment has
	// registered its rows.
	capabilityMatrix["terraform_config_state_drift.findings.list"] = capabilitySupport{
		LocalLightweightMax:   nil,
		LocalAuthoritativeMax: &truthDerived,
		LocalFullStackMax:     &truthDerived,
		ProductionMax:         &truthDerived,
		RequiredProfile:       ProfileLocalAuthoritative,
	}
	querycontract.SetCapabilityOrder(canonicalCapabilityOrder)
}
