// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package query

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"testing"
)

// TestDocumentationFindingSQLProjectedFieldsAreSchemaDeclared closes the
// payload-usage manifest gate's blind spot for the documentation_finding and
// documentation_evidence_packet kinds (Contract System v1 Wave 4e), mirroring
// TestIncidentRoutingSQLProjectedFieldsAreSchemaDeclared
// (go/internal/storage/postgres). The #4573 payload-usage manifest gate is
// generated by scanning the reducer's factschema Decode* call sites, so it
// cannot see these two kinds at all: they have NO reducer decode site — only
// this package's raw `fact_records.payload->>'field'` SQL reads them
// (documentation_read_model.go, documentation_finding_aggregates.go,
// documentation_packet_read_model.go). If a future contracts change drops one
// of those fields from the documentation/v1 schemas, the manifest gate would
// stay green while this SQL silently read a missing column.
//
// This test is the compile-adjacent lockstep that prevents it: every
// documentation_finding/documentation_evidence_packet payload field these
// files read via a literal `payload->>'field'` (or
// `addPayloadFilter("field", ...)`), or a literal `payload["field"]`/
// `payload->'field'` map/JSONB read, MUST appear as a declared property in
// the generated documentation_finding.v1.schema.json or
// documentation_evidence_packet.v1.schema.json schema. It reads the raw .go
// source text (rather than a fixed string constant, since these SQL builders
// are parameterized functions, not incident's package-level const strings) so
// the field-literal assertions below cannot go stale without failing.
func TestDocumentationFindingSQLProjectedFieldsAreSchemaDeclared(t *testing.T) {
	t.Parallel()

	declared := documentationFindingPacketSchemaDeclaredProperties(t)

	// Fields these files read from documentation_finding /
	// documentation_evidence_packet source facts via a literal field name.
	// section_id/document_id/title/heading_text/content/target_uri/
	// display_name in documentation_read_model.go's documentationFacts path
	// belong to the OTHER (typed-but-deferred) documentation kinds
	// (documentation_document/section/link/source), not documentation_finding,
	// and are excluded here; they are still declared on their own structs.
	sourceFields := []string{
		// documentation_read_model.go — buildDocumentationFindingsSQL.
		"finding_type",
		"source_id",
		"document_id",
		"status",
		"truth_level",
		"freshness_state",
		// documentation_finding_aggregates.go — the same six fields, reused
		// for the aggregate filter and inventory group expressions.
		// documentation_packet_read_model.go — the packet lookup keys.
		"finding_id",
		"packet_id",
		// documentation_target_read_model.go's documentationPayloadMatchesTargetRef
		// reads linked_entities generically off any documentation payload map
		// for target matching; doctruth's evidencePacketPayload is the only
		// writer that sets this key (always documentation_evidence_packet).
		"linked_entities",
	}

	sqlText := readGoSourceText(t, "documentation_read_model.go") +
		readGoSourceText(t, "documentation_finding_aggregates.go") +
		readGoSourceText(t, "documentation_packet_read_model.go") +
		readGoSourceText(t, "documentation_target_read_model.go")
	referenced := documentationSQLReferencedFields(sqlText)

	for _, field := range sourceFields {
		if !referenced[field] {
			t.Errorf("field %q is asserted here but no longer read by the documentation_finding/documentation_evidence_packet SQL; update this test", field)
			continue
		}
		if !declared[field] {
			t.Errorf("documentation SQL reads payload field %q but neither documentation_finding.v1.schema.json nor documentation_evidence_packet.v1.schema.json declares it as a property; a dropped/renamed field would silently break the SQL read", field)
		}
	}
}

// documentationSQLReferencedFields extracts every JSONB payload field name the
// documentation query SQL reads. It catches all four read shapes:
//
//   - `payload->>'field'` and `payload->'field'` (top-level, single- or
//     double-arrow),
//   - `addPayloadFilter("field", ...)` (the parameterized builder that emits
//     `payload->>'field'`),
//   - `payload["field"]` (the Go-map read documentationPayloadMatchesTargetRef
//     uses),
//   - a nested chain leaf like `payload->'finding'->>'finding_id'`, whose
//     leaf `->>'finding_id'` is NOT directly prefixed by `payload`.
//
// The `->>?'([a-z_]+)'` pattern (with no required `payload` prefix) is the fix
// for PR #4738's Copilot false-green finding: the old regex anchored on
// `payload` and so missed both `payload->'field'` intermediate reads and the
// nested-chain leaves, meaning a dropped field read through a nested chain
// could pass the lockstep silently. Matching any `->'field'`/`->>'field'`
// token closes that gap. It over-captures the intermediate object keys
// (`permissions`, `states`, `finding`) and their leaves, which is harmless:
// this map is only the "is this field read by SQL" side of the check; the
// caller asserts the top-level sourceFields it cares about, and the nested
// sub-object keys are intentionally not in that list (Finding/EvidencePacket
// deliberately do not model doctruth's nested sub-objects — see their godoc).
func documentationSQLReferencedFields(sqlText string) map[string]bool {
	referenced := map[string]bool{}
	// Any single- or double-arrow JSONB accessor, regardless of what precedes
	// it, so a nested-chain leaf (payload->'finding'->>'finding_id') is caught
	// as well as a top-level payload->>'field'.
	arrowRef := regexp.MustCompile(`->>?'([a-z_]+)'`)
	for _, m := range arrowRef.FindAllStringSubmatch(sqlText, -1) {
		referenced[m[1]] = true
	}
	// The parameterized builder and the Go-map read do not use an arrow
	// accessor literal, so match them separately.
	otherRef := regexp.MustCompile(`addPayloadFilter\("([a-z_]+)"|payload\["([a-z_]+)"\]`)
	for _, m := range otherRef.FindAllStringSubmatch(sqlText, -1) {
		if m[1] != "" {
			referenced[m[1]] = true
		}
		if m[2] != "" {
			referenced[m[2]] = true
		}
	}
	return referenced
}

// TestDocumentationSQLReferencedFieldsCatchesNestedChain is the negative test
// Copilot asked for: it proves the broadened extractor catches a field read
// only through a nested JSONB chain (payload->'finding'->>'finding_id'), which
// the old `payload->>?'field'` regex missed. Without this, a lockstep field
// read exclusively through a nested chain could be dropped from the schema
// while the guardrail stayed green.
func TestDocumentationSQLReferencedFieldsCatchesNestedChain(t *testing.T) {
	t.Parallel()

	sql := `COALESCE(fact_records.payload->>'finding_id', fact_records.payload->'finding'->>'nested_only_field')`
	referenced := documentationSQLReferencedFields(sql)

	if !referenced["finding_id"] {
		t.Errorf("top-level payload->>'finding_id' not caught")
	}
	if !referenced["nested_only_field"] {
		t.Errorf("nested-chain leaf payload->'finding'->>'nested_only_field' not caught; the extractor must match arrow accessors that are not directly prefixed by `payload`")
	}
	if !referenced["finding"] {
		t.Errorf("intermediate object key payload->'finding' not caught")
	}

	// Prove the OLD (anchored) regex would have missed the nested leaf, so this
	// test is a real regression guard, not a tautology.
	oldRegex := regexp.MustCompile(`payload->>?'([a-z_]+)'`)
	oldReferenced := map[string]bool{}
	for _, m := range oldRegex.FindAllStringSubmatch(sql, -1) {
		oldReferenced[m[1]] = true
	}
	if oldReferenced["nested_only_field"] {
		t.Errorf("the old anchored regex unexpectedly caught the nested leaf; the test premise is wrong")
	}
}

// documentationFindingPacketSchemaDeclaredProperties reads the generated
// documentation_finding.v1.schema.json and
// documentation_evidence_packet.v1.schema.json JSON Schemas and returns the
// union of their declared property names.
func documentationFindingPacketSchemaDeclaredProperties(t *testing.T) map[string]bool {
	t.Helper()

	schemaDir := documentationSchemaDir(t)
	declared := map[string]bool{}
	for _, name := range []string{
		"documentation_finding.v1.schema.json",
		"documentation_evidence_packet.v1.schema.json",
	} {
		raw, err := os.ReadFile(filepath.Join(schemaDir, name))
		if err != nil {
			t.Fatalf("read schema %q: %v", name, err)
		}
		var doc struct {
			Properties map[string]json.RawMessage `json:"properties"`
		}
		if err := json.Unmarshal(raw, &doc); err != nil {
			t.Fatalf("unmarshal schema %q: %v", name, err)
		}
		for prop := range doc.Properties {
			declared[prop] = true
		}
	}
	return declared
}

// documentationSchemaDir resolves the checked-in documentation schema
// directory relative to this test file, walking up to the repo root so the
// test does not depend on the working directory.
func documentationSchemaDir(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	// go/internal/query/<file> -> repo root is three levels up.
	repoRoot := filepath.Join(filepath.Dir(thisFile), "..", "..", "..")
	return filepath.Join(repoRoot, "sdk", "go", "factschema", "schema")
}

// readGoSourceText reads a .go file's raw text from this package directory,
// so the SQL-field lockstep assertions above scan the actual source rather
// than a hand-copied excerpt.
func readGoSourceText(t *testing.T, filename string) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed")
	}
	raw, err := os.ReadFile(filepath.Join(filepath.Dir(thisFile), filename))
	if err != nil {
		t.Fatalf("read %q: %v", filename, err)
	}
	return string(raw)
}
