// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package replaycoverage

import (
	"fmt"
	"sort"
	"strings"
)

// DashboardGeneratedMarker is the do-not-edit banner the rendered dashboard
// carries. The lockstep test and reviewers use it to recognize the generated
// artifact; hand-edits are overwritten on the next gate run.
const DashboardGeneratedMarker = "<!-- GENERATED by replay-coverage-gate — do not edit. Refresh: cd go && go test ./cmd/replay-coverage-gate/ -update-dashboard -->"

// axisLabels maps each coverage registry to the human axis name shown on the
// dashboard, so an operator reads "Collectors" rather than "surface_inventory".
var axisLabels = map[Registry]string{
	RegistrySurfaceInventory:    "Collectors",
	RegistryFactKind:            "Read surfaces (API/MCP)",
	RegistryCLIReadSurface:      "Read surfaces (CLI)",
	RegistryParserLedger:        "Parsers",
	RegistryCapabilityMatrix:    "Capability claims",
	RegistryProductClaims:       "Product claims",
	RegistryRetractableType:     "Retractable node types (delta)",
	RegistryRetractableEdgeType: "Retractable edge types (delta)",
	RegistryProjection:          "Projections (cost/ordering)",
	RegistryReducerDrain:        "Reducer drain (crash)",
}

// axisLabel returns the friendly axis name for a registry, falling back to the
// raw registry string for any registry without a mapping.
func axisLabel(reg Registry) string {
	if l, ok := axisLabels[reg]; ok {
		return l
	}
	return string(reg)
}

// RenderDashboard renders the coverage report as a deterministic Markdown
// dashboard: the overall percentage, a per-axis table, the named gap list grouped
// by axis, and the covered-surface table with each surface's scenario, proof
// gate, and artifact ref. It is the C-7 (#4179) visibility deliverable — a
// committed, docs-discoverable artifact that burns down as C-lane coverage lands.
// The output is byte-stable for a given report so the lockstep gate can diff it.
func RenderDashboard(rep CoverageReport) []byte {
	var b strings.Builder
	b.WriteString("# Replay coverage\n\n")
	b.WriteString(DashboardGeneratedMarker)
	b.WriteString("\n\n")
	b.WriteString("Every surface Eshu claims to support should have a green, credential-free, ")
	b.WriteString("Docker-free replay scenario. This dashboard is generated from the C-1 coverage ")
	b.WriteString("manifest and the source-of-truth registries (epic ")
	b.WriteString("[#4172](https://github.com/eshu-hq/eshu/issues/4172)); it is refreshed by the ")
	b.WriteString("replay-coverage gate so the gap is reviewable in a PR diff.\n\n")

	fmt.Fprintf(&b, "**Overall: %d/%d surfaces satisfied (%.2f%%)** — mode: %s.\n\n",
		rep.Totals.Covered+rep.Totals.Exempt, rep.Totals.Total, rep.Totals.PercentSatisfied, modeLabel(rep.Blocking))

	writeAxisTable(&b, rep)
	writeScenarioTypeTable(&b, rep)
	writeLanguageScoreboard(&b, rep)
	writeGaps(&b, rep)
	writeCovered(&b, rep)
	if len(rep.Stale) > 0 {
		writeStale(&b, rep)
	}
	// Exactly one trailing newline so the committed artifact matches the repo's
	// end-of-file-fixer hook (which would otherwise rewrite it and break the
	// lockstep test).
	return []byte(strings.TrimRight(b.String(), "\n") + "\n")
}

// writeLanguageScoreboard renders the C-11 (#4364) language-parser coverage
// scoreboard: the honest exempt/uncovered split across every language in the
// language-feature-parity ledger, plus the explicit uncovered list (the C-12
// #4365 fixture-backfill worklist). It is visibility-only — these languages do
// not gate the build — so it is reported separately from the blocking axis
// table. The section is omitted when no ledger is loaded (e.g. renderer tests).
func writeLanguageScoreboard(b *strings.Builder, rep CoverageReport) {
	board := rep.LanguageScoreboard
	if board.Total == 0 {
		return
	}
	b.WriteString("## Language parser coverage\n\n")
	b.WriteString("Visibility-only scoreboard (C-11, ")
	b.WriteString("[#4364](https://github.com/eshu-hq/eshu/issues/4364)) over every language in ")
	b.WriteString("`specs/language-feature-parity-ledger.v1.yaml`. A language is *exempt* when it is ")
	b.WriteString("exercised end-to-end by the golden-corpus 20-repo corpus; the rest are *uncovered* ")
	b.WriteString("— the C-12 ([#4365](https://github.com/eshu-hq/eshu/issues/4365)) fixture-backfill ")
	b.WriteString("worklist. This scoreboard does not gate the build.\n\n")
	fmt.Fprintf(b, "**%d/%d languages exercised by the corpus (%.2f%%); %d uncovered.**\n\n",
		board.Exempt, board.Total, board.PercentSatisfied, board.Uncovered)

	uncovered := make([]string, 0, board.Uncovered)
	for _, row := range board.Languages {
		if row.Status == LanguageUncovered {
			uncovered = append(uncovered, row.Language)
		}
	}
	if len(uncovered) > 0 {
		fmt.Fprintf(b, "Uncovered (%d) — needs a parser-fixture replay scenario:\n\n", len(uncovered))
		for _, lang := range uncovered {
			fmt.Fprintf(b, "- `%s`\n", lang)
		}
		b.WriteString("\n")
	} else {
		b.WriteString("Every ledger language is corpus-exercised.\n\n")
	}

	if len(board.StaleExemptions) > 0 {
		b.WriteString("Stale language exemptions (map no ledger language — a language was renamed or removed):\n\n")
		for _, s := range board.StaleExemptions {
			fmt.Fprintf(b, "- `%s`\n", s)
		}
		b.WriteString("\n")
	}
}

func writeScenarioTypeTable(b *strings.Builder, rep CoverageReport) {
	b.WriteString("## Coverage by scenario type\n\n")
	b.WriteString("| Scenario type | Satisfied | Total | % | Uncovered | Exempt |\n")
	b.WriteString("| --- | ---: | ---: | ---: | ---: | ---: |\n")
	for _, s := range rep.ScenarioTypeSummaries {
		fmt.Fprintf(b, "| %s | %d | %d | %.2f%% | %d | %d |\n",
			s.ScenarioType, s.Covered+s.Exempt, s.Total, s.PercentSatisfied, s.Uncovered+s.Unresolved, s.Exempt)
	}
	b.WriteString("\n")
}

// modeLabel renders the gate mode for the dashboard header.
func modeLabel(blocking bool) string {
	if blocking {
		return "blocking"
	}
	return "advisory"
}

func writeAxisTable(b *strings.Builder, rep CoverageReport) {
	b.WriteString("## Coverage by axis\n\n")
	b.WriteString("| Axis | Satisfied | Total | % | Uncovered | Exempt |\n")
	b.WriteString("| --- | ---: | ---: | ---: | ---: | ---: |\n")
	for _, s := range rep.Summaries {
		fmt.Fprintf(b, "| %s | %d | %d | %.2f%% | %d | %d |\n",
			axisLabel(s.Registry), s.Covered+s.Exempt, s.Total, s.PercentSatisfied, s.Uncovered+s.Unresolved, s.Exempt)
	}
	fmt.Fprintf(b, "| **Total** | **%d** | **%d** | **%.2f%%** | **%d** | **%d** |\n\n",
		rep.Totals.Covered+rep.Totals.Exempt, rep.Totals.Total, rep.Totals.PercentSatisfied,
		rep.Totals.Uncovered+rep.Totals.Unresolved, rep.Totals.Exempt)
}

// writeGaps lists the uncovered/unresolved surfaces grouped by axis, in the same
// registry order as the axis table, so the worklist is legible per owner.
func writeGaps(b *strings.Builder, rep CoverageReport) {
	b.WriteString("## Gaps — surfaces still needing a replay scenario\n\n")
	if len(rep.Gaps) == 0 {
		b.WriteString("None. Every supported surface has a replay scenario.\n\n")
		return
	}
	fmt.Fprintf(b, "%d surface(s) uncovered or unresolved:\n\n", len(rep.Gaps))

	gapByRegistry := map[Registry][]SurfaceReport{}
	for _, s := range rep.Surfaces {
		if s.Status == StatusUncovered || s.Status == StatusUnresolved {
			gapByRegistry[s.Registry] = append(gapByRegistry[s.Registry], s)
		}
	}
	// Iterate the report's own registry summaries (breadth registries plus any
	// depth-applicability registry present) so depth gaps are grouped and shown,
	// not silently dropped by iterating only the static breadth registries.
	for _, summary := range rep.Summaries {
		reg := summary.Registry
		rows := gapByRegistry[reg]
		if len(rows) == 0 {
			continue
		}
		sort.Slice(rows, func(i, j int) bool { return rows[i].Key < rows[j].Key })
		fmt.Fprintf(b, "### %s (%d)\n\n", axisLabel(reg), len(rows))
		for _, s := range rows {
			suffix := ""
			if s.Status == StatusUnresolved {
				suffix = " — _unresolved: manifest entry present but artifact missing_"
			}
			fmt.Fprintf(b, "- `%s` (%s)%s\n", s.Key, s.ScenarioType, suffix)
		}
		b.WriteString("\n")
	}
}

// writeCovered renders the covered surfaces with their scenario, proof gate, and
// artifact ref so a reader can click through from a covered surface to the
// scenario that proves it.
func writeCovered(b *strings.Builder, rep CoverageReport) {
	covered := make([]SurfaceReport, 0, len(rep.Surfaces))
	for _, s := range rep.Surfaces {
		if s.Status == StatusCovered || s.Status == StatusExempt {
			covered = append(covered, s)
		}
	}
	fmt.Fprintf(b, "## Covered surfaces (%d)\n\n", len(covered))
	if len(covered) == 0 {
		b.WriteString("None yet.\n\n")
		return
	}
	b.WriteString("| Surface | Scenario type | Scenario | Proof gate | Artifact |\n")
	b.WriteString("| --- | --- | --- | --- | --- |\n")
	for _, s := range covered {
		scenario := s.Scenario
		if s.Status == StatusExempt {
			scenario = "exempt"
		}
		ref := s.Ref
		if ref == "" {
			ref = "—"
		} else {
			ref = "`" + ref + "`"
		}
		gate := s.ProofGate
		if gate == "" {
			gate = "—"
		}
		fmt.Fprintf(b, "| `%s` | %s | %s | %s | %s |\n", s.Key, s.ScenarioType, scenario, gate, ref)
	}
	b.WriteString("\n")
}

func writeStale(b *strings.Builder, rep CoverageReport) {
	b.WriteString("## Stale manifest entries\n\n")
	b.WriteString("These manifest entries map no supported surface (a surface was renamed or removed):\n\n")
	for _, s := range rep.Stale {
		fmt.Fprintf(b, "- `%s`\n", s)
	}
	b.WriteString("\n")
}
