// authSession.ts — pure helpers for browser-session lifecycle.
// No DOM side-effects; redirect callers accept an optional redirect fn so tests
// can verify the URL without triggering navigation.
import type { BrowserSessionResponse, EshuApiClient } from "./client";
import { EshuApiHttpError } from "./client";

// loadCurrentSession fetches the current server-managed browser session.
// Returns null when no session exists (401/403/404). Rethrows all other errors
// so callers can distinguish "no session" from "API unavailable".
export async function loadCurrentSession(
  client: EshuApiClient,
): Promise<BrowserSessionResponse | null> {
  try {
    return await client.getBrowserSession();
  } catch (e) {
    if (
      e instanceof EshuApiHttpError &&
      (e.status === 401 || e.status === 403 || e.status === 404)
    ) {
      return null;
    }
    throw e;
  }
}

// LoginLocalOptions carries the credentials for local-identity login.
// Backend field names: login_id, password, and one of totp_code /
// recovery_code (issue #4986: the second-factor proof; the backend checks
// totp_code first when both are set).
export interface LoginLocalOptions {
  readonly login: string;
  readonly password: string;
  readonly mfaCode?: string;
}

// SIX_DIGIT_CODE classifies mfaCode as a TOTP authenticator-app code
// (issue #4986). Recovery codes generated by the backend
// (go/internal/query/local_identity_requests.go RecoveryCodes) are opaque
// operator-supplied strings, never constrained to 6 numeric digits, so this
// heuristic lets one input field serve both proof types without a mode
// toggle: a submitted value matching exactly 6 digits is sent as
// totp_code; anything else is sent as recovery_code.
const SIX_DIGIT_CODE = /^\d{6}$/;

// LocalLoginResult is a discriminated union of every possible local-login
// outcome. The backend always returns a JSON body even on 4xx (confirmed from
// go/internal/query/local_identity_handler_helpers.go:writeLocalIdentityUnauthenticated).
// HTTP status codes map as follows:
//   200 → { status: "ok", session }    — full BrowserSessionResponse in body
//   202 → { status: "mfa_required" }   — password accepted, MFA proof needed
//   423 → { status: "locked", lockedUntil? } — EshuApiHttpError status=423
//   403 → { status: "disabled" }       — EshuApiHttpError status=403
//   401 → { status: "invalid" }        — EshuApiHttpError status=401
// Any other error (5xx, network, timeout) is rethrown — never swallowed.
export type LocalLoginResult =
  | { readonly status: "ok"; readonly session: BrowserSessionResponse }
  | { readonly status: "mfa_required" }
  | { readonly status: "locked"; readonly lockedUntil?: string }
  | { readonly status: "disabled" }
  | { readonly status: "invalid" };

// LocalLoginRawResponse is the union of shapes the backend can return on
// POST /api/v0/auth/local/login for any 2xx status. Status 202 carries only
// the status marker; status 200 carries the full BrowserSessionResponse under
// `session`. Keeping the union narrow (instead of `any`) keeps downstream
// access typed and ESLint happy.
export type LocalLoginRawResponse =
  | { readonly status: "mfa_required" }
  | ({ readonly status: "ok" } & BrowserSessionResponse);

// loginLocal POSTs credentials to /api/v0/auth/local/login and returns a
// discriminated LocalLoginResult. Non-auth errors (5xx, network) are rethrown.
// Exact backend field names from go/internal/query/local_identity_requests.go:
//   login_id, password, recovery_code
export async function loginLocal(
  client: EshuApiClient,
  opts: LoginLocalOptions,
): Promise<LocalLoginResult> {
  const body: Record<string, string> = {
    login_id: opts.login,
    password: opts.password,
  };
  const mfaCode = opts.mfaCode?.trim() ?? "";
  if (mfaCode.length > 0) {
    if (SIX_DIGIT_CODE.test(mfaCode)) {
      body["totp_code"] = mfaCode;
    } else {
      body["recovery_code"] = mfaCode;
    }
  }
  try {
    // postJson resolves for 2xx. 202 (mfa_required) is 2xx, so it resolves
    // with the body {status:"mfa_required"} — not a BrowserSessionResponse.
    // The narrow `LocalLoginRawResponse` keeps the status field typed while
    // letting us cast to BrowserSessionResponse in the success branch.
    const raw = await client.postJson<LocalLoginRawResponse>("/api/v0/auth/local/login", body);
    if (raw.status === "mfa_required") {
      return { status: "mfa_required" };
    }
    // 200 authenticated — body is the BrowserSessionResponse itself; wrap it
    // for the discriminated result.
    return { status: "ok", session: raw };
  } catch (e) {
    if (e instanceof EshuApiHttpError) {
      if (e.status === 423) {
        // Body carries locked_until as ISO string but postJson threw — we cannot
        // read the response body here. Callers display generic locked message.
        return { status: "locked" };
      }
      if (e.status === 403) {
        return { status: "disabled" };
      }
      if (e.status === 401) {
        return { status: "invalid" };
      }
      // Any other HTTP error (5xx, 503, etc.) is not an auth outcome — rethrow.
      throw e;
    }
    // Network/timeout errors — rethrow.
    throw e;
  }
}

// OidcLoginOptions selects the provider and optional workspace context.
// Query param names confirmed from go/internal/query/oidc_login_handler.go:
//   provider_config_id, tenant_id, workspace_id, return_to
export interface OidcLoginOptions {
  readonly providerConfigId: string;
  readonly tenantId?: string;
  readonly workspaceId?: string;
  readonly returnTo: string;
}

// beginOidcLogin builds the OIDC login redirect URL and optionally performs
// the redirect via redirectFn (defaults to location.assign). Returns the URL
// so tests can verify it without triggering navigation.
// NOTE: No provider-discovery endpoint exists in Slice A (#3682). The UI
// hides OIDC/SAML buttons until provider discovery is wired up.
export function beginOidcLogin(
  baseUrl: string,
  opts: OidcLoginOptions,
  redirectFn?: (url: string) => void,
): string {
  const normalizedBase = baseUrl.endsWith("/") ? baseUrl.slice(0, -1) : baseUrl;
  const params = new URLSearchParams();
  params.set("provider_config_id", opts.providerConfigId);
  if (opts.tenantId) params.set("tenant_id", opts.tenantId);
  if (opts.workspaceId) params.set("workspace_id", opts.workspaceId);
  params.set("return_to", opts.returnTo);
  const url = `${normalizedBase}/api/v0/auth/oidc/login?${params.toString()}`;
  if (redirectFn) {
    redirectFn(url);
  }
  return url;
}

// SamlLoginOptions selects the SAML provider by ID.
// Path param: provider_id (from GET /api/v0/auth/saml/providers/{provider_id}/login)
// NOTE: No provider-discovery endpoint exists in Slice A (#3682). The UI
// hides OIDC/SAML buttons until provider discovery is wired up.
export interface SamlLoginOptions {
  readonly providerId: string;
  readonly returnTo: string;
}

// beginSamlLogin builds the SAML login redirect URL and optionally performs
// the redirect via redirectFn. Returns the URL for testability.
export function beginSamlLogin(
  baseUrl: string,
  opts: SamlLoginOptions,
  redirectFn?: (url: string) => void,
): string {
  const normalizedBase = baseUrl.endsWith("/") ? baseUrl.slice(0, -1) : baseUrl;
  const params = new URLSearchParams();
  params.set("return_to", opts.returnTo);
  const url = `${normalizedBase}/api/v0/auth/saml/providers/${encodeURIComponent(opts.providerId)}/login?${params.toString()}`;
  if (redirectFn) {
    redirectFn(url);
  }
  return url;
}

// AuthLoginProvider is the pre-auth view of one configured SSO provider.
// Only the opaque provider_config_id, a safe generic display_label, the
// protocol class (provider_kind), and a generic icon_hint are ever returned —
// no secrets, metadata URLs, IdP hostnames, org names, or group names. Shape
// matches go/internal/query/auth_providers_handler.go AuthProviderItem.
export interface AuthLoginProvider {
  readonly provider_config_id: string;
  readonly display_label: string;
  readonly provider_kind: "oidc" | "saml";
  readonly icon_hint: "oidc" | "saml";
}

// AuthPosture is the tenant's derived pre-auth sign-in posture (issue #5165,
// F-4): the configured providers, whether the local password form is
// offered, and whether self-service personal API tokens are offered. Shape
// matches go/internal/query/auth_posture.go AuthPosture verbatim — this is
// the SAME derivation issue #5163 (F-2)'s MCP OAuth discovery consumes
// server-side, so the console and MCP surfaces never disagree on posture.
export interface AuthPosture {
  readonly providers: readonly AuthLoginProvider[];
  readonly local_login_offered: boolean;
  readonly self_service_tokens_offered: boolean;
}

// FAIL_OPEN_POSTURE is the safe local-only default: no SSO buttons, local
// form shown, self-service tokens assumed available. Used whenever the
// posture cannot be determined (network/HTTP error) or a field is missing
// from an older backend response — mirrors the backend's own fail-open
// defaults for an empty tenant_id or a policy-store read error (see
// query.DeriveAuthPosture's doc comment).
const FAIL_OPEN_POSTURE: AuthPosture = {
  providers: [],
  local_login_offered: true,
  self_service_tokens_offered: true,
};

// PartialAuthPostureWire is the subset of AuthPosture fields the backend
// response is expected to carry. Modeled as partial (rather than requiring
// every field) so a response from an older backend build — or any field a
// future migration temporarily omits — degrades to FAIL_OPEN_POSTURE's safe
// per-field defaults instead of throwing or rendering `undefined`.
interface PartialAuthPostureWire {
  readonly providers?: readonly AuthLoginProvider[];
  readonly local_login_offered?: boolean;
  readonly self_service_tokens_offered?: boolean;
}

// listAuthPosture fetches the tenant's derived sign-in posture from GET
// /api/v0/auth/providers (one discovery call, replacing the console's former
// separate listAuthProviders + loadPublicRequireSSO fetches). tenantId must
// be non-empty to receive anything but the safe zero-configuration default;
// when tenantId is absent the endpoint returns that default (no global
// cross-tenant scan). On any fetch failure this returns FAIL_OPEN_POSTURE so
// the login page always falls back to local-only rather than breaking.
export async function listAuthPosture(
  client: EshuApiClient,
  tenantId?: string,
): Promise<AuthPosture> {
  try {
    const trimmed = tenantId?.trim() ?? "";
    const path =
      trimmed.length > 0
        ? `/api/v0/auth/providers?tenant_id=${encodeURIComponent(trimmed)}`
        : "/api/v0/auth/providers";
    const resp = await client.getJson<PartialAuthPostureWire>(path);
    return {
      providers: resp.providers ?? FAIL_OPEN_POSTURE.providers,
      local_login_offered: resp.local_login_offered ?? FAIL_OPEN_POSTURE.local_login_offered,
      self_service_tokens_offered:
        resp.self_service_tokens_offered ?? FAIL_OPEN_POSTURE.self_service_tokens_offered,
    };
  } catch (err) {
    // Pre-auth network errors must never break the login form, but warn so
    // backend outages are visible in devtools during development and triage.
    console.warn(
      "[eshu] GET /api/v0/auth/providers failed — falling back to local-only login",
      err,
    );
    return FAIL_OPEN_POSTURE;
  }
}

// logout revokes the current browser session.
export async function logout(client: EshuApiClient): Promise<void> {
  await client.logoutBrowserSession();
}

// InsecureCookieOrigin is the subset of window.location this module reads to
// classify an origin. Accepting this narrow shape (instead of the global
// Location) lets tests pass a plain object without monkey-patching jsdom.
export interface InsecureCookieOrigin {
  readonly protocol: string;
  readonly hostname: string;
}

// isCookiePersistenceAtRiskOrigin mirrors the backend's #4964 origin
// classification exactly (go/internal/query/browser_session_cookie_secure.go):
// the default ESHU_AUTH_COOKIE_SECURE=auto mode relaxes the Secure cookie
// attribute only for a plain-HTTP loopback origin (localhost, 127.0.0.0/8,
// ::1). Any other plain-HTTP origin still gets a Secure cookie, which the
// browser refuses to store — the session silently would not persist there.
// LoginPage uses this to show an actionable diagnostic banner instead of a
// confusing "session lost" experience.
export function isCookiePersistenceAtRiskOrigin(
  loc: InsecureCookieOrigin = globalThis.location,
): boolean {
  if (loc.protocol === "https:") return false;
  const hostname = loc.hostname.replace(/^\[|\]$/g, "").toLowerCase();
  if (hostname === "localhost" || hostname === "::1") return false;
  const isLoopbackIPv4 = /^127\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(hostname);
  return !isLoopbackIPv4;
}

// INSECURE_COOKIE_ORIGIN_MESSAGE names the exact remediation for an origin
// where the session cookie will not persist: switch to a loopback address,
// front the console with a TLS-terminating tunnel/proxy, or serve it over
// HTTPS directly.
export const INSECURE_COOKIE_ORIGIN_MESSAGE =
  "Your session will not stay signed in here — plain HTTP outside localhost cannot keep a session cookie. Use http://localhost, put a TLS tunnel/proxy in front, or serve this over HTTPS.";
