// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq
//
// Code generated by scripts/generate-dirgate-grandfather-go.sh from
// scripts/lib/dirgate-grandfather.tsv and
// scripts/lib/dirgate-naming-exempt.tsv; DO NOT EDIT BY HAND.

package main

// grandfatheredDirectories is the digest-pinned ledger of package
// directories that already exceeded the 40-non-test-.go-file cap when the
// dirgate gate landed (issue #6054), so the gate lands green on today's
// tree instead of failing on the entire pre-existing sprawl it exists to
// stop from growing further, merged with the per-file naming exemptions
// pinned for the same directories. See grandfatherEntry and
// evaluateCapViolation for the exact pass/fail rule FileCount/Digest are
// checked with, namingExemptSet for how NamingExempt is checked, and
// scripts/lib/dirgate-grandfather.tsv plus
// scripts/lib/dirgate-naming-exempt.tsv for the sources of truth this map
// is generated from -- edit those TSVs, then re-run
// scripts/generate-dirgate-grandfather-go.sh, never this file directly.
var grandfatheredDirectories = map[string]grandfatherEntry{
	"internal/collector/awscloud": {FileCount: 154, Digest: "5f0ea4b0c73faae13cc03f3c05609b6a7b6befd92941cfa599b08ff5c2fae641"},
	"internal/collector/gcpcloud": {FileCount: 96, Digest: "0cb76eb63cd133ea5dc15c2556fb64b08db61757f23372af1c0e170845858af3"},
	"internal/collector/gitrepo":  {FileCount: 66, Digest: "774b96b40dbec9964c434c50a6056df7780e8909ecb3a0f43e1ffe17e606eae3"},
	"internal/coordinator":        {FileCount: 49, Digest: "e39400aa04976497d8e4f169e8b8de10e3e1b16d40a5f9b9f31ff7f7da64377e"},
	"internal/facts":              {FileCount: 45, Digest: "4622f2b6b606a2878aa88dfa1b5e5916edad5ef536989b4136774e25c1367c4e"},
	"internal/mcp":                {FileCount: 105, Digest: "ecc069f30a7319acc9ee2a6c2a2805636e946f9a1041e8817afb14357b31bd15"},
	"internal/parser":             {FileCount: 47, Digest: "dc6d2390c51ca20550859d3f746a14ec3899765ea31c9a8707532c6e709d2a09", NamingExempt: []string{"c_language.go", "cpp_language.go", "csharp_language.go", "dart_language.go", "dockerfile_language.go", "elixir_language.go", "gomod_language.go", "gradle_language.go", "groovy_language.go", "hcl_language.go", "java_language.go", "java_metadata_files.go", "javascript_language.go", "json_language.go", "kotlin_language.go", "maven_language.go", "perl_haskell_language.go", "php_language.go", "python_dep_language.go", "python_language.go", "ruby_language.go", "rust_language.go", "scala_language.go", "shared_bridge.go", "sql_language.go", "swift_language.go", "yaml_language.go"}},
	"internal/parser/golang":      {FileCount: 42, Digest: "a27d65bfc9ffe3085e35e66aab932d0c361bea10ac34e407dd3300205379e039"},
	"internal/parser/javascript":  {FileCount: 48, Digest: "b6aaa1628818f74382a4b7eee937f476f991d613f624a325b930fd89aa7e437c"},
	"internal/projector":          {FileCount: 47, Digest: "90bc68bb690013862bc225b94c15ff4d758882a9c4cfb57363b8af52c45e123d"},
	"internal/query":              {FileCount: 787, Digest: "39e91764858d5145a3821b5c3206d7fc956acb9fb41cf9661838a7593541715d"},
	"internal/reducer":            {FileCount: 354, Digest: "e522a81dfe929e90db19651d328a2b6618198372ff9c4fd7c013bd1e013239b0"},
	"internal/status":             {FileCount: 45, Digest: "c7dfe62bb4c04da7f242ba8d2a8fb744865937c103df10c5374f05df25ce9261"},
	"internal/storage/cypher":     {FileCount: 131, Digest: "eb310aa90dadf1c8bba189a65bd0c9f529c9c40a59e098789465e073f1996de7"},
	"internal/storage/postgres":   {FileCount: 372, Digest: "813c9bf8a06608058485c87e4f80b720de917ce01ca0a087358f8d9de5b3f883"},
	"internal/telemetry":          {FileCount: 42, Digest: "b33686b92bd3c69804d61fc7ee9bc9e8ccd5a111b3b96cd74a9ea7b8d71313c9"},
}
