// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq
//
// Code generated by scripts/generate-dirgate-grandfather-go.sh from
// scripts/lib/dirgate-grandfather.tsv and
// scripts/lib/dirgate-naming-exempt.tsv; DO NOT EDIT BY HAND.

package main

// grandfatheredDirectories is the digest-pinned ledger of package
// directories that already exceeded the 40-non-test-.go-file cap when the
// dirgate gate landed (issue #6054), so the gate lands green on today's
// tree instead of failing on the entire pre-existing sprawl it exists to
// stop from growing further, merged with the per-file naming exemptions
// pinned for the same directories. See grandfatherEntry and
// evaluateCapViolation for the exact pass/fail rule FileCount/Digest are
// checked with, namingExemptSet for how NamingExempt is checked, and
// scripts/lib/dirgate-grandfather.tsv plus
// scripts/lib/dirgate-naming-exempt.tsv for the sources of truth this map
// is generated from -- edit those TSVs, then re-run
// scripts/generate-dirgate-grandfather-go.sh, never this file directly.
var grandfatheredDirectories = map[string]grandfatherEntry{
	"internal/collector/awscloud": {FileCount: 154, Digest: "7f55ebaf069c318deeb9e220f97a5387f9f33011a08e6c72b8497b38a396cbfd"},
	"internal/collector/gcpcloud": {FileCount: 96, Digest: "0cb76eb63cd133ea5dc15c2556fb64b08db61757f23372af1c0e170845858af3"},
	"internal/collector/repo/git": {FileCount: 65, Digest: "c52b52eda6e521c5b56988994f637f36708e6810e1b6c04386d6081d845e78bb"},
	"internal/facts":              {FileCount: 45, Digest: "4622f2b6b606a2878aa88dfa1b5e5916edad5ef536989b4136774e25c1367c4e"},
	"internal/mcp":                {FileCount: 93, Digest: "2d88cefb5f7b666fbfd8f55216a1a9a6756de20bc3617ea9c09f0dab6cee1e8b"},
	"internal/parser":             {FileCount: 45, Digest: "ec26538203a8717bfb5cdc794d85fd02156914c7678f1683f1229d13cf7c6bf5", NamingExempt: []string{"c_language.go", "cpp_language.go", "csharp_language.go", "dart_language.go", "dockerfile_language.go", "elixir_language.go", "gomod_language.go", "gradle_language.go", "groovy_language.go", "hcl_language.go", "java_language.go", "java_metadata_files.go", "javascript_language.go", "json_language.go", "kotlin_language.go", "maven_language.go", "perl_haskell_language.go", "php_language.go", "python_dep_language.go", "python_language.go", "ruby_language.go", "rust_language.go", "scala_language.go", "shared_bridge.go", "sql_language.go", "swift_language.go", "yaml_language.go"}},
	"internal/parser/javascript":  {FileCount: 44, Digest: "06dc4d9f02cb7499686049b7ddebc40458cc6c2edff8c1c94a6610d574d80832"},
	"internal/query":              {FileCount: 277, Digest: "9c52f08bbe86185263d306745269f3df99b31608126c77a9184125f6b67ee005"},
	"internal/reducer":            {FileCount: 128, Digest: "d074549cd2d2306c02901ac6eafa52c568bb06c7502bcbd76fcdb3fbf3e85273"},
	"internal/status":             {FileCount: 45, Digest: "c7dfe62bb4c04da7f242ba8d2a8fb744865937c103df10c5374f05df25ce9261"},
	"internal/storage/cypher":     {FileCount: 108, Digest: "8db858257e7816803e50ea7a393651b8d58a8f3097cf5d95c4eac39b7d4b1a69"},
	"internal/storage/postgres":   {FileCount: 368, Digest: "6e9ff9178f87fa2ccc24e160692f769777592f33c9decdbe8ee24ea77df69b0a"},
	"internal/telemetry":          {FileCount: 42, Digest: "b33686b92bd3c69804d61fc7ee9bc9e8ccd5a111b3b96cd74a9ea7b8d71313c9"},
}
