// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq
//
// Code generated by scripts/generate-dirgate-grandfather-go.sh from
// scripts/lib/dirgate-grandfather.tsv and
// scripts/lib/dirgate-naming-exempt.tsv; DO NOT EDIT BY HAND.

package main

// grandfatheredDirectories is the digest-pinned ledger of package
// directories that already exceeded the 40-non-test-.go-file cap when the
// dirgate gate landed (issue #6054), so the gate lands green on today's
// tree instead of failing on the entire pre-existing sprawl it exists to
// stop from growing further, merged with the per-file naming exemptions
// pinned for the same directories. See grandfatherEntry and
// evaluateCapViolation for the exact pass/fail rule FileCount/Digest are
// checked with, namingExemptSet for how NamingExempt is checked, and
// scripts/lib/dirgate-grandfather.tsv plus
// scripts/lib/dirgate-naming-exempt.tsv for the sources of truth this map
// is generated from -- edit those TSVs, then re-run
// scripts/generate-dirgate-grandfather-go.sh, never this file directly.
var grandfatheredDirectories = map[string]grandfatherEntry{
	"internal/collector/awscloud": {FileCount: 154, Digest: "7f55ebaf069c318deeb9e220f97a5387f9f33011a08e6c72b8497b38a396cbfd"},
	"internal/collector/gcpcloud": {FileCount: 96, Digest: "0cb76eb63cd133ea5dc15c2556fb64b08db61757f23372af1c0e170845858af3"},
	"internal/collector/repo/git": {FileCount: 65, Digest: "c52b52eda6e521c5b56988994f637f36708e6810e1b6c04386d6081d845e78bb"},
	"internal/mcp":                {FileCount: 93, Digest: "2d88cefb5f7b666fbfd8f55216a1a9a6756de20bc3617ea9c09f0dab6cee1e8b"},
	"internal/parser":             {FileCount: 45, Digest: "ec26538203a8717bfb5cdc794d85fd02156914c7678f1683f1229d13cf7c6bf5", NamingExempt: []string{"c_language.go", "cpp_language.go", "csharp_language.go", "dart_language.go", "dockerfile_language.go", "elixir_language.go", "gomod_language.go", "gradle_language.go", "groovy_language.go", "hcl_language.go", "java_language.go", "java_metadata_files.go", "javascript_language.go", "json_language.go", "kotlin_language.go", "maven_language.go", "perl_haskell_language.go", "php_language.go", "python_dep_language.go", "python_language.go", "ruby_language.go", "rust_language.go", "scala_language.go", "shared_bridge.go", "sql_language.go", "swift_language.go", "yaml_language.go"}},
	"internal/query":              {FileCount: 272, Digest: "7e02db6d99e07030f8bcdff54eb1f4083f2be1391a6eaace0a612a686d329035"},
	"internal/reducer":            {FileCount: 128, Digest: "d074549cd2d2306c02901ac6eafa52c568bb06c7502bcbd76fcdb3fbf3e85273"},
	"internal/storage/cypher":     {FileCount: 109, Digest: "e8063838d416354547735422111cdaa416b281a48d60a7a49245ed3abb92660e"},
	"internal/storage/postgres":   {FileCount: 358, Digest: "18ca4bf7e90c1e7b7912db74179975780dff797c8880b8d03cb64fa61de2b420"},
}
