// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package reducer

import observabilityv1 "github.com/eshu-hq/eshu/sdk/go/factschema/observability/v1"

// Observed/applied-signal and coverage-warning lane converters for the
// observability metadata view. See observability_coverage_metadata_view.go for
// the converter contract.

// viewFromObservedDashboard maps observabilityv1.ObservedDashboard into the metadata view.
func viewFromObservedDashboard(s observabilityv1.ObservedDashboard) observabilityMetadataView {
	return observabilityMetadataView{
		providerObjectUID:           s.ProviderObjectUID,
		dashboardUID:                derefOr(s.DashboardUID),
		datasourceUID:               derefOr(s.DatasourceUID),
		alertRuleUID:                derefOr(s.AlertRuleUID),
		folderUID:                   derefOr(s.FolderUID),
		resourceIdentity:            derefOr(s.ResourceIdentity),
		resourceIdentityFingerprint: derefOr(s.ResourceIdentityFingerprint),
		resourceName:                derefOr(s.ResourceName),
		pipelineName:                derefOr(s.PipelineName),
		selectorIdentityFingerprint: derefOr(s.SelectorIdentityFingerprint),
		ruleGroup:                   derefOr(s.RuleGroup),
		ruleName:                    derefOr(s.RuleName),
		alertRuleNameFingerprint:    derefOr(s.AlertRuleNameFingerprint),
		recordRuleNameFingerprint:   derefOr(s.RecordRuleNameFingerprint),
		routeDestinationFingerprint: derefOr(s.RouteDestinationFingerprint),
		labelIdentityFingerprint:    derefOr(s.LabelIdentityFingerprint),
		traceTagIdentityFingerprint: derefOr(s.TraceTagIdentityFingerprint),
		tagName:                     derefOr(s.TagName),
		seriesFingerprint:           derefOr(s.SeriesFingerprint),
		appName:                     derefOr(s.AppName),
		provider:                    derefOr(s.Provider),
		backendKind:                 derefOr(s.BackendKind),
		sourceKind:                  derefOr(s.SourceKind),
		sourceClass:                 derefOr(s.SourceClass),
		resourceClass:               derefOr(s.ResourceClass),
		observabilityResourceClass:  derefOr(s.ObservabilityResourceClass),
		resourceKind:                derefOr(s.ResourceKind),
		outcome:                     derefOr(s.Outcome),
		freshnessState:              derefOr(s.FreshnessState),
		warningKind:                 derefOr(s.WarningKind),
		driftCandidateReason:        derefOr(s.DriftCandidateReason),
		declaredMatchState:          derefOr(s.DeclaredMatchState),
		serviceHints:                derefOr(s.ServiceHints),
		serviceRef:                  derefOr(s.ServiceRef),
	}
}

// viewFromObservedTarget maps observabilityv1.ObservedTarget into the metadata view.
func viewFromObservedTarget(s observabilityv1.ObservedTarget) observabilityMetadataView {
	return observabilityMetadataView{
		providerObjectUID:           s.ProviderObjectUID,
		dashboardUID:                derefOr(s.DashboardUID),
		datasourceUID:               derefOr(s.DatasourceUID),
		alertRuleUID:                derefOr(s.AlertRuleUID),
		folderUID:                   derefOr(s.FolderUID),
		resourceIdentity:            derefOr(s.ResourceIdentity),
		resourceIdentityFingerprint: derefOr(s.ResourceIdentityFingerprint),
		resourceName:                derefOr(s.ResourceName),
		pipelineName:                derefOr(s.PipelineName),
		selectorIdentityFingerprint: derefOr(s.SelectorIdentityFingerprint),
		ruleGroup:                   derefOr(s.RuleGroup),
		ruleName:                    derefOr(s.RuleName),
		alertRuleNameFingerprint:    derefOr(s.AlertRuleNameFingerprint),
		recordRuleNameFingerprint:   derefOr(s.RecordRuleNameFingerprint),
		routeDestinationFingerprint: derefOr(s.RouteDestinationFingerprint),
		labelIdentityFingerprint:    derefOr(s.LabelIdentityFingerprint),
		traceTagIdentityFingerprint: derefOr(s.TraceTagIdentityFingerprint),
		tagName:                     derefOr(s.TagName),
		seriesFingerprint:           derefOr(s.SeriesFingerprint),
		appName:                     derefOr(s.AppName),
		provider:                    derefOr(s.Provider),
		backendKind:                 derefOr(s.BackendKind),
		sourceKind:                  derefOr(s.SourceKind),
		sourceClass:                 derefOr(s.SourceClass),
		resourceClass:               derefOr(s.ResourceClass),
		observabilityResourceClass:  derefOr(s.ObservabilityResourceClass),
		resourceKind:                derefOr(s.ResourceKind),
		outcome:                     derefOr(s.Outcome),
		freshnessState:              derefOr(s.FreshnessState),
		warningKind:                 derefOr(s.WarningKind),
		driftCandidateReason:        derefOr(s.DriftCandidateReason),
		declaredMatchState:          derefOr(s.DeclaredMatchState),
		serviceHints:                derefOr(s.ServiceHints),
		serviceRef:                  derefOr(s.ServiceRef),
	}
}

// viewFromObservedRule maps observabilityv1.ObservedRule into the metadata view.
func viewFromObservedRule(s observabilityv1.ObservedRule) observabilityMetadataView {
	return observabilityMetadataView{
		providerObjectUID:           derefOr(s.ProviderObjectUID),
		dashboardUID:                derefOr(s.DashboardUID),
		datasourceUID:               derefOr(s.DatasourceUID),
		alertRuleUID:                derefOr(s.AlertRuleUID),
		folderUID:                   derefOr(s.FolderUID),
		resourceIdentity:            derefOr(s.ResourceIdentity),
		resourceIdentityFingerprint: derefOr(s.ResourceIdentityFingerprint),
		resourceName:                derefOr(s.ResourceName),
		pipelineName:                derefOr(s.PipelineName),
		selectorIdentityFingerprint: derefOr(s.SelectorIdentityFingerprint),
		ruleGroup:                   derefOr(s.RuleGroup),
		ruleName:                    derefOr(s.RuleName),
		alertRuleNameFingerprint:    derefOr(s.AlertRuleNameFingerprint),
		recordRuleNameFingerprint:   derefOr(s.RecordRuleNameFingerprint),
		routeDestinationFingerprint: derefOr(s.RouteDestinationFingerprint),
		labelIdentityFingerprint:    derefOr(s.LabelIdentityFingerprint),
		traceTagIdentityFingerprint: derefOr(s.TraceTagIdentityFingerprint),
		tagName:                     derefOr(s.TagName),
		seriesFingerprint:           derefOr(s.SeriesFingerprint),
		appName:                     derefOr(s.AppName),
		provider:                    derefOr(s.Provider),
		backendKind:                 derefOr(s.BackendKind),
		sourceKind:                  derefOr(s.SourceKind),
		sourceClass:                 derefOr(s.SourceClass),
		resourceClass:               derefOr(s.ResourceClass),
		observabilityResourceClass:  derefOr(s.ObservabilityResourceClass),
		resourceKind:                derefOr(s.ResourceKind),
		outcome:                     derefOr(s.Outcome),
		freshnessState:              derefOr(s.FreshnessState),
		warningKind:                 derefOr(s.WarningKind),
		driftCandidateReason:        derefOr(s.DriftCandidateReason),
		declaredMatchState:          derefOr(s.DeclaredMatchState),
		serviceHints:                derefOr(s.ServiceHints),
		serviceRef:                  derefOr(s.ServiceRef),
	}
}

// viewFromObservedLogSignal maps observabilityv1.ObservedLogSignal into the metadata view.
func viewFromObservedLogSignal(s observabilityv1.ObservedLogSignal) observabilityMetadataView {
	return observabilityMetadataView{
		providerObjectUID:           s.ProviderObjectUID,
		dashboardUID:                derefOr(s.DashboardUID),
		datasourceUID:               derefOr(s.DatasourceUID),
		alertRuleUID:                derefOr(s.AlertRuleUID),
		folderUID:                   derefOr(s.FolderUID),
		resourceIdentity:            derefOr(s.ResourceIdentity),
		resourceIdentityFingerprint: derefOr(s.ResourceIdentityFingerprint),
		resourceName:                derefOr(s.ResourceName),
		pipelineName:                derefOr(s.PipelineName),
		selectorIdentityFingerprint: derefOr(s.SelectorIdentityFingerprint),
		ruleGroup:                   derefOr(s.RuleGroup),
		ruleName:                    derefOr(s.RuleName),
		alertRuleNameFingerprint:    derefOr(s.AlertRuleNameFingerprint),
		recordRuleNameFingerprint:   derefOr(s.RecordRuleNameFingerprint),
		routeDestinationFingerprint: derefOr(s.RouteDestinationFingerprint),
		labelIdentityFingerprint:    derefOr(s.LabelIdentityFingerprint),
		traceTagIdentityFingerprint: derefOr(s.TraceTagIdentityFingerprint),
		tagName:                     derefOr(s.TagName),
		seriesFingerprint:           derefOr(s.SeriesFingerprint),
		appName:                     derefOr(s.AppName),
		provider:                    derefOr(s.Provider),
		backendKind:                 derefOr(s.BackendKind),
		sourceKind:                  derefOr(s.SourceKind),
		sourceClass:                 derefOr(s.SourceClass),
		resourceClass:               derefOr(s.ResourceClass),
		observabilityResourceClass:  derefOr(s.ObservabilityResourceClass),
		resourceKind:                derefOr(s.ResourceKind),
		outcome:                     derefOr(s.Outcome),
		freshnessState:              derefOr(s.FreshnessState),
		warningKind:                 derefOr(s.WarningKind),
		driftCandidateReason:        derefOr(s.DriftCandidateReason),
		declaredMatchState:          derefOr(s.DeclaredMatchState),
		serviceHints:                derefOr(s.ServiceHints),
		serviceRef:                  derefOr(s.ServiceRef),
	}
}

// viewFromObservedTraceSignal maps observabilityv1.ObservedTraceSignal into the metadata view.
func viewFromObservedTraceSignal(s observabilityv1.ObservedTraceSignal) observabilityMetadataView {
	return observabilityMetadataView{
		providerObjectUID:           s.ProviderObjectUID,
		dashboardUID:                derefOr(s.DashboardUID),
		datasourceUID:               derefOr(s.DatasourceUID),
		alertRuleUID:                derefOr(s.AlertRuleUID),
		folderUID:                   derefOr(s.FolderUID),
		resourceIdentity:            derefOr(s.ResourceIdentity),
		resourceIdentityFingerprint: derefOr(s.ResourceIdentityFingerprint),
		resourceName:                derefOr(s.ResourceName),
		pipelineName:                derefOr(s.PipelineName),
		selectorIdentityFingerprint: derefOr(s.SelectorIdentityFingerprint),
		ruleGroup:                   derefOr(s.RuleGroup),
		ruleName:                    derefOr(s.RuleName),
		alertRuleNameFingerprint:    derefOr(s.AlertRuleNameFingerprint),
		recordRuleNameFingerprint:   derefOr(s.RecordRuleNameFingerprint),
		routeDestinationFingerprint: derefOr(s.RouteDestinationFingerprint),
		labelIdentityFingerprint:    derefOr(s.LabelIdentityFingerprint),
		traceTagIdentityFingerprint: derefOr(s.TraceTagIdentityFingerprint),
		tagName:                     derefOr(s.TagName),
		seriesFingerprint:           derefOr(s.SeriesFingerprint),
		appName:                     derefOr(s.AppName),
		provider:                    derefOr(s.Provider),
		backendKind:                 derefOr(s.BackendKind),
		sourceKind:                  derefOr(s.SourceKind),
		sourceClass:                 derefOr(s.SourceClass),
		resourceClass:               derefOr(s.ResourceClass),
		observabilityResourceClass:  derefOr(s.ObservabilityResourceClass),
		resourceKind:                derefOr(s.ResourceKind),
		outcome:                     derefOr(s.Outcome),
		freshnessState:              derefOr(s.FreshnessState),
		warningKind:                 derefOr(s.WarningKind),
		driftCandidateReason:        derefOr(s.DriftCandidateReason),
		declaredMatchState:          derefOr(s.DeclaredMatchState),
		serviceHints:                derefOr(s.ServiceHints),
		serviceRef:                  derefOr(s.ServiceRef),
	}
}

// viewFromCoverageWarning maps observabilityv1.CoverageWarning into the metadata view.
func viewFromCoverageWarning(s observabilityv1.CoverageWarning) observabilityMetadataView {
	return observabilityMetadataView{
		providerObjectUID:           derefOr(s.ProviderObjectUID),
		dashboardUID:                derefOr(s.DashboardUID),
		datasourceUID:               derefOr(s.DatasourceUID),
		alertRuleUID:                derefOr(s.AlertRuleUID),
		folderUID:                   derefOr(s.FolderUID),
		resourceIdentity:            derefOr(s.ResourceIdentity),
		resourceIdentityFingerprint: derefOr(s.ResourceIdentityFingerprint),
		resourceName:                derefOr(s.ResourceName),
		pipelineName:                derefOr(s.PipelineName),
		selectorIdentityFingerprint: derefOr(s.SelectorIdentityFingerprint),
		ruleGroup:                   derefOr(s.RuleGroup),
		ruleName:                    derefOr(s.RuleName),
		alertRuleNameFingerprint:    derefOr(s.AlertRuleNameFingerprint),
		recordRuleNameFingerprint:   derefOr(s.RecordRuleNameFingerprint),
		routeDestinationFingerprint: derefOr(s.RouteDestinationFingerprint),
		labelIdentityFingerprint:    derefOr(s.LabelIdentityFingerprint),
		traceTagIdentityFingerprint: derefOr(s.TraceTagIdentityFingerprint),
		tagName:                     derefOr(s.TagName),
		seriesFingerprint:           derefOr(s.SeriesFingerprint),
		appName:                     derefOr(s.AppName),
		provider:                    derefOr(s.Provider),
		backendKind:                 derefOr(s.BackendKind),
		sourceKind:                  derefOr(s.SourceKind),
		sourceClass:                 derefOr(s.SourceClass),
		resourceClass:               derefOr(s.ResourceClass),
		observabilityResourceClass:  derefOr(s.ObservabilityResourceClass),
		resourceKind:                derefOr(s.ResourceKind),
		outcome:                     derefOr(s.Outcome),
		freshnessState:              derefOr(s.FreshnessState),
		warningKind:                 derefOr(s.WarningKind),
		driftCandidateReason:        derefOr(s.DriftCandidateReason),
		declaredMatchState:          derefOr(s.DeclaredMatchState),
		serviceHints:                derefOr(s.ServiceHints),
		serviceRef:                  derefOr(s.ServiceRef),
	}
}
