// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package reducer

import observabilityv1 "github.com/eshu-hq/eshu/sdk/go/factschema/observability/v1"

// The viewFrom<Kind> converters map one decoded typed observability struct into
// the flat observabilityMetadataView the coverage-metadata classifier reads.
// Each pointer field derefs to "" when nil, byte-identical to payloadString's
// absent-key behavior; providerObjectUID is a non-pointer (required) field on
// the four observed kinds that require it and a pointer elsewhere. This file
// holds the DECLARED and APPLIED lane converters; the observed/warning lane
// converters live in observability_coverage_metadata_view_observed.go.

// viewFromDeclaredFolder maps observabilityv1.DeclaredFolder into the metadata view.
func viewFromDeclaredFolder(s observabilityv1.DeclaredFolder) observabilityMetadataView {
	return observabilityMetadataView{
		providerObjectUID:           derefOr(s.ProviderObjectUID),
		dashboardUID:                derefOr(s.DashboardUID),
		datasourceUID:               derefOr(s.DatasourceUID),
		alertRuleUID:                derefOr(s.AlertRuleUID),
		folderUID:                   derefOr(s.FolderUID),
		resourceIdentity:            derefOr(s.ResourceIdentity),
		resourceIdentityFingerprint: derefOr(s.ResourceIdentityFingerprint),
		resourceName:                derefOr(s.ResourceName),
		pipelineName:                derefOr(s.PipelineName),
		selectorIdentityFingerprint: derefOr(s.SelectorIdentityFingerprint),
		ruleGroup:                   derefOr(s.RuleGroup),
		ruleName:                    derefOr(s.RuleName),
		alertRuleNameFingerprint:    derefOr(s.AlertRuleNameFingerprint),
		recordRuleNameFingerprint:   derefOr(s.RecordRuleNameFingerprint),
		routeDestinationFingerprint: derefOr(s.RouteDestinationFingerprint),
		labelIdentityFingerprint:    derefOr(s.LabelIdentityFingerprint),
		traceTagIdentityFingerprint: derefOr(s.TraceTagIdentityFingerprint),
		tagName:                     derefOr(s.TagName),
		seriesFingerprint:           derefOr(s.SeriesFingerprint),
		appName:                     derefOr(s.AppName),
		provider:                    derefOr(s.Provider),
		backendKind:                 derefOr(s.BackendKind),
		sourceKind:                  derefOr(s.SourceKind),
		sourceClass:                 derefOr(s.SourceClass),
		resourceClass:               derefOr(s.ResourceClass),
		observabilityResourceClass:  derefOr(s.ObservabilityResourceClass),
		resourceKind:                derefOr(s.ResourceKind),
		outcome:                     derefOr(s.Outcome),
		freshnessState:              derefOr(s.FreshnessState),
		warningKind:                 derefOr(s.WarningKind),
		driftCandidateReason:        derefOr(s.DriftCandidateReason),
		declaredMatchState:          derefOr(s.DeclaredMatchState),
		serviceHints:                derefOr(s.ServiceHints),
		serviceRef:                  derefOr(s.ServiceRef),
	}
}

// viewFromDeclaredDashboard maps observabilityv1.DeclaredDashboard into the metadata view.
func viewFromDeclaredDashboard(s observabilityv1.DeclaredDashboard) observabilityMetadataView {
	return observabilityMetadataView{
		providerObjectUID:           derefOr(s.ProviderObjectUID),
		dashboardUID:                derefOr(s.DashboardUID),
		datasourceUID:               derefOr(s.DatasourceUID),
		alertRuleUID:                derefOr(s.AlertRuleUID),
		folderUID:                   derefOr(s.FolderUID),
		resourceIdentity:            derefOr(s.ResourceIdentity),
		resourceIdentityFingerprint: derefOr(s.ResourceIdentityFingerprint),
		resourceName:                derefOr(s.ResourceName),
		pipelineName:                derefOr(s.PipelineName),
		selectorIdentityFingerprint: derefOr(s.SelectorIdentityFingerprint),
		ruleGroup:                   derefOr(s.RuleGroup),
		ruleName:                    derefOr(s.RuleName),
		alertRuleNameFingerprint:    derefOr(s.AlertRuleNameFingerprint),
		recordRuleNameFingerprint:   derefOr(s.RecordRuleNameFingerprint),
		routeDestinationFingerprint: derefOr(s.RouteDestinationFingerprint),
		labelIdentityFingerprint:    derefOr(s.LabelIdentityFingerprint),
		traceTagIdentityFingerprint: derefOr(s.TraceTagIdentityFingerprint),
		tagName:                     derefOr(s.TagName),
		seriesFingerprint:           derefOr(s.SeriesFingerprint),
		appName:                     derefOr(s.AppName),
		provider:                    derefOr(s.Provider),
		backendKind:                 derefOr(s.BackendKind),
		sourceKind:                  derefOr(s.SourceKind),
		sourceClass:                 derefOr(s.SourceClass),
		resourceClass:               derefOr(s.ResourceClass),
		observabilityResourceClass:  derefOr(s.ObservabilityResourceClass),
		resourceKind:                derefOr(s.ResourceKind),
		outcome:                     derefOr(s.Outcome),
		freshnessState:              derefOr(s.FreshnessState),
		warningKind:                 derefOr(s.WarningKind),
		driftCandidateReason:        derefOr(s.DriftCandidateReason),
		declaredMatchState:          derefOr(s.DeclaredMatchState),
		serviceHints:                derefOr(s.ServiceHints),
		serviceRef:                  derefOr(s.ServiceRef),
	}
}

// viewFromDeclaredDatasource maps observabilityv1.DeclaredDatasource into the metadata view.
func viewFromDeclaredDatasource(s observabilityv1.DeclaredDatasource) observabilityMetadataView {
	return observabilityMetadataView{
		providerObjectUID:           derefOr(s.ProviderObjectUID),
		dashboardUID:                derefOr(s.DashboardUID),
		datasourceUID:               derefOr(s.DatasourceUID),
		alertRuleUID:                derefOr(s.AlertRuleUID),
		folderUID:                   derefOr(s.FolderUID),
		resourceIdentity:            derefOr(s.ResourceIdentity),
		resourceIdentityFingerprint: derefOr(s.ResourceIdentityFingerprint),
		resourceName:                derefOr(s.ResourceName),
		pipelineName:                derefOr(s.PipelineName),
		selectorIdentityFingerprint: derefOr(s.SelectorIdentityFingerprint),
		ruleGroup:                   derefOr(s.RuleGroup),
		ruleName:                    derefOr(s.RuleName),
		alertRuleNameFingerprint:    derefOr(s.AlertRuleNameFingerprint),
		recordRuleNameFingerprint:   derefOr(s.RecordRuleNameFingerprint),
		routeDestinationFingerprint: derefOr(s.RouteDestinationFingerprint),
		labelIdentityFingerprint:    derefOr(s.LabelIdentityFingerprint),
		traceTagIdentityFingerprint: derefOr(s.TraceTagIdentityFingerprint),
		tagName:                     derefOr(s.TagName),
		seriesFingerprint:           derefOr(s.SeriesFingerprint),
		appName:                     derefOr(s.AppName),
		provider:                    derefOr(s.Provider),
		backendKind:                 derefOr(s.BackendKind),
		sourceKind:                  derefOr(s.SourceKind),
		sourceClass:                 derefOr(s.SourceClass),
		resourceClass:               derefOr(s.ResourceClass),
		observabilityResourceClass:  derefOr(s.ObservabilityResourceClass),
		resourceKind:                derefOr(s.ResourceKind),
		outcome:                     derefOr(s.Outcome),
		freshnessState:              derefOr(s.FreshnessState),
		warningKind:                 derefOr(s.WarningKind),
		driftCandidateReason:        derefOr(s.DriftCandidateReason),
		declaredMatchState:          derefOr(s.DeclaredMatchState),
		serviceHints:                derefOr(s.ServiceHints),
		serviceRef:                  derefOr(s.ServiceRef),
	}
}

// viewFromDeclaredAlertRule maps observabilityv1.DeclaredAlertRule into the metadata view.
func viewFromDeclaredAlertRule(s observabilityv1.DeclaredAlertRule) observabilityMetadataView {
	return observabilityMetadataView{
		providerObjectUID:           derefOr(s.ProviderObjectUID),
		dashboardUID:                derefOr(s.DashboardUID),
		datasourceUID:               derefOr(s.DatasourceUID),
		alertRuleUID:                derefOr(s.AlertRuleUID),
		folderUID:                   derefOr(s.FolderUID),
		resourceIdentity:            derefOr(s.ResourceIdentity),
		resourceIdentityFingerprint: derefOr(s.ResourceIdentityFingerprint),
		resourceName:                derefOr(s.ResourceName),
		pipelineName:                derefOr(s.PipelineName),
		selectorIdentityFingerprint: derefOr(s.SelectorIdentityFingerprint),
		ruleGroup:                   derefOr(s.RuleGroup),
		ruleName:                    derefOr(s.RuleName),
		alertRuleNameFingerprint:    derefOr(s.AlertRuleNameFingerprint),
		recordRuleNameFingerprint:   derefOr(s.RecordRuleNameFingerprint),
		routeDestinationFingerprint: derefOr(s.RouteDestinationFingerprint),
		labelIdentityFingerprint:    derefOr(s.LabelIdentityFingerprint),
		traceTagIdentityFingerprint: derefOr(s.TraceTagIdentityFingerprint),
		tagName:                     derefOr(s.TagName),
		seriesFingerprint:           derefOr(s.SeriesFingerprint),
		appName:                     derefOr(s.AppName),
		provider:                    derefOr(s.Provider),
		backendKind:                 derefOr(s.BackendKind),
		sourceKind:                  derefOr(s.SourceKind),
		sourceClass:                 derefOr(s.SourceClass),
		resourceClass:               derefOr(s.ResourceClass),
		observabilityResourceClass:  derefOr(s.ObservabilityResourceClass),
		resourceKind:                derefOr(s.ResourceKind),
		outcome:                     derefOr(s.Outcome),
		freshnessState:              derefOr(s.FreshnessState),
		warningKind:                 derefOr(s.WarningKind),
		driftCandidateReason:        derefOr(s.DriftCandidateReason),
		declaredMatchState:          derefOr(s.DeclaredMatchState),
		serviceHints:                derefOr(s.ServiceHints),
		serviceRef:                  derefOr(s.ServiceRef),
	}
}

// viewFromDeclaredScrapeConfig maps observabilityv1.DeclaredScrapeConfig into the metadata view.
func viewFromDeclaredScrapeConfig(s observabilityv1.DeclaredScrapeConfig) observabilityMetadataView {
	return observabilityMetadataView{
		providerObjectUID:           derefOr(s.ProviderObjectUID),
		dashboardUID:                derefOr(s.DashboardUID),
		datasourceUID:               derefOr(s.DatasourceUID),
		alertRuleUID:                derefOr(s.AlertRuleUID),
		folderUID:                   derefOr(s.FolderUID),
		resourceIdentity:            derefOr(s.ResourceIdentity),
		resourceIdentityFingerprint: derefOr(s.ResourceIdentityFingerprint),
		resourceName:                derefOr(s.ResourceName),
		pipelineName:                derefOr(s.PipelineName),
		selectorIdentityFingerprint: derefOr(s.SelectorIdentityFingerprint),
		ruleGroup:                   derefOr(s.RuleGroup),
		ruleName:                    derefOr(s.RuleName),
		alertRuleNameFingerprint:    derefOr(s.AlertRuleNameFingerprint),
		recordRuleNameFingerprint:   derefOr(s.RecordRuleNameFingerprint),
		routeDestinationFingerprint: derefOr(s.RouteDestinationFingerprint),
		labelIdentityFingerprint:    derefOr(s.LabelIdentityFingerprint),
		traceTagIdentityFingerprint: derefOr(s.TraceTagIdentityFingerprint),
		tagName:                     derefOr(s.TagName),
		seriesFingerprint:           derefOr(s.SeriesFingerprint),
		appName:                     derefOr(s.AppName),
		provider:                    derefOr(s.Provider),
		backendKind:                 derefOr(s.BackendKind),
		sourceKind:                  derefOr(s.SourceKind),
		sourceClass:                 derefOr(s.SourceClass),
		resourceClass:               derefOr(s.ResourceClass),
		observabilityResourceClass:  derefOr(s.ObservabilityResourceClass),
		resourceKind:                derefOr(s.ResourceKind),
		outcome:                     derefOr(s.Outcome),
		freshnessState:              derefOr(s.FreshnessState),
		warningKind:                 derefOr(s.WarningKind),
		driftCandidateReason:        derefOr(s.DriftCandidateReason),
		declaredMatchState:          derefOr(s.DeclaredMatchState),
		serviceHints:                derefOr(s.ServiceHints),
		serviceRef:                  derefOr(s.ServiceRef),
	}
}

// viewFromDeclaredMetricRule maps observabilityv1.DeclaredMetricRule into the metadata view.
func viewFromDeclaredMetricRule(s observabilityv1.DeclaredMetricRule) observabilityMetadataView {
	return observabilityMetadataView{
		providerObjectUID:           derefOr(s.ProviderObjectUID),
		dashboardUID:                derefOr(s.DashboardUID),
		datasourceUID:               derefOr(s.DatasourceUID),
		alertRuleUID:                derefOr(s.AlertRuleUID),
		folderUID:                   derefOr(s.FolderUID),
		resourceIdentity:            derefOr(s.ResourceIdentity),
		resourceIdentityFingerprint: derefOr(s.ResourceIdentityFingerprint),
		resourceName:                derefOr(s.ResourceName),
		pipelineName:                derefOr(s.PipelineName),
		selectorIdentityFingerprint: derefOr(s.SelectorIdentityFingerprint),
		ruleGroup:                   derefOr(s.RuleGroup),
		ruleName:                    derefOr(s.RuleName),
		alertRuleNameFingerprint:    derefOr(s.AlertRuleNameFingerprint),
		recordRuleNameFingerprint:   derefOr(s.RecordRuleNameFingerprint),
		routeDestinationFingerprint: derefOr(s.RouteDestinationFingerprint),
		labelIdentityFingerprint:    derefOr(s.LabelIdentityFingerprint),
		traceTagIdentityFingerprint: derefOr(s.TraceTagIdentityFingerprint),
		tagName:                     derefOr(s.TagName),
		seriesFingerprint:           derefOr(s.SeriesFingerprint),
		appName:                     derefOr(s.AppName),
		provider:                    derefOr(s.Provider),
		backendKind:                 derefOr(s.BackendKind),
		sourceKind:                  derefOr(s.SourceKind),
		sourceClass:                 derefOr(s.SourceClass),
		resourceClass:               derefOr(s.ResourceClass),
		observabilityResourceClass:  derefOr(s.ObservabilityResourceClass),
		resourceKind:                derefOr(s.ResourceKind),
		outcome:                     derefOr(s.Outcome),
		freshnessState:              derefOr(s.FreshnessState),
		warningKind:                 derefOr(s.WarningKind),
		driftCandidateReason:        derefOr(s.DriftCandidateReason),
		declaredMatchState:          derefOr(s.DeclaredMatchState),
		serviceHints:                derefOr(s.ServiceHints),
		serviceRef:                  derefOr(s.ServiceRef),
	}
}

// viewFromDeclaredMetricRoute maps observabilityv1.DeclaredMetricRoute into the metadata view.
func viewFromDeclaredMetricRoute(s observabilityv1.DeclaredMetricRoute) observabilityMetadataView {
	return observabilityMetadataView{
		providerObjectUID:           derefOr(s.ProviderObjectUID),
		dashboardUID:                derefOr(s.DashboardUID),
		datasourceUID:               derefOr(s.DatasourceUID),
		alertRuleUID:                derefOr(s.AlertRuleUID),
		folderUID:                   derefOr(s.FolderUID),
		resourceIdentity:            derefOr(s.ResourceIdentity),
		resourceIdentityFingerprint: derefOr(s.ResourceIdentityFingerprint),
		resourceName:                derefOr(s.ResourceName),
		pipelineName:                derefOr(s.PipelineName),
		selectorIdentityFingerprint: derefOr(s.SelectorIdentityFingerprint),
		ruleGroup:                   derefOr(s.RuleGroup),
		ruleName:                    derefOr(s.RuleName),
		alertRuleNameFingerprint:    derefOr(s.AlertRuleNameFingerprint),
		recordRuleNameFingerprint:   derefOr(s.RecordRuleNameFingerprint),
		routeDestinationFingerprint: derefOr(s.RouteDestinationFingerprint),
		labelIdentityFingerprint:    derefOr(s.LabelIdentityFingerprint),
		traceTagIdentityFingerprint: derefOr(s.TraceTagIdentityFingerprint),
		tagName:                     derefOr(s.TagName),
		seriesFingerprint:           derefOr(s.SeriesFingerprint),
		appName:                     derefOr(s.AppName),
		provider:                    derefOr(s.Provider),
		backendKind:                 derefOr(s.BackendKind),
		sourceKind:                  derefOr(s.SourceKind),
		sourceClass:                 derefOr(s.SourceClass),
		resourceClass:               derefOr(s.ResourceClass),
		observabilityResourceClass:  derefOr(s.ObservabilityResourceClass),
		resourceKind:                derefOr(s.ResourceKind),
		outcome:                     derefOr(s.Outcome),
		freshnessState:              derefOr(s.FreshnessState),
		warningKind:                 derefOr(s.WarningKind),
		driftCandidateReason:        derefOr(s.DriftCandidateReason),
		declaredMatchState:          derefOr(s.DeclaredMatchState),
		serviceHints:                derefOr(s.ServiceHints),
		serviceRef:                  derefOr(s.ServiceRef),
	}
}

// viewFromDeclaredLogRoute maps observabilityv1.DeclaredLogRoute into the metadata view.
func viewFromDeclaredLogRoute(s observabilityv1.DeclaredLogRoute) observabilityMetadataView {
	return observabilityMetadataView{
		providerObjectUID:           derefOr(s.ProviderObjectUID),
		dashboardUID:                derefOr(s.DashboardUID),
		datasourceUID:               derefOr(s.DatasourceUID),
		alertRuleUID:                derefOr(s.AlertRuleUID),
		folderUID:                   derefOr(s.FolderUID),
		resourceIdentity:            derefOr(s.ResourceIdentity),
		resourceIdentityFingerprint: derefOr(s.ResourceIdentityFingerprint),
		resourceName:                derefOr(s.ResourceName),
		pipelineName:                derefOr(s.PipelineName),
		selectorIdentityFingerprint: derefOr(s.SelectorIdentityFingerprint),
		ruleGroup:                   derefOr(s.RuleGroup),
		ruleName:                    derefOr(s.RuleName),
		alertRuleNameFingerprint:    derefOr(s.AlertRuleNameFingerprint),
		recordRuleNameFingerprint:   derefOr(s.RecordRuleNameFingerprint),
		routeDestinationFingerprint: derefOr(s.RouteDestinationFingerprint),
		labelIdentityFingerprint:    derefOr(s.LabelIdentityFingerprint),
		traceTagIdentityFingerprint: derefOr(s.TraceTagIdentityFingerprint),
		tagName:                     derefOr(s.TagName),
		seriesFingerprint:           derefOr(s.SeriesFingerprint),
		appName:                     derefOr(s.AppName),
		provider:                    derefOr(s.Provider),
		backendKind:                 derefOr(s.BackendKind),
		sourceKind:                  derefOr(s.SourceKind),
		sourceClass:                 derefOr(s.SourceClass),
		resourceClass:               derefOr(s.ResourceClass),
		observabilityResourceClass:  derefOr(s.ObservabilityResourceClass),
		resourceKind:                derefOr(s.ResourceKind),
		outcome:                     derefOr(s.Outcome),
		freshnessState:              derefOr(s.FreshnessState),
		warningKind:                 derefOr(s.WarningKind),
		driftCandidateReason:        derefOr(s.DriftCandidateReason),
		declaredMatchState:          derefOr(s.DeclaredMatchState),
		serviceHints:                derefOr(s.ServiceHints),
		serviceRef:                  derefOr(s.ServiceRef),
	}
}

// viewFromDeclaredTraceRoute maps observabilityv1.DeclaredTraceRoute into the metadata view.
func viewFromDeclaredTraceRoute(s observabilityv1.DeclaredTraceRoute) observabilityMetadataView {
	return observabilityMetadataView{
		providerObjectUID:           derefOr(s.ProviderObjectUID),
		dashboardUID:                derefOr(s.DashboardUID),
		datasourceUID:               derefOr(s.DatasourceUID),
		alertRuleUID:                derefOr(s.AlertRuleUID),
		folderUID:                   derefOr(s.FolderUID),
		resourceIdentity:            derefOr(s.ResourceIdentity),
		resourceIdentityFingerprint: derefOr(s.ResourceIdentityFingerprint),
		resourceName:                derefOr(s.ResourceName),
		pipelineName:                derefOr(s.PipelineName),
		selectorIdentityFingerprint: derefOr(s.SelectorIdentityFingerprint),
		ruleGroup:                   derefOr(s.RuleGroup),
		ruleName:                    derefOr(s.RuleName),
		alertRuleNameFingerprint:    derefOr(s.AlertRuleNameFingerprint),
		recordRuleNameFingerprint:   derefOr(s.RecordRuleNameFingerprint),
		routeDestinationFingerprint: derefOr(s.RouteDestinationFingerprint),
		labelIdentityFingerprint:    derefOr(s.LabelIdentityFingerprint),
		traceTagIdentityFingerprint: derefOr(s.TraceTagIdentityFingerprint),
		tagName:                     derefOr(s.TagName),
		seriesFingerprint:           derefOr(s.SeriesFingerprint),
		appName:                     derefOr(s.AppName),
		provider:                    derefOr(s.Provider),
		backendKind:                 derefOr(s.BackendKind),
		sourceKind:                  derefOr(s.SourceKind),
		sourceClass:                 derefOr(s.SourceClass),
		resourceClass:               derefOr(s.ResourceClass),
		observabilityResourceClass:  derefOr(s.ObservabilityResourceClass),
		resourceKind:                derefOr(s.ResourceKind),
		outcome:                     derefOr(s.Outcome),
		freshnessState:              derefOr(s.FreshnessState),
		warningKind:                 derefOr(s.WarningKind),
		driftCandidateReason:        derefOr(s.DriftCandidateReason),
		declaredMatchState:          derefOr(s.DeclaredMatchState),
		serviceHints:                derefOr(s.ServiceHints),
		serviceRef:                  derefOr(s.ServiceRef),
	}
}

// viewFromAppliedResource maps observabilityv1.AppliedResource into the metadata view.
func viewFromAppliedResource(s observabilityv1.AppliedResource) observabilityMetadataView {
	return observabilityMetadataView{
		providerObjectUID:           derefOr(s.ProviderObjectUID),
		dashboardUID:                derefOr(s.DashboardUID),
		datasourceUID:               derefOr(s.DatasourceUID),
		alertRuleUID:                derefOr(s.AlertRuleUID),
		folderUID:                   derefOr(s.FolderUID),
		resourceIdentity:            derefOr(s.ResourceIdentity),
		resourceIdentityFingerprint: derefOr(s.ResourceIdentityFingerprint),
		resourceName:                derefOr(s.ResourceName),
		pipelineName:                derefOr(s.PipelineName),
		selectorIdentityFingerprint: derefOr(s.SelectorIdentityFingerprint),
		ruleGroup:                   derefOr(s.RuleGroup),
		ruleName:                    derefOr(s.RuleName),
		alertRuleNameFingerprint:    derefOr(s.AlertRuleNameFingerprint),
		recordRuleNameFingerprint:   derefOr(s.RecordRuleNameFingerprint),
		routeDestinationFingerprint: derefOr(s.RouteDestinationFingerprint),
		labelIdentityFingerprint:    derefOr(s.LabelIdentityFingerprint),
		traceTagIdentityFingerprint: derefOr(s.TraceTagIdentityFingerprint),
		tagName:                     derefOr(s.TagName),
		seriesFingerprint:           derefOr(s.SeriesFingerprint),
		appName:                     derefOr(s.AppName),
		provider:                    derefOr(s.Provider),
		backendKind:                 derefOr(s.BackendKind),
		sourceKind:                  derefOr(s.SourceKind),
		sourceClass:                 derefOr(s.SourceClass),
		resourceClass:               derefOr(s.ResourceClass),
		observabilityResourceClass:  derefOr(s.ObservabilityResourceClass),
		resourceKind:                derefOr(s.ResourceKind),
		outcome:                     derefOr(s.Outcome),
		freshnessState:              derefOr(s.FreshnessState),
		warningKind:                 derefOr(s.WarningKind),
		driftCandidateReason:        derefOr(s.DriftCandidateReason),
		declaredMatchState:          derefOr(s.DeclaredMatchState),
		serviceHints:                derefOr(s.ServiceHints),
		serviceRef:                  derefOr(s.ServiceRef),
	}
}

// viewFromAppliedSyncState maps observabilityv1.AppliedSyncState into the metadata view.
func viewFromAppliedSyncState(s observabilityv1.AppliedSyncState) observabilityMetadataView {
	return observabilityMetadataView{
		providerObjectUID:           derefOr(s.ProviderObjectUID),
		dashboardUID:                derefOr(s.DashboardUID),
		datasourceUID:               derefOr(s.DatasourceUID),
		alertRuleUID:                derefOr(s.AlertRuleUID),
		folderUID:                   derefOr(s.FolderUID),
		resourceIdentity:            derefOr(s.ResourceIdentity),
		resourceIdentityFingerprint: derefOr(s.ResourceIdentityFingerprint),
		resourceName:                derefOr(s.ResourceName),
		pipelineName:                derefOr(s.PipelineName),
		selectorIdentityFingerprint: derefOr(s.SelectorIdentityFingerprint),
		ruleGroup:                   derefOr(s.RuleGroup),
		ruleName:                    derefOr(s.RuleName),
		alertRuleNameFingerprint:    derefOr(s.AlertRuleNameFingerprint),
		recordRuleNameFingerprint:   derefOr(s.RecordRuleNameFingerprint),
		routeDestinationFingerprint: derefOr(s.RouteDestinationFingerprint),
		labelIdentityFingerprint:    derefOr(s.LabelIdentityFingerprint),
		traceTagIdentityFingerprint: derefOr(s.TraceTagIdentityFingerprint),
		tagName:                     derefOr(s.TagName),
		seriesFingerprint:           derefOr(s.SeriesFingerprint),
		appName:                     derefOr(s.AppName),
		provider:                    derefOr(s.Provider),
		backendKind:                 derefOr(s.BackendKind),
		sourceKind:                  derefOr(s.SourceKind),
		sourceClass:                 derefOr(s.SourceClass),
		resourceClass:               derefOr(s.ResourceClass),
		observabilityResourceClass:  derefOr(s.ObservabilityResourceClass),
		resourceKind:                derefOr(s.ResourceKind),
		outcome:                     derefOr(s.Outcome),
		freshnessState:              derefOr(s.FreshnessState),
		warningKind:                 derefOr(s.WarningKind),
		driftCandidateReason:        derefOr(s.DriftCandidateReason),
		declaredMatchState:          derefOr(s.DeclaredMatchState),
		serviceHints:                derefOr(s.ServiceHints),
		serviceRef:                  derefOr(s.ServiceRef),
	}
}
