// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package telemetry

import "slices"

var metricDimensionKeys = []string{
	MetricDimensionScopeKind,
	MetricDimensionSource,
	MetricDimensionLanguage,
	MetricDimensionSourceSystem,
	MetricDimensionCollectorKind,
	MetricDimensionDomain,
	MetricDimensionPartitionKey,
	MetricDimensionPartitionID,
	MetricDimensionRunner,
	MetricDimensionLookupResult,
	MetricDimensionErrorType,
	MetricDimensionRepoSizeTier,
	MetricDimensionSkipReason,
	MetricDimensionNodeType,
	MetricDimensionEdgeType,
	MetricDimensionWritePhase,
	MetricDimensionOutcome,
	MetricDimensionGuardrail,
	MetricDimensionPolicyID,
	MetricDimensionEvidenceClass,
	MetricDimensionBackendKind,
	MetricDimensionConfidence,
	MetricDimensionRiskType,
	MetricDimensionSeverity,
	MetricDimensionResult,
	MetricDimensionReason,
	MetricDimensionKind,
	MetricDimensionAction,
	MetricDimensionMCPMethod,
	MetricDimensionAuthPath,
	MetricDimensionProvider,
	MetricDimensionEventKind,
	MetricDimensionDecision,
	MetricDimensionStatus,
	MetricDimensionOperation,
	MetricDimensionGate,
	MetricDimensionStatusClass,
	MetricDimensionRoute,
	MetricDimensionFailureClass,
	MetricDimensionFactKind,
	MetricDimensionResourceScope,
	MetricDimensionDocumentType,
	MetricDimensionService,
	MetricDimensionAccount,
	MetricDimensionRegion,
	MetricDimensionMediaFamily,
	MetricDimensionArtifactFamily,
	MetricDimensionSafeLocatorHash,
	MetricDimensionWarningKind,
	MetricDimensionPack,
	MetricDimensionRule,
	MetricDimensionDriftKind,
	MetricDimensionResourceType,
	MetricDimensionRelationshipType,
	MetricDimensionJoinMode,
	MetricDimensionOwnershipFamily,
	MetricDimensionCoverageSignal,
	MetricDimensionResolutionMode,
	MetricDimensionEndpointKind,
	MetricDimensionPrincipalKind,
	MetricDimensionNodeLabel,
	MetricDimensionAgeBucket,
	MetricDimensionEcosystem,
	MetricDimensionCloudFormationSection,
}

var spanNames = []string{
	SpanCollectorObserve,
	SpanCollectorStream,
	SpanScopeAssign,
	SpanFactEmit,
	SpanProjectorRun,
	SpanReducerIntentEnqueue,
	SpanReducerRun,
	SpanReducerBatchClaim,
	SpanReducerEshuSearchIndexWrite,
	SpanReducerDriftEvidenceLoad,
	SpanReducerAWSRuntimeDriftEvidenceLoad,
	SpanReducerMultiCloudRuntimeDriftEvidenceLoad,
	SpanReducerAWSRelationshipMaterialization,
	SpanReducerGCPRelationshipMaterialization,
	SpanReducerAzureRelationshipMaterialization,
	SpanReducerObservabilityCoverageMaterialization,
	SpanReducerSecurityGroupReachabilityMaterialization,
	SpanReducerIAMCanAssumeMaterialization,
	SpanReducerS3LogsToMaterialization,
	SpanReducerRDSPostureMaterialization,
	SpanReducerEC2UsesProfileMaterialization,
	SpanReducerIAMInstanceProfileRoleMaterialization,
	SpanReducerEC2InternetExposureMaterialization,
	SpanReducerEC2BlockDeviceKMSPostureMaterialization,
	SpanReducerS3InternetExposureMaterialization,
	SpanReducerIAMEscalationMaterialization,
	SpanReducerIAMCanPerformMaterialization,
	SpanReducerSecretsIAMGraphProjection,
	SpanCanonicalWrite,
	SpanCanonicalProjection,
	SpanCanonicalRetract,
	SpanEvidenceDiscovery,
	SpanIaCReachabilityMaterialization,
	SpanSQLRelationshipMaterialization,
	SpanInheritanceMaterialization,
	SpanCrossRepoResolution,
	SpanCodeImportRepoEdge,
	SpanSharedAcceptanceLookup,
	SpanSharedAcceptanceUpsert,
	SpanQueryRelationshipEvidence,
	SpanQueryEvidenceCitationPacket,
	SpanQueryDocumentationFindings,
	SpanQueryDocumentationFacts,
	SpanQueryDocumentationEvidencePacket,
	SpanQueryDocumentationPacketFreshness,
	SpanQuerySemanticEvidence,
	SpanQuerySemanticSearch,
	SpanQueryDocumentationAggregate,
	SpanQueryDeadIaC,
	SpanQueryIaCUnmanagedResources,
	SpanQueryIaCManagementStatus,
	SpanQueryIaCManagementExplanation,
	SpanQueryIaCTerraformImportPlan,
	SpanQueryAWSRuntimeDriftFindings,
	SpanQueryReplatformingSelectors,
	SpanQueryReplatformingPlan,
	SpanQueryIaCResources,
	SpanQueryInfraResourceSearch,
	SpanQueryInfraRelationships,
	SpanQueryInfraResourceAggregate,
	SpanQueryCloudResourceList,
	SpanQueryCloudInventoryReadback,
	SpanQueryCloudRuntimeDriftFindings,
	SpanQueryCodeTopicInvestigation,
	SpanQueryHardcodedSecretInvestigation,
	SpanQueryDeadCodeInvestigation,
	SpanQueryCallGraphMetrics,
	SpanQueryGraphSummaryPacket,
	SpanQueryChangeSurfaceInvestigation,
	SpanQueryResourceInvestigation,
	SpanQueryPackageRegistryPackages,
	SpanQueryPackageRegistryVersions,
	SpanQueryPackageRegistryDependencies,
	SpanQueryDependencies,
	SpanQueryCodeownersOwnership,
	SpanTerraformStateClaimProcess,
	SpanTerraformStateDiscoveryResolve,
	SpanTerraformStateSourceOpen,
	SpanTerraformStateParserStream,
	SpanTerraformStateFactEmitBatch,
	SpanTerraformStateCoordinatorDone,
	SpanWebhookHandle,
	SpanWebhookStore,
	SpanOCIRegistryScan,
	SpanOCIRegistryAPICall,
	SpanKubernetesLiveSnapshot,
	SpanKubernetesLiveAPICall,
	SpanVaultLiveSnapshot,
	SpanAWSCollectorClaimProcess,
	SpanAWSCredentialsAssumeRole,
	SpanAWSServiceScan,
	SpanAWSServicePaginationPage,
	SpanPostgresExec,
	SpanPostgresQuery,
	SpanNeo4jExecute,
}

var logKeys = []string{
	LogKeyScopeID,
	LogKeyScopeKind,
	LogKeySourceSystem,
	LogKeyGenerationID,
	LogKeyCollectorKind,
	LogKeyDomain,
	LogKeyPartitionKey,
	LogKeyRequestID,
	LogKeyFailureClass,
	LogKeyRefreshSkipped,
	LogKeyPipelinePhase,
	LogKeyAcceptanceScopeID,
	LogKeyAcceptanceUnitID,
	LogKeyAcceptanceSourceRunID,
	LogKeyAcceptanceGenerationID,
	LogKeyAcceptanceStaleCount,
	LogKeyResourceFingerprint,
	LogKeyResourceIdentityKind,
	LogKeyResourceType,
	LogKeyDriftPriorConfigDepth,
	LogKeyDriftPriorConfigAddresses,
	LogKeyDriftStateOnlyAddresses,
	LogKeyDriftAddressesPromoted,
	LogKeyDriftMultiElementPrefix,
	LogKeyDriftMultiElementCount,
	LogKeyDriftMultiElementSource,
	LogKeyDriftCompositeResourceType,
	LogKeyDriftCompositeAttributeKey,
	LogKeyDriftCompositePath,
	LogKeyDriftCompositeError,
}

// MetricDimensionKeys returns the frozen ordered metric dimensions.
func MetricDimensionKeys() []string {
	return slices.Clone(metricDimensionKeys)
}

// SpanNames returns the frozen ordered span names.
func SpanNames() []string {
	return slices.Clone(spanNames)
}

// LogKeys returns the frozen ordered structured log keys.
func LogKeys() []string {
	return slices.Clone(logKeys)
}
