// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package main

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/eshu-hq/eshu/go/internal/collector/scannerworker"
	"github.com/eshu-hq/eshu/go/internal/collector/scannerworker/sbomgenerator"
	"github.com/eshu-hq/eshu/go/internal/facts"
	"github.com/eshu-hq/eshu/go/internal/scope"
	"github.com/eshu-hq/eshu/go/internal/workflow"
)

func TestBuildAnalyzerUsesConfiguredSBOMGenerationSource(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, "package-lock.json"), `{
		"lockfileVersion": 3,
		"packages": {
			"": {"name": "test-app", "version": "1.0.0"},
			"node_modules/left-pad": {"version": "1.3.0"}
		}
	}`)
	writeTestFile(t, filepath.Join(root, "go.mod"), `module example.test/app

require github.com/gin-gonic/gin v1.9.1
`)

	config := runtimeConfig{
		Instance: workflow.DesiredCollectorInstance{
			InstanceID: "scanner-worker-sbom",
		},
		Analyzer: scannerworker.AnalyzerSBOMGeneration,
		SBOMTargets: []sbomTargetConfig{{
			ScopeID:       "scanner-worker://repository/repo-private-name",
			RootPath:      root,
			SubjectDigest: "sha256:1111111111111111111111111111111111111111111111111111111111111111",
		}},
	}
	analyzer, err := buildAnalyzer(config)
	if err != nil {
		t.Fatalf("buildAnalyzer(sbom_generation) error = %v, want nil", err)
	}

	result, err := analyzer.Analyze(context.Background(), testSBOMClaimInput(t))
	if err != nil {
		t.Fatalf("Analyze() error = %v, want nil", err)
	}
	counts := countFactKinds(result.Output.Facts)
	if got, want := counts[facts.SBOMDocumentFactKind], 1; got != want {
		t.Fatalf("document facts = %d, want %d", got, want)
	}
	if got, want := counts[facts.SBOMComponentFactKind], 2; got != want {
		t.Fatalf("component facts = %d, want %d", got, want)
	}
	if counts[facts.ScannerWorkerWarningFactKind] != 0 {
		t.Fatalf("scanner-worker warning facts = %d, want 0 for configured source", counts[facts.ScannerWorkerWarningFactKind])
	}
	if result.Usage.PeakMemoryBytes == 0 {
		t.Fatal("PeakMemoryBytes = 0, want measured input bytes")
	}
}

func TestRepositorySBOMSourceParsesCargoAndComposerLockfiles(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, "Cargo.lock"), `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "service"
version = "0.1.0"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.197"
source = "registry+https://github.com/rust-lang/crates.io-index"
`)
	writeTestFile(t, filepath.Join(root, "composer.lock"), `{
		"packages": [
			{"name": "symfony/console", "version": "v7.0.0"}
		],
		"packages-dev": [
			{"name": "phpunit/phpunit", "version": "10.5.0"}
		]
	}`)
	source, err := newRepositorySBOMSource([]sbomTargetConfig{{
		ScopeID:  "scanner-worker://repository/repo-private-name",
		RootPath: root,
	}})
	if err != nil {
		t.Fatalf("newRepositorySBOMSource() error = %v, want nil", err)
	}

	inventory, err := source.Collect(context.Background(), testSBOMClaimInput(t))
	if err != nil {
		t.Fatalf("Collect() error = %v, want nil", err)
	}
	components := componentsByName(inventory.Components)
	assertComponentEvidence(t, components["serde"], "cargo", "Cargo.lock", "", "direct", "pkg:cargo/serde@1.0.197")
	assertComponentEvidence(t, components["symfony/console"], "composer", "composer.lock", "packages", "runtime", "pkg:composer/symfony/console@v7.0.0")
	assertComponentEvidence(t, components["phpunit/phpunit"], "composer", "composer.lock", "packages-dev", "development", "pkg:composer/phpunit/phpunit@10.5.0")
}

func TestRepositorySBOMSourceParsesPythonRubyAndGradleLockfiles(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, "Pipfile.lock"), `{
		"default": {
			"requests": {"version": "==2.31.0"},
			"local-tool": {"path": "../local-tool"}
		},
		"develop": {
			"pytest": {"version": "==8.2.0"}
		}
	}`)
	writeTestFile(t, filepath.Join(root, "poetry.lock"), `
[[package]]
name = "django"
version = "5.0.6"
category = "main"

[[package]]
name = "ruff"
version = "0.4.8"
category = "dev"

[[package]]
name = "internal-lib"
version = "1.2.3"

[package.source]
type = "git"
url = "https://example.invalid/internal-lib.git"
`)
	writeTestFile(t, filepath.Join(root, "Gemfile.lock"), `GEM
  remote: https://rubygems.org/
  specs:
    actionpack (7.1.3)
      rack
    rack (3.0.9)

DEPENDENCIES
  actionpack
`)
	writeTestFile(t, filepath.Join(root, "gradle.lockfile"), `# This is a Gradle dependency lockfile.
org.springframework:spring-core:6.1.2=compileClasspath,runtimeClasspath
empty=empty
`)
	source, err := newRepositorySBOMSource([]sbomTargetConfig{{
		ScopeID:  "scanner-worker://repository/repo-private-name",
		RootPath: root,
	}})
	if err != nil {
		t.Fatalf("newRepositorySBOMSource() error = %v, want nil", err)
	}

	inventory, err := source.Collect(context.Background(), testSBOMClaimInput(t))
	if err != nil {
		t.Fatalf("Collect() error = %v, want nil", err)
	}
	components := componentsByName(inventory.Components)
	assertComponentEvidence(t, components["requests"], "pypi", "Pipfile.lock", "default", "runtime", "pkg:pypi/requests@2.31.0")
	assertComponentEvidence(t, components["pytest"], "pypi", "Pipfile.lock", "develop", "development", "pkg:pypi/pytest@8.2.0")
	assertComponentEvidence(t, components["django"], "pypi", "poetry.lock", "main", "runtime", "pkg:pypi/django@5.0.6")
	assertComponentEvidence(t, components["ruff"], "pypi", "poetry.lock", "dev", "development", "pkg:pypi/ruff@0.4.8")
	if _, ok := components["internal-lib"]; ok {
		t.Fatal("poetry git source component was emitted, want only registry lockfile proof")
	}
	assertComponentEvidence(t, components["actionpack"], "rubygems", "Gemfile.lock", "DEPENDENCIES", "direct", "pkg:gem/actionpack@7.1.3")
	assertComponentEvidence(t, components["rack"], "rubygems", "Gemfile.lock", "GEM", "transitive", "pkg:gem/rack@3.0.9")
	assertComponentEvidence(t, components["org.springframework:spring-core"], "maven", "gradle.lockfile", "compileClasspath,runtimeClasspath", "resolved", "pkg:maven/org.springframework/spring-core@6.1.2")
}

func TestRepositorySBOMSourceParsesNPMPackageDependencyRanges(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, "package-lock.json"), `{
		"lockfileVersion": 3,
		"packages": {
			"": {
				"name": "test-app",
				"version": "1.0.0",
				"dependencies": {
					"@hapi/wreck": "^18.0.0",
					"range-only": "^1.0.0"
				}
			},
			"node_modules/@hapi/wreck": {
				"version": "18.0.0",
				"dependencies": {
					"@hapi/boom": "^10.0.1",
					"hoek": "9.x"
				}
			},
			"node_modules/@hapi/boom": {
				"version": "10.0.1"
			},
			"node_modules/hoek": {
				"version": "9.3.0",
				"optional": true
			}
		}
	}`)
	nestedDir := filepath.Join(root, "subdir")
	if err := os.MkdirAll(nestedDir, 0o700); err != nil {
		t.Fatalf("MkdirAll(%s) error = %v", nestedDir, err)
	}
	writeTestFile(t, filepath.Join(nestedDir, "package-lock.json"), `{
		"lockfileVersion": 3,
		"packages": {
			"": {
				"name": "nested-app",
				"version": "1.0.0",
				"dependencies": {
					"nested-exact": "^2.0.0",
					"nested-range-only": "^3.0.0"
				}
			},
			"node_modules/nested-exact": {
				"version": "2.0.1",
				"dependencies": {
					"nested-transitive": "~4.0.0"
				}
			},
			"node_modules/nested-transitive": {
				"version": "4.0.2"
			}
		}
	}`)
	source, err := newRepositorySBOMSource([]sbomTargetConfig{{
		ScopeID:  "scanner-worker://repository/repo-private-name",
		RootPath: root,
	}})
	if err != nil {
		t.Fatalf("newRepositorySBOMSource() error = %v, want nil", err)
	}

	inventory, err := source.Collect(context.Background(), testSBOMClaimInput(t))
	if err != nil {
		t.Fatalf("Collect() error = %v, want nil", err)
	}
	if len(inventory.Warnings) != 0 {
		t.Fatalf("Warnings len = %d, want 0 for npm package dependency ranges: %#v", len(inventory.Warnings), inventory.Warnings)
	}
	components := componentsByName(inventory.Components)
	assertComponentEvidence(t, components["@hapi/wreck"], "npm", "package-lock.json", "runtime", "direct", "pkg:npm/%40hapi/wreck@18.0.0")
	assertComponentEvidence(t, components["@hapi/boom"], "npm", "package-lock.json", "runtime", "direct", "pkg:npm/%40hapi/boom@10.0.1")
	assertComponentEvidence(t, components["hoek"], "npm", "package-lock.json", "optional", "direct", "pkg:npm/hoek@9.3.0")
	assertComponentEvidence(t, components["nested-exact"], "npm", "subdir/package-lock.json", "runtime", "direct", "pkg:npm/nested-exact@2.0.1")
	assertComponentEvidence(t, components["nested-transitive"], "npm", "subdir/package-lock.json", "runtime", "direct", "pkg:npm/nested-transitive@4.0.2")
	if _, ok := components["range-only"]; ok {
		t.Fatalf("range-only dependency emitted as installed component, want dependency range ignored without exact installed version")
	}
	if _, ok := components["nested-range-only"]; ok {
		t.Fatalf("nested-range-only dependency emitted as installed component, want dependency range ignored without exact installed version")
	}
}

func TestRepositorySBOMSourceEmitsMalformedLockfileWarning(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, "composer.lock"), `{"packages":[`)
	source, err := newRepositorySBOMSource([]sbomTargetConfig{{
		ScopeID:  "scanner-worker://repository/repo-private-name",
		RootPath: root,
	}})
	if err != nil {
		t.Fatalf("newRepositorySBOMSource() error = %v, want nil", err)
	}

	inventory, err := source.Collect(context.Background(), testSBOMClaimInput(t))
	if err != nil {
		t.Fatalf("Collect() error = %v, want nil; malformed lockfile should emit warning evidence", err)
	}
	if got := len(inventory.Components); got != 0 {
		t.Fatalf("Components len = %d, want 0 for malformed lockfile", got)
	}
	if got, want := len(inventory.Warnings), 1; got != want {
		t.Fatalf("Warnings len = %d, want %d", got, want)
	}
	warning := inventory.Warnings[0]
	if warning.Reason != "lockfile_malformed" {
		t.Fatalf("warning reason = %q, want lockfile_malformed", warning.Reason)
	}
	if warning.LockfilePath != "composer.lock" || warning.Ecosystem != "composer" {
		t.Fatalf("warning evidence = %#v, want composer.lock composer evidence", warning)
	}
	if containsAny(warning.Summary, root) {
		t.Fatalf("warning summary leaked private root path: %q", warning.Summary)
	}
}

func TestRepositorySBOMSourceEnforcesFileLimitWithoutLeakingPaths(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, "package-lock.json"), `{"lockfileVersion":3,"packages":{}}`)
	writeTestFile(t, filepath.Join(root, "go.mod"), "module example.test/app\n")

	source, err := newRepositorySBOMSource([]sbomTargetConfig{{
		ScopeID:  "scanner-worker://repository/repo-private-name",
		RootPath: root,
	}})
	if err != nil {
		t.Fatalf("newRepositorySBOMSource() error = %v, want nil", err)
	}
	input := testSBOMClaimInput(t)
	input.Limits.MaxFiles = 1

	_, err = source.Collect(context.Background(), input)
	if err == nil {
		t.Fatal("Collect() error = nil, want file limit failure")
	}
	var failure scannerworker.AnalyzerFailure
	if !errors.As(err, &failure) {
		t.Fatalf("Collect() error = %T, want scannerworker.AnalyzerFailure", err)
	}
	if got, want := failure.FailureClass(), scannerworker.FailureClassFileLimitExceeded; got != want {
		t.Fatalf("FailureClass = %q, want %q", got, want)
	}
	if got := err.Error(); containsAny(got, root, "package-lock.json", "go.mod") {
		t.Fatalf("Collect() error leaked private target detail: %q", got)
	}
}

func testSBOMClaimInput(t *testing.T) scannerworker.ClaimInput {
	t.Helper()

	now := time.Date(2026, 5, 31, 12, 0, 0, 0, time.UTC)
	item := workflow.WorkItem{
		WorkItemID:          "scanner-worker:collector-scanner:work-1",
		RunID:               "scanner-worker:run-1",
		CollectorKind:       scope.CollectorScannerWorker,
		CollectorInstanceID: "scanner-worker-sbom",
		SourceSystem:        string(scope.CollectorScannerWorker),
		ScopeID:             "scanner-worker://repository/repo-private-name",
		AcceptanceUnitID:    "repository:repo-123",
		SourceRunID:         "scanner-worker:generation-1",
		GenerationID:        "scanner-worker:generation-1",
		FairnessKey:         "scanner_worker:scanner-worker-sbom:repository",
		Status:              workflow.WorkItemStatusClaimed,
		AttemptCount:        1,
		CurrentClaimID:      "claim-1",
		CurrentFencingToken: 7,
		CurrentOwnerID:      "scanner-worker-1",
		LeaseExpiresAt:      now.Add(time.Minute),
		VisibleAt:           now.Add(-time.Minute),
		LastClaimedAt:       now,
		CreatedAt:           now.Add(-time.Hour),
		UpdatedAt:           now,
	}
	claim := workflow.Claim{
		ClaimID:        item.CurrentClaimID,
		WorkItemID:     item.WorkItemID,
		FencingToken:   item.CurrentFencingToken,
		OwnerID:        item.CurrentOwnerID,
		Status:         workflow.ClaimStatusActive,
		ClaimedAt:      now,
		HeartbeatAt:    now,
		LeaseExpiresAt: now.Add(time.Minute),
		CreatedAt:      now,
		UpdatedAt:      now,
	}
	target, err := scannerworker.TargetScopeFromWorkItem(item)
	if err != nil {
		t.Fatalf("TargetScopeFromWorkItem() error = %v, want nil", err)
	}
	limits, err := scannerworker.DefaultResourceLimits(scannerworker.AnalyzerSBOMGeneration)
	if err != nil {
		t.Fatalf("DefaultResourceLimits() error = %v, want nil", err)
	}
	input, err := scannerworker.NewClaimInputAt(item, claim, scannerworker.AnalyzerSBOMGeneration, target, limits, now)
	if err != nil {
		t.Fatalf("NewClaimInputAt() error = %v, want nil", err)
	}
	return input
}

func writeTestFile(t *testing.T, path string, body string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatalf("WriteFile(%s) error = %v", path, err)
	}
}

func countFactKinds(values []facts.Envelope) map[string]int {
	counts := make(map[string]int)
	for _, value := range values {
		counts[value.FactKind]++
	}
	return counts
}

func componentsByName(values []sbomgenerator.Component) map[string]sbomgenerator.Component {
	components := make(map[string]sbomgenerator.Component, len(values))
	for _, value := range values {
		components[value.Name] = value
	}
	return components
}

func assertComponentEvidence(
	t *testing.T,
	component sbomgenerator.Component,
	ecosystem string,
	lockfilePath string,
	dependencyScope string,
	dependencyType string,
	purl string,
) {
	t.Helper()

	if component.Name == "" {
		t.Fatalf("component for %s missing", purl)
	}
	if component.Ecosystem != ecosystem {
		t.Fatalf("%s ecosystem = %q, want %q", component.Name, component.Ecosystem, ecosystem)
	}
	if component.LockfilePath != lockfilePath {
		t.Fatalf("%s lockfile path = %q, want %q", component.Name, component.LockfilePath, lockfilePath)
	}
	if component.DependencyScope != dependencyScope {
		t.Fatalf("%s dependency scope = %q, want %q", component.Name, component.DependencyScope, dependencyScope)
	}
	if component.DependencyType != dependencyType {
		t.Fatalf("%s dependency type = %q, want %q", component.Name, component.DependencyType, dependencyType)
	}
	if component.PURL != purl {
		t.Fatalf("%s purl = %q, want %q", component.Name, component.PURL, purl)
	}
	if component.ExtractionReason != "lockfile_exact_version" {
		t.Fatalf("%s extraction reason = %q, want lockfile_exact_version", component.Name, component.ExtractionReason)
	}
}

func containsAny(value string, needles ...string) bool {
	for _, needle := range needles {
		if needle != "" && strings.Contains(value, needle) {
			return true
		}
	}
	return false
}
