// Code generated by go/internal/collector/contracttest/gen; DO NOT EDIT.
// Source-of-truth: specs/collector_fact_contract.v1.yaml

package contracttest

// AWSContract is the fact-shape contract for the "aws" collector.
var AWSContract = Contract{
	CollectorKind: "aws",
	FactKinds: []FactKindShape{
		{Kind: "aws_dns_record", RequiredPayloadKeys: []string{"account_id", "region", "service_kind", "collector_instance_id", "hosted_zone_id", "hosted_zone_name", "record_name", "record_type", "correlation_anchors"}},
		{Kind: "aws_iam_permission", RequiredPayloadKeys: []string{"account_id", "region", "service_kind", "collector_instance_id", "principal_arn", "principal_type", "policy_source", "effect", "actions"}},
		{Kind: "aws_image_reference", RequiredPayloadKeys: []string{"account_id", "region", "service_kind", "collector_instance_id", "repository_arn", "repository_name", "registry_id", "image_digest", "manifest_digest", "tag", "correlation_anchors"}},
		{Kind: "aws_relationship", RequiredPayloadKeys: []string{"account_id", "region", "service_kind", "collector_instance_id", "relationship_type", "source_resource_id", "source_arn", "target_resource_id", "target_arn", "target_type", "attributes"}},
		{Kind: "aws_resource", RequiredPayloadKeys: []string{"account_id", "region", "service_kind", "collector_instance_id", "arn", "resource_id", "resource_type", "name", "state", "tags", "attributes", "correlation_anchors"}},
		{Kind: "aws_resource_policy_permission", RequiredPayloadKeys: []string{"account_id", "region", "service_kind", "collector_instance_id", "resource_arn", "resource_type", "effect", "actions"}},
		{Kind: "aws_security_group_rule", RequiredPayloadKeys: []string{"account_id", "region", "service_kind", "collector_instance_id", "rule_id", "group_id", "direction", "source_kind", "source_value"}},
		{Kind: "aws_warning", RequiredPayloadKeys: []string{"account_id", "region", "service_kind", "collector_instance_id", "warning_kind", "error_class"}},
		{Kind: "ec2_instance_posture", RequiredPayloadKeys: []string{"account_id", "region", "service_kind", "collector_instance_id", "instance_id", "imds_v2_required"}},
		{Kind: "s3_bucket_posture", RequiredPayloadKeys: []string{"account_id", "region", "service_kind", "collector_instance_id", "bucket_arn", "bucket_name"}},
		{Kind: "s3_external_principal_grant", RequiredPayloadKeys: []string{"account_id", "region", "service_kind", "collector_instance_id", "bucket_arn", "bucket_name", "principal_kind", "principal_value", "grant_outcome"}},
		{Kind: "secrets_iam_coverage_warning", RequiredPayloadKeys: []string{"scope_id", "warning_kind", "source_state", "error_class", "collector_kind"}},
		{Kind: "secrets_iam_instance_profile", RequiredPayloadKeys: []string{"scope_id", "profile_arn", "profile_name", "collector_kind"}},
		{Kind: "secrets_iam_permission_boundary", RequiredPayloadKeys: []string{"scope_id", "principal_arn", "principal_type", "boundary_policy_arn", "collector_kind"}},
		{Kind: "secrets_iam_permission_policy", RequiredPayloadKeys: []string{"scope_id", "principal_arn", "principal_type", "policy_source", "effect", "actions", "collector_kind"}},
		{Kind: "secrets_iam_policy_attachment", RequiredPayloadKeys: []string{"scope_id", "principal_arn", "principal_type", "policy_arn", "collector_kind"}},
		{Kind: "secrets_iam_principal", RequiredPayloadKeys: []string{"scope_id", "principal_arn", "principal_type", "collector_kind"}},
		{Kind: "secrets_iam_trust_policy", RequiredPayloadKeys: []string{"scope_id", "principal_arn", "principal_type", "collector_instance_id"}},
	},
}

// Contracts returns all collector contracts defined in the source-of-truth spec.
func Contracts() []Contract {
	return []Contract{
		AWSContract,
	}
}
