// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package json

import (
	"testing"

	"github.com/eshu-hq/eshu/go/internal/parser/shared"
)

// TestTSConfigJSONCBlockCommentPreservesRealLineNumbers pins issue #5358 (a
// correctness follow-up found reviewing #5329): tsconfig*.json is JSONC, so it
// can carry a `/* ... */` block comment. stripJSONCCommentsWithOffsets drops
// the comment's embedded '\n' bytes when it builds the normalized buffer
// handed to encoding/json -- it never writes them to its output -- so a
// newlineIndex built from that normalized buffer (rather than the original
// on-disk source) undercounts every line after a multi-line block comment by
// however many newlines the comment swallowed. "@app/*" sits on real line 8;
// the pre-fix code reports line 6 (undercounted by the comment's 2 embedded
// newlines).
func TestTSConfigJSONCBlockCommentPreservesRealLineNumbers(t *testing.T) {
	t.Parallel()

	path := writeJSONTestFile(t, "tsconfig.json", `{
  "extends": "./base.json",
  /* generated by our internal
     tsconfig codegen tool --
     do not edit by hand */
  "compilerOptions": {
    "paths": {
      "@app/*": ["src/app/*"]
    }
  }
}`)

	payload, err := Parse(path, false, shared.Options{}, Config{})
	if err != nil {
		t.Fatalf("Parse() error = %v, want nil", err)
	}

	rows, ok := payload["variables"].([]map[string]any)
	if !ok {
		t.Fatalf("variables = %T, want []map[string]any", payload["variables"])
	}
	byName := make(map[string]map[string]any, len(rows))
	for _, row := range rows {
		name, _ := row["name"].(string)
		byName[name] = row
	}

	const target = "path:@app/*"
	row, ok := byName[target]
	if !ok {
		t.Fatalf("row %q missing", target)
	}
	got, ok := row["line_number"].(int)
	if !ok {
		t.Fatalf("row[%q][line_number] = %T, want int", target, row["line_number"])
	}
	const wantLine = 8
	if got != wantLine {
		t.Errorf("row[%q][line_number] = %d, want %d (real on-disk line)", target, got, wantLine)
	}
}

// TestPackageJSONLeadingBlankLinesPreservesRealLineNumbers pins issue #5358: a
// hand-edited package.json can start with blank lines before its opening
// brace. normalizeJSONSource's leading-whitespace TrimLeft removes those blank
// lines' '\n' bytes when it builds the normalized buffer handed to
// encoding/json, so a newlineIndex built from that normalized buffer (rather
// than the original on-disk source) undercounts every line by however many
// leading blank lines were trimmed. "zod" sits on real line 5; the pre-fix
// code reports line 3 (undercounted by the 2 trimmed leading blank lines).
func TestPackageJSONLeadingBlankLinesPreservesRealLineNumbers(t *testing.T) {
	t.Parallel()

	path := writeJSONTestFile(t, "package.json", "\n\n{\n  \"dependencies\": {\n    \"zod\": \"^3.0.0\"\n  }\n}")

	payload, err := Parse(path, false, shared.Options{}, Config{})
	if err != nil {
		t.Fatalf("Parse() error = %v, want nil", err)
	}

	variables, ok := payload["variables"].([]map[string]any)
	if !ok {
		t.Fatalf("variables = %T, want []map[string]any", payload["variables"])
	}
	byName := dependencyRowsByName(variables)

	row, ok := byName["zod"]
	if !ok {
		t.Fatalf("dependency row %q missing", "zod")
	}
	got, ok := row["line_number"].(int)
	if !ok {
		t.Fatalf("row[%q][line_number] = %T, want int", "zod", row["line_number"])
	}
	const wantLine = 5
	if got != wantLine {
		t.Errorf("row[%q][line_number] = %d, want %d (real on-disk line)", "zod", got, wantLine)
	}
}
