// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq
//
// Code generated by go/cmd/fact-envelope-adapter; DO NOT EDIT.

package factenvelope

import (
	"github.com/eshu-hq/eshu/go/internal/facts"
	sdkcollector "github.com/eshu-hq/eshu/sdk/go/collector"
	"github.com/eshu-hq/eshu/sdk/go/factschema"
)

// DefaultSchemaMajorVersion is the schema version assumed for version-less
// envelopes before they enter the factschema Decode seam.
const DefaultSchemaMajorVersion = "1.0.0"

// PersistedVersionlessSchemaVersion is the Postgres sentinel for an envelope
// whose collector emitted no schema version.
const PersistedVersionlessSchemaVersion = "0.0.0"

// InternalEnvelopeOptions carries host-owned fields that never come from an SDK
// fact payload.
type InternalEnvelopeOptions struct {
	ComponentID   string
	ScopeID       string
	GenerationID  string
	CollectorKind string
	FencingToken  int64
}

// InternalFromSDKFact maps one validated collector SDK fact into the durable
// internal envelope shape.
func InternalFromSDKFact(fact sdkcollector.Fact, opts InternalEnvelopeOptions) facts.Envelope {
	envelope := facts.Envelope{
		FactID: facts.StableID("CollectorExtensionFact", map[string]any{
			"component_id":    opts.ComponentID,
			"fact_kind":       fact.Kind,
			"generation_id":   opts.GenerationID,
			"scope_id":        opts.ScopeID,
			"stable_fact_key": fact.StableKey,
		}),
		ScopeID:          opts.ScopeID,
		GenerationID:     opts.GenerationID,
		FactKind:         fact.Kind,
		StableFactKey:    fact.StableKey,
		SchemaVersion:    fact.SchemaVersion,
		CollectorKind:    opts.CollectorKind,
		FencingToken:     opts.FencingToken,
		SourceConfidence: string(fact.SourceConfidence),
		ObservedAt:       fact.ObservedAt.UTC(),
		Payload:          fact.Payload,
		IsTombstone:      fact.Tombstone,
		SourceRef: facts.Ref{
			SourceSystem:   fact.SourceRef.SourceSystem,
			ScopeID:        fact.SourceRef.ScopeID,
			GenerationID:   fact.SourceRef.GenerationID,
			FactKey:        fact.SourceRef.FactKey,
			SourceURI:      fact.SourceRef.URI,
			SourceRecordID: fact.SourceRef.RecordID,
		},
	}
	return envelope.Clone()
}

// FactSchemaFromInternal maps a durable internal envelope into the contracts
// module decode envelope.
func FactSchemaFromInternal(env facts.Envelope) factschema.Envelope {
	schemaVersion := env.SchemaVersion
	if schemaVersion == "" || schemaVersion == PersistedVersionlessSchemaVersion {
		schemaVersion = DefaultSchemaMajorVersion
	}
	return factschema.Envelope{
		FactKind:         env.FactKind,
		SchemaVersion:    schemaVersion,
		StableFactKey:    env.StableFactKey,
		ScopeID:          env.ScopeID,
		GenerationID:     env.GenerationID,
		CollectorKind:    env.CollectorKind,
		SourceConfidence: env.SourceConfidence,
		ObservedAt:       env.ObservedAt,
		IsTombstone:      env.IsTombstone,
		SourceRef:        sourceRefString(env.SourceRef),
		Payload:          env.Payload,
	}
}

func sourceRefString(ref facts.Ref) string {
	if ref.SourceURI != "" {
		return ref.SourceURI
	}
	if ref.SourceRecordID != "" {
		return ref.SourceRecordID
	}
	return ref.FactKey
}
