// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package gcp

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/eshu-hq/eshu/go/internal/demospec"
	"github.com/eshu-hq/eshu/go/internal/replay/cassette"
)

func TestDefaultDemoOrgProfileReservesAcmeIdentityScheme(t *testing.T) {
	profile := DefaultDemoOrgProfile()
	if err := profile.Validate(); err != nil {
		t.Fatalf("DefaultDemoOrgProfile().Validate(): %v", err)
	}
	if profile.GitHubOrg != "acme" {
		t.Fatalf("GitHubOrg = %q, want acme", profile.GitHubOrg)
	}
	if profile.Seed == 0 {
		t.Fatal("Seed must be non-zero so the demo corpus has a stable public identity")
	}

	for _, repo := range []string{"api-svc", "orders-api", "lib-common"} {
		got, ok := profile.JoinKeys.RepositoryRemote(repo)
		if !ok {
			t.Fatalf("RepositoryRemote(%q) missing from join-key registry", repo)
		}
		want := "github.com/acme/" + repo
		if got != want {
			t.Fatalf("RepositoryRemote(%q) = %q, want %q", repo, got, want)
		}
		if !strings.HasPrefix(got, "github.com/acme/") {
			t.Fatalf("RepositoryRemote(%q) = %q, want acme remote prefix", repo, got)
		}
	}

	got, ok := profile.JoinKeys.PackageOwnerHint("github.com/acme/lib-common")
	if !ok {
		t.Fatal("PackageOwnerHint(github.com/acme/lib-common) missing from join-key registry")
	}
	if got != "github.com/acme/lib-common" {
		t.Fatalf("PackageOwnerHint(github.com/acme/lib-common) = %q, want github.com/acme/lib-common", got)
	}
}

func TestGenerateDemoOrgCassetteUsesManifestLayout(t *testing.T) {
	generated, err := GenerateDemoOrgCassette(DefaultDemoOrgProfile())
	if err != nil {
		t.Fatalf("GenerateDemoOrgCassette: %v", err)
	}
	if generated.Family != "gcpcloud" {
		t.Fatalf("Family = %q, want gcpcloud", generated.Family)
	}
	if generated.Recording != "supply-chain-demo.json" {
		t.Fatalf("Recording = %q, want supply-chain-demo.json", generated.Recording)
	}
	wantManifestPath := filepath.Join("testdata", "cassettes", "gcpcloud", "supply-chain-demo.json")
	if generated.ManifestPath != wantManifestPath {
		t.Fatalf("ManifestPath = %q, want %q", generated.ManifestPath, wantManifestPath)
	}
	wantPath := filepath.Join("testdata", "generated-cassettes", "gcpcloud", "supply-chain-demo.json")
	if generated.Path != wantPath {
		t.Fatalf("Path = %q, want %q", generated.Path, wantPath)
	}
	if generated.Path == generated.ManifestPath {
		t.Fatal("generated write path must not overwrite the committed demo-corpus cassette path")
	}

	file, err := cassette.ParseAndValidate(generated.Bytes)
	if err != nil {
		t.Fatalf("generated demo-org cassette does not parse as a valid cassette: %v", err)
	}
	if len(file.Scopes) != 1 {
		t.Fatalf("generated demo-org cassette scopes = %d, want 1", len(file.Scopes))
	}
	metadata := file.Scopes[0].Metadata
	for key, want := range map[string]string{
		"demo_org":        "acme",
		"github_org":      "acme",
		"identity_scheme": "github.com/acme/<repo>",
	} {
		if got := metadata[key]; got != want {
			t.Fatalf("scope metadata[%q] = %q, want %q", key, got, want)
		}
	}
}

func TestGenerateDemoOrgCassetteIsByteIdenticalForSameSeed(t *testing.T) {
	profile := DefaultDemoOrgProfile()
	first, err := GenerateDemoOrgCassette(profile)
	if err != nil {
		t.Fatalf("GenerateDemoOrgCassette run 1: %v", err)
	}
	second, err := GenerateDemoOrgCassette(profile)
	if err != nil {
		t.Fatalf("GenerateDemoOrgCassette run 2: %v", err)
	}
	if !bytes.Equal(first.Bytes, second.Bytes) {
		t.Fatal("GenerateDemoOrgCassette is not deterministic for the same profile seed")
	}
}

func TestWriteDemoOrgCassetteEmitsGeneratedArtifactFile(t *testing.T) {
	root := t.TempDir()
	generated, err := WriteDemoOrgCassette(root, DefaultDemoOrgProfile())
	if err != nil {
		t.Fatalf("WriteDemoOrgCassette: %v", err)
	}

	writtenPath := filepath.Join(root, generated.Path)
	written, err := os.ReadFile(writtenPath) // #nosec G304 -- path is under t.TempDir and generated by this package.
	if err != nil {
		t.Fatalf("read written cassette %s: %v", writtenPath, err)
	}
	if !bytes.Equal(written, generated.Bytes) {
		t.Fatal("written cassette bytes differ from generated cassette bytes")
	}
	if _, err := cassette.ParseAndValidate(written); err != nil {
		t.Fatalf("written cassette does not parse as a valid cassette: %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, generated.ManifestPath)); !os.IsNotExist(err) {
		t.Fatalf("WriteDemoOrgCassette wrote committed manifest path %s; err=%v", generated.ManifestPath, err)
	}
}

func TestDemoOrgGeneratedGCPCassetteMatchesDemoManifestArtifact(t *testing.T) {
	root := moduleRoot(t)
	manifest, err := demospec.LoadManifest(filepath.Join(root, "specs", demospec.ManifestFileName))
	if err != nil {
		t.Fatalf("LoadManifest: %v", err)
	}
	generated, err := GenerateDemoOrgCassette(DefaultDemoOrgProfile())
	if err != nil {
		t.Fatalf("GenerateDemoOrgCassette: %v", err)
	}

	manifestReferencesGCP := false
	for _, question := range manifest.Questions {
		for _, family := range question.Artifacts.Cassettes {
			if family == generated.Family {
				manifestReferencesGCP = true
			}
		}
	}
	if !manifestReferencesGCP {
		t.Fatalf("demo manifest does not reference cassette family %q", generated.Family)
	}

	wantPath := filepath.Join("testdata", "cassettes", generated.Family, generated.Recording)
	if generated.ManifestPath != wantPath {
		t.Fatalf("generated cassette manifest path = %q, want %q", generated.ManifestPath, wantPath)
	}
	if generated.Path == generated.ManifestPath {
		t.Fatal("generated write path must stay separate from the committed manifest artifact path")
	}
	if _, err := cassette.ParseAndValidate(generated.Bytes); err != nil {
		t.Fatalf("generated cassette candidate for %s is invalid: %v", generated.ManifestPath, err)
	}
}

func TestDemoOrgGeneratedGCPCassetteCommittedSwapRequiresGoldenGate(t *testing.T) {
	if os.Getenv("ESHU_SYNTH_GCP_GOLDEN_SWAP") != "1" {
		t.Skip("set ESHU_SYNTH_GCP_GOLDEN_SWAP=1 to run the operator-gated golden-corpus swap proof")
	}

	root := moduleRoot(t)
	generated, err := GenerateDemoOrgCassette(DefaultDemoOrgProfile())
	if err != nil {
		t.Fatalf("GenerateDemoOrgCassette: %v", err)
	}
	cassettePath := filepath.Join(root, generated.ManifestPath)
	original, err := os.ReadFile(cassettePath) // #nosec G304 -- repo-owned cassette path selected by the generator.
	if err != nil {
		t.Fatalf("read original cassette %s: %v", cassettePath, err)
	}
	t.Cleanup(func() {
		if err := os.WriteFile(cassettePath, original, 0o644); err != nil {
			t.Errorf("restore original cassette %s: %v", cassettePath, err)
		}
	})

	// #nosec G306 -- operator-gated replacement of public fixture data.
	if err := os.WriteFile(cassettePath, generated.Bytes, 0o644); err != nil {
		t.Fatalf("write generated cassette to committed manifest path %s: %v", cassettePath, err)
	}
	cmd := exec.Command("bash", "scripts/verify-golden-corpus-gate.sh")
	cmd.Dir = root
	cmd.Env = append(os.Environ(), "GOCACHE="+filepath.Join(root, ".gocache-golden-swap"))
	out, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("golden-corpus swap gate failed after replacing %s:\n%s\n%v", generated.ManifestPath, string(out), err)
	}
}

func moduleRoot(t *testing.T) string {
	t.Helper()
	_, thisFile, _, ok := runtime.Caller(0)
	if !ok {
		t.Fatal("runtime.Caller failed; cannot locate repository root")
	}
	dir := filepath.Dir(thisFile)
	for {
		if _, err := os.Stat(filepath.Join(dir, "specs", demospec.ManifestFileName)); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("reached filesystem root without finding specs/" + demospec.ManifestFileName)
		}
		dir = parent
	}
}
