// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package urlredact

import (
	"fmt"
	"strings"
)

// TailSentinel is the second synthetic credential a DifferentialCase carries.
// It sits AFTER the escape, so a walk that treats the escape as the end of the
// value removes Sentinel and leaves TailSentinel — the partial leak that a
// whole-value assertion cannot see.
const TailSentinel = "URLREDACT-TAILSENTINEL-4b1c"

// DifferentialCase is one raw query string handed to BOTH redaction walks so
// their answers can be compared to each other rather than to a hand-written
// expectation.
//
// BoundaryCases pins what each walk produces; this pins that the two decide the
// same thing. The distinction is not academic. Depth and position are decided
// independently in urlredact.Query and in reportbundle's free-text scan, both
// walks passed every row of the boundary corpus, and they still disagreed on 81
// of 378 generated inputs: the endpoint walk shipped a whole credential when an
// escape opened the value, and the free-text walk cut one in half at an escaped
// space, quote or tab inside an already-encoded pair. Neither had a corpus row,
// because a corpus row is written by whoever already knows the case exists.
//
// The inputs are generated by crossing the axes that broke — the key name, the
// spelling of the pair's own "=", which byte the escape stands for, WHERE in the
// value it sits, and what follows the pair — so a cell nobody thought of is
// still covered.
type DifferentialCase struct {
	// Name identifies the row in test output.
	Name string
	// Input is the identical byte sequence given to both walks. It is a raw
	// query string, which is what Query takes and is also valid free text.
	Input string
	// Secrets are the credential fragments whose survival is compared. A row
	// carries two when the escape sits inside the value, so truncation at the
	// escape shows up as one fragment removed and one kept.
	Secrets []string
	// WalksDisagree records why the two walks provably cannot agree on this
	// row. Empty means they must. CheckAgreement asserts both directions, so an
	// exemption that stops being true fails rather than quietly widening what
	// the differential permits.
	WalksDisagree string
}

// CheckAgreement reports whether the two walks decided the same thing about
// every fragment of this row. It returns nil when they did.
//
// It is the single implementation both drivers are held to, so the packages
// cannot drift on what agreement means. Neither redacted body is echoed: a
// failure message that printed the output would become the leak it reports.
//
// Agreement is about REMOVAL, not about the resulting bytes. The two walks emit
// different text on purpose — the endpoint walk keeps the parameter name so an
// operator can see which parameter was dropped, the free-text walk removes the
// name too because leaving "api_key=" standing would be re-found on the next
// pass. Comparing bytes would need an exemption on almost every row and would
// pin nothing.
func (c DifferentialCase) CheckAgreement(endpointOut, freeTextOut string) error {
	var split []string
	for _, secret := range c.Secrets {
		endpointKept := strings.Contains(endpointOut, secret)
		freeTextKept := strings.Contains(freeTextOut, secret)
		switch {
		case endpointKept && !freeTextKept:
			split = append(split, "the endpoint walk kept a fragment the free-text walk removed")
		case freeTextKept && !endpointKept:
			split = append(split, "the free-text walk kept a fragment the endpoint walk removed")
		}
	}
	switch {
	case len(split) > 0 && c.WalksDisagree == "":
		return fmt.Errorf("the walks disagree and nothing records why: %s", strings.Join(split, "; "))
	case len(split) == 0 && c.WalksDisagree != "":
		return fmt.Errorf("the walks now agree, so the recorded exemption is stale: %s", c.WalksDisagree)
	}
	return nil
}

// differentialKeyNames vary whether the pair is credential-shaped at all. The
// benign name is there for the other direction: the two walks must also agree
// to leave a pair alone, or one of them is over-removing a parameter a
// maintainer needed.
var differentialKeyNames = []string{"token", "api_key", "q"}

// differentialSeparatorSpellings vary how the pair's own "=" arrived, which is
// what selects the depth an escape after it is read at.
var differentialSeparatorSpellings = []struct{ name, text string }{
	{"a literal equals", "="},
	{"an encoded equals", "%3D"},
}

// differentialEscapes vary which byte the escape inside the value stands for.
// Three of them are URL structure (urlredact.PairSeparators); the rest are prose
// delimiters or an "=", and an encoder writes those precisely because the byte
// is INSIDE a value. Both groups are here because the walks split on which
// group they honoured at which depth.
var differentialEscapes = []struct{ name, text string }{
	{"an escaped question mark", "%3F"},
	{"an escaped ampersand", "%26"},
	{"an escaped semicolon", "%3B"},
	{"an escaped equals", "%3D"},
	{"an escaped space", "%20"},
	{"an escaped tab", "%09"},
	{"an escaped carriage return", "%0D"},
	{"an escaped line feed", "%0A"},
	{"an escaped double quote", "%22"},
	{"an escaped single quote", "%27"},
	{"an escaped backtick", "%60"},
}

// differentialEscapePositions vary WHERE in the value the escape sits. This is
// the axis both the corpus and the unit rows missed: every row they carried put
// at least one value byte in front of the escape, so the cell where the escape
// is the value's first byte — the one that shipped a credential whole — was
// never reached.
var differentialEscapePositions = []struct {
	name  string
	value func(escape string) (string, []string)
}{
	{
		name: "opening the value",
		value: func(escape string) (string, []string) {
			return escape + Sentinel, []string{Sentinel}
		},
	},
	{
		name: "inside the value",
		value: func(escape string) (string, []string) {
			return Sentinel + escape + TailSentinel, []string{Sentinel, TailSentinel}
		},
	},
	{
		name: "closing the value",
		value: func(escape string) (string, []string) {
			return Sentinel + escape, []string{Sentinel}
		},
	},
}

// differentialSuffixes vary what follows the pair, because a credential in LAST
// position hides which boundary a walk actually knows: the value runs to the end
// of the string either way.
var differentialSuffixes = []struct{ name, text string }{
	{"nothing after it", ""},
	{"a literal pair after it", "&repo=demo"},
	{"an encoded pair after it", "%26repo%3Ddemo"},
}

// DifferentialCases returns the generated cross-product both walks are driven
// through. It is a function rather than a package-level slice so no caller can
// mutate a table another test then reads.
func DifferentialCases() []DifferentialCase {
	cases := make([]DifferentialCase, 0,
		len(differentialKeyNames)*len(differentialSeparatorSpellings)*len(differentialEscapes)*
			len(differentialEscapePositions)*len(differentialSuffixes))
	for _, key := range differentialKeyNames {
		for _, equals := range differentialSeparatorSpellings {
			for _, escape := range differentialEscapes {
				for _, position := range differentialEscapePositions {
					value, secrets := position.value(escape.text)
					for _, suffix := range differentialSuffixes {
						cases = append(cases, DifferentialCase{
							Name: fmt.Sprintf("%q joined by %s with %s %s and %s",
								key, equals.name, escape.name, position.name, suffix.name),
							Input:   key + equals.text + value + suffix.text,
							Secrets: secrets,
						})
					}
				}
			}
		}
	}
	return cases
}
