// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package urlredact

import (
	"errors"
	"fmt"
	"strings"
)

// TailSentinel is the second synthetic credential a DifferentialCase carries.
// It sits AFTER the escape, so a walk that treats the escape as the end of the
// value removes Sentinel and leaves TailSentinel — the partial leak that a
// whole-value assertion cannot see.
const TailSentinel = "URLREDACT-TAILSENTINEL-4b1c"

// DifferentialCase is one raw query string handed to BOTH redaction walks so
// their answers can be compared to each other rather than to a hand-written
// expectation.
//
// BoundaryCases pins what each walk produces; this pins that the two decide the
// same thing. The distinction is not academic. Depth and position are decided
// independently in urlredact.Query and in reportbundle's free-text scan, both
// walks passed every row of the boundary corpus, and they still disagreed on 72
// of 594 generated inputs: the endpoint walk shipped a whole credential when an
// escape opened the value, and the free-text walk cut one in half at an escaped
// space, quote or tab inside an already-encoded pair. Neither had a corpus row,
// because a corpus row is written by whoever already knows the case exists.
//
// 378 of those 594 rows carry a credential fragment both walks must remove.
// The rest are the over-removal direction — a benign name, or text past the
// separator that ended the pair — and they pin agreement, not removal. The two
// are separate fields for that reason.
//
// The inputs are generated by crossing the axes that broke — the key name, the
// spelling of the pair's own "=", which byte the escape stands for, WHERE in the
// value it sits, and what follows the pair — so a cell nobody thought of is
// still covered.
type DifferentialCase struct {
	// Name identifies the row in test output.
	Name string
	// Input is the identical byte sequence given to both walks. It is a raw
	// query string, which is what Query takes and is also valid free text.
	Input string
	// Removable are the fragments the depth model puts INSIDE the value of a
	// credential-named pair. Both walks must remove every one of them, and
	// CheckRemoval says so directly rather than leaving it to agreement.
	//
	// A row carries two when the escape is content of the value, and one when
	// the escape ends it, so truncation at the escape shows up as one fragment
	// removed and one kept.
	Removable []string
	// Outside are the fragments the depth model puts outside any credential
	// value: after a separator that ended the pair, or under a name no
	// sensitive-key rule matches. The walks must AGREE about them, and nothing
	// more — over-removal is this package's accepted cost, so neither keeping
	// nor removing them is required.
	//
	// Declaring these apart from Removable is what makes the coverage number
	// honest. They were all in one list, and 234 of 594 rows landed where BOTH
	// walks keep the fragment, 36 of those under a credential-shaped name. Not
	// a leak — one layer down "token%3D%26X" really does carry an empty value
	// and X is a separate bare parameter. But 18 of those 36 declared nothing
	// else, so they carried no removal assertion at all while counting toward
	// the coverage the guard's justification rests on. The other 18 also
	// declared a fragment that IS in the value, and did signal.
	Outside []string
	// WalksDisagree records why the two walks provably cannot agree on this
	// row. Empty means they must. CheckAgreement asserts both directions, so an
	// exemption that stops being true fails rather than quietly widening what
	// the differential permits.
	//
	// It is not the field for a row where both walks keep a fragment. That is
	// agreement, so recording it here would trip the stale-exemption branch;
	// classify the fragment as Outside instead.
	WalksDisagree string
}

// Fragments returns every declared fragment, for a caller that only asks
// whether the two implementations decided a fragment the same way and does not
// care which side of the value it sits on.
func (c DifferentialCase) Fragments() []string {
	all := make([]string, 0, len(c.Removable)+len(c.Outside))
	all = append(all, c.Removable...)
	return append(all, c.Outside...)
}

// CheckRemoval reports whether both walks removed every fragment the depth
// model puts inside a credential value. It returns nil when they did.
//
// This is the positive half, and the differential had no such half. Comparing
// the walks to each other catches them drifting apart and says nothing when
// they drift together: breaking the name predicate they share stops BOTH from
// removing anything, every row still agrees, and the whole table stays green.
// A guard whose failure mode is "both walks became wrong in the same way" is
// worth having only if something also asserts what right looks like.
//
// Neither redacted body is echoed: a failure message that printed the output
// would become the leak it reports.
func (c DifferentialCase) CheckRemoval(endpointOut, freeTextOut string) error {
	for _, fragment := range c.Removable {
		endpointKept := strings.Contains(endpointOut, fragment)
		freeTextKept := strings.Contains(freeTextOut, fragment)
		switch {
		case endpointKept && freeTextKept:
			return errors.New("both walks kept a fragment inside a credential value")
		case endpointKept:
			return errors.New("the endpoint walk kept a fragment inside a credential value")
		case freeTextKept:
			return errors.New("the free-text walk kept a fragment inside a credential value")
		}
	}
	return nil
}

// CheckAgreement reports whether the two walks decided the same thing about
// every fragment of this row. It returns nil when they did.
//
// It is the single implementation both drivers are held to, so the packages
// cannot drift on what agreement means. Neither redacted body is echoed: a
// failure message that printed the output would become the leak it reports.
//
// Agreement is about REMOVAL, not about the resulting bytes. The two walks emit
// different text on purpose — the endpoint walk keeps the parameter name so an
// operator can see which parameter was dropped, the free-text walk removes the
// name too because leaving "api_key=" standing would be re-found on the next
// pass. Comparing bytes would need an exemption on almost every row and would
// pin nothing.
func (c DifferentialCase) CheckAgreement(endpointOut, freeTextOut string) error {
	var split []string
	for _, fragment := range c.Fragments() {
		endpointKept := strings.Contains(endpointOut, fragment)
		freeTextKept := strings.Contains(freeTextOut, fragment)
		switch {
		case endpointKept && !freeTextKept:
			split = append(split, "the endpoint walk kept a fragment the free-text walk removed")
		case freeTextKept && !endpointKept:
			split = append(split, "the free-text walk kept a fragment the endpoint walk removed")
		}
	}
	switch {
	case len(split) > 0 && c.WalksDisagree == "":
		return fmt.Errorf("the walks disagree and nothing records why: %s", strings.Join(split, "; "))
	case len(split) == 0 && c.WalksDisagree != "":
		return fmt.Errorf("the walks now agree, so the recorded exemption is stale: %s", c.WalksDisagree)
	}
	return nil
}

// Every axis below carries the model's own answer as a hand-written literal
// rather than asking the production code. That is deliberate. An oracle that
// called collector.IsSensitiveKeyName or read PairSeparators would move
// whenever the code it is checking moves: break the name predicate and every
// row would reclassify its fragments as Outside, the table would stop asserting
// any removal, and the differential would go green on a walk that had stopped
// redacting. The literals are the second opinion.

// differentialKeyNames vary whether the pair is credential-shaped at all. The
// benign name is there for the other direction: the two walks must also agree
// to leave a pair alone, or one of them is over-removing a parameter a
// maintainer needed.
var differentialKeyNames = []struct {
	name string
	// credentialShaped is what collector.IsSensitiveKeyName says about this
	// name, written down rather than asked.
	credentialShaped bool
}{
	{name: "token", credentialShaped: true},
	{name: "api_key", credentialShaped: true},
	{name: "q", credentialShaped: false},
}

// differentialSeparatorSpellings vary how the pair's own "=" arrived, which is
// what selects the depth an escape after it is read at.
var differentialSeparatorSpellings = []struct {
	name, text string
	// encoded is true when the pair's structure sits one layer down, which is
	// the only depth where an escaped separator ends the value.
	encoded bool
}{
	{name: "a literal equals", text: "=", encoded: false},
	{name: "an encoded equals", text: "%3D", encoded: true},
}

// differentialEscapes vary which byte the escape inside the value stands for.
// Three of them are URL structure (urlredact.PairSeparators); the rest are prose
// delimiters or an "=", and an encoder writes those precisely because the byte
// is INSIDE a value. Both groups are here because the walks split on which
// group they honoured at which depth.
var differentialEscapes = []struct {
	name, text string
	// pairSeparator is whether this byte is in PairSeparators, written down
	// rather than read from it. Together with an encoded "=" it is what ends
	// the value early, which decides where the fragments after it belong.
	pairSeparator bool
}{
	{name: "an escaped question mark", text: "%3F", pairSeparator: true},
	{name: "an escaped ampersand", text: "%26", pairSeparator: true},
	{name: "an escaped semicolon", text: "%3B", pairSeparator: true},
	{name: "an escaped equals", text: "%3D", pairSeparator: false},
	{name: "an escaped space", text: "%20", pairSeparator: false},
	{name: "an escaped tab", text: "%09", pairSeparator: false},
	{name: "an escaped carriage return", text: "%0D", pairSeparator: false},
	{name: "an escaped line feed", text: "%0A", pairSeparator: false},
	{name: "an escaped double quote", text: "%22", pairSeparator: false},
	{name: "an escaped single quote", text: "%27", pairSeparator: false},
	{name: "an escaped backtick", text: "%60", pairSeparator: false},
}

// differentialEscapePositions vary WHERE in the value the escape sits. This is
// the axis both the corpus and the unit rows missed: every row they carried put
// at least one value byte in front of the escape, so the cell where the escape
// is the value's first byte — the one that shipped a credential whole — was
// never reached.
// The value function returns the value text plus the fragments on each side of
// the escape, because which side a fragment is on is what decides whether the
// depth model still counts it as part of the credential.
var differentialEscapePositions = []struct {
	name  string
	value func(escape string) (text string, beforeEscape, afterEscape []string)
}{
	{
		name: "opening the value",
		value: func(escape string) (string, []string, []string) {
			return escape + Sentinel, nil, []string{Sentinel}
		},
	},
	{
		name: "inside the value",
		value: func(escape string) (string, []string, []string) {
			return Sentinel + escape + TailSentinel, []string{Sentinel}, []string{TailSentinel}
		},
	},
	{
		name: "closing the value",
		value: func(escape string) (string, []string, []string) {
			return Sentinel + escape, []string{Sentinel}, nil
		},
	},
}

// differentialSuffixes vary what follows the pair, because a credential in LAST
// position hides which boundary a walk actually knows: the value runs to the end
// of the string either way.
var differentialSuffixes = []struct{ name, text string }{
	{"nothing after it", ""},
	{"a literal pair after it", "&repo=demo"},
	{"an encoded pair after it", "%26repo%3Ddemo"},
}

// DifferentialCases returns the generated cross-product both walks are driven
// through. It is a function rather than a package-level slice so no caller can
// mutate a table another test then reads.
func DifferentialCases() []DifferentialCase {
	cases := make([]DifferentialCase, 0,
		len(differentialKeyNames)*len(differentialSeparatorSpellings)*len(differentialEscapes)*
			len(differentialEscapePositions)*len(differentialSuffixes))
	for _, key := range differentialKeyNames {
		for _, equals := range differentialSeparatorSpellings {
			for _, escape := range differentialEscapes {
				for _, position := range differentialEscapePositions {
					value, beforeEscape, afterEscape := position.value(escape.text)
					removable, outside := classifyFragments(
						key.credentialShaped, equals.encoded && escape.pairSeparator,
						beforeEscape, afterEscape,
					)
					for _, suffix := range differentialSuffixes {
						cases = append(cases, DifferentialCase{
							Name: fmt.Sprintf("%q joined by %s with %s %s and %s",
								key.name, equals.name, escape.name, position.name, suffix.name),
							Input:     key.name + equals.text + value + suffix.text,
							Removable: removable,
							Outside:   outside,
						})
					}
				}
			}
		}
	}
	return cases
}

// classifyFragments is the model, stated once: which declared fragments the two
// walks must remove, and which are text that happens to sit nearby.
//
// escapeEndsValue is the one case where the escape is structure rather than
// content — the pair's own "=" arrived encoded AND the escape stands for a pair
// separator — so the value stops there and everything after it is a separate
// parameter. "token%3D%26X" decodes to "token=&X": the pair carries an empty
// value and X is a bare parameter name, not a credential. Declaring X a secret
// there is what left 18 credential-named rows with no removal assertion at all.
func classifyFragments(credentialShaped, escapeEndsValue bool, beforeEscape, afterEscape []string) (removable, outside []string) {
	switch {
	case !credentialShaped:
		// No sensitive-key rule matches the name, so nothing in the pair is a
		// credential and neither walk is required to remove any of it.
		return nil, append(append([]string{}, beforeEscape...), afterEscape...)
	case escapeEndsValue:
		return append([]string{}, beforeEscape...), append([]string{}, afterEscape...)
	default:
		// The escape is content, so the whole value is the credential.
		return append(append([]string{}, beforeEscape...), afterEscape...), nil
	}
}
