// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package shape

// entityBucketMapping pairs a parser output bucket name with the canonical
// content-entity node label it materializes into.
type entityBucketMapping struct {
	bucket string
	label  string
}

// contentEntityBuckets is the frozen, ordered table mapping parser buckets to
// node labels. Order is significant: it fixes the deterministic iteration order
// used by materializeEntities and is referenced as a single table by the
// entity-row count contract. Do not reorder existing rows.
var contentEntityBuckets = []entityBucketMapping{
	{bucket: "functions", label: "Function"},
	{bucket: "classes", label: "Class"},
	{bucket: "modules", label: "Module"},
	{bucket: "variables", label: "Variable"},
	{bucket: "type_annotations", label: "TypeAnnotation"},
	{bucket: "traits", label: "Trait"},
	{bucket: "interfaces", label: "Interface"},
	{bucket: "macros", label: "Macro"},
	{bucket: "structs", label: "Struct"},
	{bucket: "enums", label: "Enum"},
	{bucket: "protocols", label: "Protocol"},
	{bucket: "protocol_implementations", label: "ProtocolImplementation"},
	{bucket: "unions", label: "Union"},
	{bucket: "typedefs", label: "Typedef"},
	{bucket: "type_aliases", label: "TypeAlias"},
	{bucket: "annotations", label: "Annotation"},
	{bucket: "records", label: "Record"},
	{bucket: "properties", label: "Property"},
	{bucket: "components", label: "Component"},
	{bucket: "k8s_resources", label: "K8sResource"},
	{bucket: "argocd_applications", label: "ArgoCDApplication"},
	{bucket: "argocd_applicationsets", label: "ArgoCDApplicationSet"},
	{bucket: "crossplane_xrds", label: "CrossplaneXRD"},
	{bucket: "crossplane_compositions", label: "CrossplaneComposition"},
	{bucket: "crossplane_claims", label: "CrossplaneClaim"},
	{bucket: "kustomize_overlays", label: "KustomizeOverlay"},
	{bucket: "helm_charts", label: "HelmChart"},
	{bucket: "helm_values", label: "HelmValues"},
	{bucket: "terraform_blocks", label: "TerraformBlock"},
	{bucket: "terraform_resources", label: "TerraformResource"},
	{bucket: "terraform_variables", label: "TerraformVariable"},
	{bucket: "terraform_outputs", label: "TerraformOutput"},
	{bucket: "terraform_modules", label: "TerraformModule"},
	{bucket: "terraform_data_sources", label: "TerraformDataSource"},
	{bucket: "terraform_providers", label: "TerraformProvider"},
	{bucket: "terraform_locals", label: "TerraformLocal"},
	{bucket: "terraform_backends", label: "TerraformBackend"},
	{bucket: "terraform_imports", label: "TerraformImport"},
	{bucket: "terraform_moved_blocks", label: "TerraformMovedBlock"},
	{bucket: "terraform_removed_blocks", label: "TerraformRemovedBlock"},
	{bucket: "terraform_checks", label: "TerraformCheck"},
	{bucket: "terraform_lock_providers", label: "TerraformLockProvider"},
	{bucket: "terragrunt_configs", label: "TerragruntConfig"},
	{bucket: "terragrunt_dependencies", label: "TerragruntDependency"},
	{bucket: "terragrunt_locals", label: "TerragruntLocal"},
	{bucket: "terragrunt_inputs", label: "TerragruntInput"},
	{bucket: "cloudformation_resources", label: "CloudFormationResource"},
	{bucket: "cloudformation_parameters", label: "CloudFormationParameter"},
	{bucket: "cloudformation_outputs", label: "CloudFormationOutput"},
	{bucket: "cloudformation_conditions", label: "CloudFormationCondition"},
	{bucket: "cloudformation_cross_stack_imports", label: "CloudFormationImport"},
	{bucket: "cloudformation_cross_stack_exports", label: "CloudFormationExport"},
	{bucket: "atlantis_projects", label: "AtlantisProject"},
	{bucket: "atlantis_workflows", label: "AtlantisWorkflow"},
	{bucket: "sql_tables", label: "SqlTable"},
	{bucket: "sql_columns", label: "SqlColumn"},
	{bucket: "sql_views", label: "SqlView"},
	{bucket: "sql_functions", label: "SqlFunction"},
	{bucket: "sql_triggers", label: "SqlTrigger"},
	{bucket: "sql_indexes", label: "SqlIndex"},
	{bucket: "analytics_models", label: "AnalyticsModel"},
	{bucket: "data_assets", label: "DataAsset"},
	{bucket: "data_columns", label: "DataColumn"},
	{bucket: "query_executions", label: "QueryExecution"},
	{bucket: "dashboard_assets", label: "DashboardAsset"},
	{bucket: "data_quality_checks", label: "DataQualityCheck"},
	{bucket: "data_owners", label: "DataOwner"},
	{bucket: "data_contracts", label: "DataContract"},
	{bucket: "impl_blocks", label: "ImplBlock"},
	{bucket: "pagerduty_declarations", label: "PagerDutyDeclaration"},
}

// sourceFieldContainsCode is the set of entity labels whose Source field holds
// real code text (as opposed to a structured/IaC payload).
var sourceFieldContainsCode = map[string]struct{}{
	"Annotation":             {},
	"Class":                  {},
	"Component":              {},
	"Enum":                   {},
	"Function":               {},
	"Interface":              {},
	"Macro":                  {},
	"Module":                 {},
	"ImplBlock":              {},
	"Property":               {},
	"Protocol":               {},
	"ProtocolImplementation": {},
	"Record":                 {},
	"Struct":                 {},
	"Trait":                  {},
	"TypeAlias":              {},
	"Typedef":                {},
	"Union":                  {},
	"Variable":               {},
}

// trailingNewlineLabels is the set of entity labels whose cached source text is
// normalized to end with a trailing newline by withTrailingNewline.
var trailingNewlineLabels = map[string]struct{}{
	"Annotation":              {},
	"ArgoCDApplication":       {},
	"ArgoCDApplicationSet":    {},
	"AtlantisProject":         {},
	"AtlantisWorkflow":        {},
	"Class":                   {},
	"Component":               {},
	"CloudFormationOutput":    {},
	"CloudFormationParameter": {},
	"CloudFormationResource":  {},
	"ImplBlock":               {},
	"CrossplaneClaim":         {},
	"CrossplaneComposition":   {},
	"CrossplaneXRD":           {},
	"Enum":                    {},
	"Function":                {},
	"HelmChart":               {},
	"HelmValues":              {},
	"Interface":               {},
	"Module":                  {},
	"K8sResource":             {},
	"KustomizeOverlay":        {},
	"Macro":                   {},
	"Property":                {},
	"Protocol":                {},
	"ProtocolImplementation":  {},
	"Record":                  {},
	"SqlColumn":               {},
	"SqlFunction":             {},
	"SqlIndex":                {},
	"SqlTable":                {},
	"SqlTrigger":              {},
	"SqlView":                 {},
	"Struct":                  {},
	"TerragruntConfig":        {},
	"TerragruntDependency":    {},
	"TerragruntInput":         {},
	"TerragruntLocal":         {},
	"TerraformDataSource":     {},
	"TerraformBackend":        {},
	"TerraformCheck":          {},
	"TerraformImport":         {},
	"TerraformLockProvider":   {},
	"TerraformLocal":          {},
	"TerraformModule":         {},
	"TerraformMovedBlock":     {},
	"TerraformOutput":         {},
	"TerraformProvider":       {},
	"TerraformRemovedBlock":   {},
	"TerraformResource":       {},
	"TerraformVariable":       {},
	"Trait":                   {},
	"TypeAlias":               {},
	"TypeAnnotation":          {},
	"Typedef":                 {},
	"Union":                   {},
	"Variable":                {},
}
