// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"io"
	"os"
	"path/filepath"
	"strings"
)

type options struct {
	repoRoot string
	out      string
	check    bool
}

func main() {
	if err := run(os.Args[1:], os.Stdout, os.Stderr); err != nil {
		_, _ = fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(args []string, stdout io.Writer, stderr io.Writer) error {
	opts, err := parseOptions(args, stderr)
	if err != nil {
		return err
	}
	generated, err := renderAdapter()
	if err != nil {
		return err
	}
	if opts.check {
		if err := verifyFile(opts.out, generated); err != nil {
			return err
		}
		_, _ = fmt.Fprintln(stdout, "fact-envelope-adapter: generated artifact is current")
		return nil
	}
	if err := writeFile(opts.out, generated); err != nil {
		return err
	}
	_, _ = fmt.Fprintf(stdout, "fact-envelope-adapter: wrote %s\n", opts.out)
	return nil
}

func parseOptions(args []string, stderr io.Writer) (options, error) {
	flags := flag.NewFlagSet("fact-envelope-adapter", flag.ContinueOnError)
	flags.SetOutput(stderr)
	opts := options{}
	flags.StringVar(&opts.repoRoot, "repo-root", "..", "repository root")
	flags.StringVar(&opts.out, "out", "", "generated Go output path")
	flags.BoolVar(&opts.check, "check", false, "verify generated output without writing")
	if err := flags.Parse(args); err != nil {
		return options{}, err //nolint:wrapcheck // flag errors are self-describing.
	}
	opts.repoRoot = strings.TrimSpace(opts.repoRoot)
	if opts.repoRoot == "" {
		return options{}, fmt.Errorf("-repo-root is required")
	}
	if strings.TrimSpace(opts.out) == "" {
		opts.out = filepath.Join(opts.repoRoot, "go", "internal", "factenvelope", "adapter_generated.go")
	}
	return opts, nil
}

func renderAdapter() ([]byte, error) {
	source := []byte(`// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq
//
// Code generated by go/cmd/fact-envelope-adapter; DO NOT EDIT.

package factenvelope

import (
	"github.com/eshu-hq/eshu/go/internal/facts"
	sdkcollector "github.com/eshu-hq/eshu/sdk/go/collector"
	"github.com/eshu-hq/eshu/sdk/go/factschema"
)

// DefaultSchemaMajorVersion is the schema version assumed for version-less
// envelopes before they enter the factschema Decode seam.
const DefaultSchemaMajorVersion = "1.0.0"

// PersistedVersionlessSchemaVersion is the Postgres sentinel for an envelope
// whose collector emitted no schema version.
const PersistedVersionlessSchemaVersion = "0.0.0"

// InternalEnvelopeOptions carries host-owned fields that never come from an SDK
// fact payload.
type InternalEnvelopeOptions struct {
	ComponentID   string
	ScopeID       string
	GenerationID  string
	CollectorKind string
	FencingToken  int64
}

// InternalFromSDKFact maps one validated collector SDK fact into the durable
// internal envelope shape.
func InternalFromSDKFact(fact sdkcollector.Fact, opts InternalEnvelopeOptions) facts.Envelope {
	envelope := facts.Envelope{
		FactID: facts.StableID("CollectorExtensionFact", map[string]any{
			"component_id":    opts.ComponentID,
			"fact_kind":       fact.Kind,
			"generation_id":   opts.GenerationID,
			"scope_id":        opts.ScopeID,
			"stable_fact_key": fact.StableKey,
		}),
		ScopeID:          opts.ScopeID,
		GenerationID:     opts.GenerationID,
		FactKind:         fact.Kind,
		StableFactKey:    fact.StableKey,
		SchemaVersion:    fact.SchemaVersion,
		CollectorKind:    opts.CollectorKind,
		FencingToken:     opts.FencingToken,
		SourceConfidence: string(fact.SourceConfidence),
		ObservedAt:       fact.ObservedAt.UTC(),
		Payload:          fact.Payload,
		IsTombstone:      fact.Tombstone,
		SourceRef: facts.Ref{
			SourceSystem:   fact.SourceRef.SourceSystem,
			ScopeID:        fact.SourceRef.ScopeID,
			GenerationID:   fact.SourceRef.GenerationID,
			FactKey:        fact.SourceRef.FactKey,
			SourceURI:      fact.SourceRef.URI,
			SourceRecordID: fact.SourceRef.RecordID,
		},
	}
	return envelope.Clone()
}

// FactSchemaFromInternal maps a durable internal envelope into the contracts
// module decode envelope.
func FactSchemaFromInternal(env facts.Envelope) factschema.Envelope {
	schemaVersion := env.SchemaVersion
	if schemaVersion == "" || schemaVersion == PersistedVersionlessSchemaVersion {
		schemaVersion = DefaultSchemaMajorVersion
	}
	return factschema.Envelope{
		FactKind:         env.FactKind,
		SchemaVersion:    schemaVersion,
		StableFactKey:    env.StableFactKey,
		ScopeID:          env.ScopeID,
		GenerationID:     env.GenerationID,
		CollectorKind:    env.CollectorKind,
		SourceConfidence: env.SourceConfidence,
		ObservedAt:       env.ObservedAt,
		IsTombstone:      env.IsTombstone,
		SourceRef:        sourceRefString(env.SourceRef),
		Payload:          env.Payload,
	}
}

func sourceRefString(ref facts.Ref) string {
	if ref.SourceURI != "" {
		return ref.SourceURI
	}
	if ref.SourceRecordID != "" {
		return ref.SourceRecordID
	}
	return ref.FactKey
}
`)
	formatted, err := format.Source(source)
	if err != nil {
		return nil, fmt.Errorf("format generated adapter: %w", err)
	}
	return formatted, nil
}

func verifyFile(path string, want []byte) error {
	got, err := os.ReadFile(path) // #nosec G304 -- path is a repo-local generated artifact.
	if err != nil {
		return fmt.Errorf("read generated adapter %s: %w", path, err)
	}
	if !bytes.Equal(got, want) {
		return fmt.Errorf("generated adapter %s is stale; run go generate ./internal/factenvelope", path)
	}
	return nil
}

func writeFile(path string, contents []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil { // #nosec G301 -- repo-local generated artifact directory.
		return fmt.Errorf("create generated adapter directory %s: %w", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, contents, 0o644); err != nil { // #nosec G306 -- generated source artifact.
		return fmt.Errorf("write generated adapter %s: %w", path, err)
	}
	return nil
}
