// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRenderAdapterContainsGeneratedMappingContract(t *testing.T) {
	t.Parallel()

	generated, err := renderAdapter()
	if err != nil {
		t.Fatalf("renderAdapter() error = %v", err)
	}
	text := string(generated)
	for _, want := range []string{
		"Code generated by go/cmd/fact-envelope-adapter",
		"type InternalEnvelopeOptions struct",
		"func InternalFromSDKFact",
		"func FactSchemaFromInternal",
		"PersistedVersionlessSchemaVersion",
		"SourceURI:      fact.SourceRef.URI",
	} {
		if !strings.Contains(text, want) {
			t.Fatalf("generated adapter missing %q", want)
		}
	}
}

func TestGeneratedAdapterArtifactIsCurrent(t *testing.T) {
	t.Parallel()

	generated, err := renderAdapter()
	if err != nil {
		t.Fatalf("renderAdapter() error = %v", err)
	}
	path := filepath.Join("..", "..", "internal", "factenvelope", "adapter_generated.go")
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read generated adapter: %v", err)
	}
	if !bytes.Equal(got, generated) {
		t.Fatal("adapter_generated.go is stale; run go generate ./internal/factenvelope")
	}
}
