// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package admin

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"strings"
)

// ReindexInput carries the operator-supplied selectors for Reindex.
type ReindexInput struct {
	// Ingester names the ingester type to reindex.
	Ingester string
	// Scope names the reindex scope.
	Scope string
	// Force requests a reindex even when the ingester considers the scope
	// already current.
	Force bool
}

// Reindex queues a reindex request for the ingester and returns the decoded
// response body. Every field of in is sent, including a false Force and any
// empty string, because the endpoint's defaults are the CLI's flag defaults.
func Reindex(client Client, in ReindexInput) (any, error) {
	var result any
	err := client.Post("/api/v0/admin/reindex", map[string]any{
		"ingester": in.Ingester,
		"scope":    in.Scope,
		"force":    in.Force,
	}, &result)
	if err != nil {
		return nil, err //nolint:wrapcheck // Client's error is already the operator's message; cmd/eshu prints it verbatim and wrapping would prepend a second prefix.
	}
	return result, nil
}

// TuningReport returns the decoded shared-projection tuning report.
func TuningReport(client Client) (any, error) {
	var result any
	if err := client.Get("/api/v0/admin/shared-projection/tuning-report", &result); err != nil {
		return nil, err //nolint:wrapcheck // Client's error is already the operator's message; cmd/eshu prints it verbatim and wrapping would prepend a second prefix.
	}
	return result, nil
}

// ListWorkItemsInput carries the optional filters for ListWorkItems. Every
// string field is omitted from the request body when empty, so an unset
// filter never narrows the query.
type ListWorkItemsInput struct {
	Status       string
	RepositoryID string
	SourceRunID  string
	// Limit is always sent, including zero.
	Limit int
}

// ListWorkItems returns the decoded fact work-item query response.
func ListWorkItems(client Client, in ListWorkItemsInput) (any, error) {
	body := map[string]any{"limit": in.Limit}
	if in.Status != "" {
		body["status"] = in.Status
	}
	if in.RepositoryID != "" {
		body["repository_id"] = in.RepositoryID
	}
	if in.SourceRunID != "" {
		body["source_run_id"] = in.SourceRunID
	}
	var result any
	if err := client.Post("/api/v0/admin/work-items/query", body, &result); err != nil {
		return nil, err //nolint:wrapcheck // Client's error is already the operator's message; cmd/eshu prints it verbatim and wrapping would prepend a second prefix.
	}
	return result, nil
}

// ListDecisionsInput carries the optional filters for ListDecisions. Empty
// string fields are omitted from the request body; Limit is always sent.
type ListDecisionsInput struct {
	RepositoryID string
	SourceRunID  string
	Limit        int
}

// ListDecisions returns the decoded projection-decision query response.
func ListDecisions(client Client, in ListDecisionsInput) (any, error) {
	body := map[string]any{"limit": in.Limit}
	if in.RepositoryID != "" {
		body["repository_id"] = in.RepositoryID
	}
	if in.SourceRunID != "" {
		body["source_run_id"] = in.SourceRunID
	}
	var result any
	if err := client.Post("/api/v0/admin/decisions/query", body, &result); err != nil {
		return nil, err //nolint:wrapcheck // Client's error is already the operator's message; cmd/eshu prints it verbatim and wrapping would prepend a second prefix.
	}
	return result, nil
}

// ReplayInput carries the selectors and the operator's justification for
// Replay. Reason is mandatory; IdempotencyKey is generated when blank.
type ReplayInput struct {
	WorkItemID   string
	ScopeID      string
	Stage        string
	FailureClass string
	// Reason must be non-blank: Replay rejects the request before any HTTP
	// call otherwise.
	Reason string
	// IdempotencyKey is generated by newReplayIdempotencyKey when blank.
	IdempotencyKey string
	// Force and Limit are always sent, including their zero values.
	Force bool
	Limit int
}

// Replay moves failed work items back to pending and returns the decoded
// response body. It refuses a blank Reason and generates an idempotency key
// when the caller supplies none, so a retried invocation stays safe.
//
// The blank-Reason error names the `--reason` CLI flag rather than the
// struct field, because that message reaches an operator running
// `eshu admin facts replay` and naming the field would not tell them what
// to type.
func Replay(client Client, in ReplayInput) (any, error) {
	if strings.TrimSpace(in.Reason) == "" {
		return nil, fmt.Errorf("--reason is required and must explain why the replay is safe")
	}
	idempotencyKey := in.IdempotencyKey
	if strings.TrimSpace(idempotencyKey) == "" {
		generated, err := newReplayIdempotencyKey()
		if err != nil {
			return nil, err
		}
		idempotencyKey = generated
	}

	body := map[string]any{
		"limit":           in.Limit,
		"reason":          in.Reason,
		"idempotency_key": idempotencyKey,
		"force":           in.Force,
	}
	if in.WorkItemID != "" {
		body["work_item_ids"] = []string{in.WorkItemID}
	}
	if in.ScopeID != "" {
		body["scope_id"] = in.ScopeID
	}
	if in.Stage != "" {
		body["stage"] = in.Stage
	}
	if in.FailureClass != "" {
		body["failure_class"] = in.FailureClass
	}
	var result any
	if err := client.Post("/api/v0/admin/replay", body, &result); err != nil {
		return nil, err //nolint:wrapcheck // Client's error is already the operator's message; cmd/eshu prints it verbatim and wrapping would prepend a second prefix.
	}
	return result, nil
}

// newReplayIdempotencyKey returns a random key so repeated CLI invocations do
// not accidentally collide while a single invocation stays retry-safe.
func newReplayIdempotencyKey() (string, error) {
	buf := make([]byte, 16)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("generate idempotency key: %w", err)
	}
	return "cli-replay-" + hex.EncodeToString(buf), nil
}

// DeadLetterInput carries the selectors for DeadLetter. Every field is
// omitted from the request body when empty.
type DeadLetterInput struct {
	WorkItemID   string
	RepositoryID string
	Note         string
}

// DeadLetter moves work items to a terminal failed state and returns the
// decoded response body.
func DeadLetter(client Client, in DeadLetterInput) (any, error) {
	body := map[string]any{}
	if in.WorkItemID != "" {
		body["work_item_id"] = in.WorkItemID
	}
	if in.RepositoryID != "" {
		body["repository_id"] = in.RepositoryID
	}
	if in.Note != "" {
		body["note"] = in.Note
	}
	var result any
	if err := client.Post("/api/v0/admin/dead-letter", body, &result); err != nil {
		return nil, err //nolint:wrapcheck // Client's error is already the operator's message; cmd/eshu prints it verbatim and wrapping would prepend a second prefix.
	}
	return result, nil
}

// SkipInput carries the selectors for Skip. Every field is omitted from the
// request body when empty.
type SkipInput struct {
	WorkItemID string
	Note       string
}

// Skip skips work items and returns the decoded response body.
func Skip(client Client, in SkipInput) (any, error) {
	body := map[string]any{}
	if in.WorkItemID != "" {
		body["work_item_id"] = in.WorkItemID
	}
	if in.Note != "" {
		body["note"] = in.Note
	}
	var result any
	if err := client.Post("/api/v0/admin/skip", body, &result); err != nil {
		return nil, err //nolint:wrapcheck // Client's error is already the operator's message; cmd/eshu prints it verbatim and wrapping would prepend a second prefix.
	}
	return result, nil
}

// BackfillInput carries the selectors for Backfill. Every field is omitted
// from the request body when empty.
type BackfillInput struct {
	RepositoryID string
	SourceRunID  string
}

// Backfill creates a fact backfill request and returns the decoded response
// body.
func Backfill(client Client, in BackfillInput) (any, error) {
	body := map[string]any{}
	if in.RepositoryID != "" {
		body["repository_id"] = in.RepositoryID
	}
	if in.SourceRunID != "" {
		body["source_run_id"] = in.SourceRunID
	}
	var result any
	if err := client.Post("/api/v0/admin/backfill", body, &result); err != nil {
		return nil, err //nolint:wrapcheck // Client's error is already the operator's message; cmd/eshu prints it verbatim and wrapping would prepend a second prefix.
	}
	return result, nil
}

// ListReplayEvents returns the decoded replay audit-event query response.
// limit is always sent, including zero.
func ListReplayEvents(client Client, limit int) (any, error) {
	var result any
	if err := client.Post("/api/v0/admin/replay-events/query", map[string]any{"limit": limit}, &result); err != nil {
		return nil, err //nolint:wrapcheck // Client's error is already the operator's message; cmd/eshu prints it verbatim and wrapping would prepend a second prefix.
	}
	return result, nil
}
