// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package main

import (
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"

	gcpsynth "github.com/eshu-hq/eshu/go/internal/synth/gcp"
)

// synthCassetteDefaultProjects and synthCassetteDefaultResources are
// "ifa synth-cassette"'s -projects/-resources defaults: a small, fast corpus
// (4 scopes x 16 resources) suitable for a quick local check. Callers that
// need genuinely varying worker concurrency (the Ifá P3 determinism matrix,
// scripts/verify-ifa-determinism.sh) pass larger explicit values.
const (
	synthCassetteDefaultProjects  = 4
	synthCassetteDefaultResources = 16
)

// synthCassetteOptions holds the parsed command-line inputs for one
// "ifa synth-cassette" run.
type synthCassetteOptions struct {
	seed      uint64
	projects  int
	resources int
	out       string
}

func parseSynthCassetteFlags(args []string, stderr io.Writer) (synthCassetteOptions, error) {
	fs := flag.NewFlagSet("ifa synth-cassette", flag.ContinueOnError)
	fs.SetOutput(stderr)
	var o synthCassetteOptions
	fs.Uint64Var(&o.seed, "seed", 0, "deterministic PRNG seed (required)")
	fs.IntVar(&o.projects, "projects", synthCassetteDefaultProjects, "number K of independent GCP project scopes to generate")
	fs.IntVar(&o.resources, "resources", synthCassetteDefaultResources, "number of gcp_cloud_resource facts to generate per scope")
	fs.StringVar(&o.out, "out", "", "path to write the generated cassette JSON file (required)")
	if err := fs.Parse(args); err != nil {
		return synthCassetteOptions{}, err //nolint:wrapcheck // flag errors are self-describing.
	}
	if o.out == "" {
		return synthCassetteOptions{}, errors.New("ifa synth-cassette: -out is required")
	}
	return o, nil
}

// runSynthCassetteCommand implements `ifa synth-cassette`: the Ifá P3
// determinism-matrix multi-scope fixture generator (issue #4396 slice 6b).
// It calls the pure, credential-free go/internal/synth/gcp.GenerateMultiScope
// with -seed/-projects/-resources and writes the resulting canonical cassette
// bytes to -out — a NEW file this verb creates, never a committed testdata
// path (no synth-cassette output is ever checked into the repo; every caller
// regenerates it into a scratch/work directory per run).
//
// This verb performs no I/O beyond writing -out: it opens no database or
// graph backend and reads no cassette from disk, matching
// "ifa mutate-cassette"'s pure disk-and-memory footprint (this verb writes
// but never reads a cassette, since it generates one from scratch).
func runSynthCassetteCommand(args []string, stdout, stderr io.Writer) error {
	o, err := parseSynthCassetteFlags(args, stderr)
	if err != nil {
		return err
	}

	out, err := gcpsynth.GenerateMultiScope(gcpsynth.MultiScopeOptions{
		Seed:          o.seed,
		Scopes:        o.projects,
		ResourceCount: o.resources,
	})
	if err != nil {
		return fmt.Errorf("ifa synth-cassette: generate: %w", err)
	}

	// #nosec G306 -- a scratch cassette fixture, not a secret; world-readable
	// is fine and matches "ifa mutate-cassette"'s own generated-fixture
	// permissions.
	if err := os.WriteFile(o.out, out, 0o644); err != nil {
		return fmt.Errorf("ifa synth-cassette: write %s: %w", o.out, err)
	}

	return printSynthCassetteReport(stdout, o, out)
}

// synthCassetteReport is the JSON-decoded shape printSynthCassetteReport reads
// back from the generated bytes just to report scope/fact counts; it is not
// the cassette.File type itself so this file does not need to import the
// cassette package only to print a summary line.
type synthCassetteReport struct {
	Scopes []struct {
		ScopeID string `json:"scope_id"`
		Facts   []any  `json:"facts"`
	} `json:"scopes"`
}

// printSynthCassetteReport renders one human-readable summary line naming how
// many scopes and total facts were generated, so a caller (or a proof script)
// can sanity-check the output without re-parsing -out itself.
func printSynthCassetteReport(w io.Writer, o synthCassetteOptions, raw []byte) error {
	var report synthCassetteReport
	if err := json.Unmarshal(raw, &report); err != nil {
		return fmt.Errorf("ifa synth-cassette: decode generated cassette for report: %w", err)
	}
	totalFacts := 0
	for _, scope := range report.Scopes {
		totalFacts += len(scope.Facts)
	}
	_, err := fmt.Fprintf(w, "ifa synth-cassette: seed=%d projects=%d resources=%d out=%s scopes=%d facts=%d\n",
		o.seed, o.projects, o.resources, o.out, len(report.Scopes), totalFacts)
	if err != nil {
		return fmt.Errorf("ifa synth-cassette: write report: %w", err)
	}
	return nil
}
