#!/usr/bin/env bash
# shellcheck disable=SC2154  # Sourced helper; `fail` is parent-owned.
# The one definition of what "private data" means to the Ifá gate mirrors, and
# the positive control that proves it still detects anything.
#
# WHY THIS EXISTS (#6161/#6195). Both mirrors scan the gate script, every
# declared *_lib, the family registry, its rows and its pins for home-directory
# paths, cloud keys, tokens and account ids. #6195 pinned the FLOOR on how many
# files get scanned, and #6173 pinned the glob block that feeds it. Neither
# pinned the one thing the scan actually asserts. Replacing the pattern with
# anything that cannot match left both mirrors at exit 0, still printing
# `private-data scan: 57 file(s) scanned` -- a check that keeps running and
# always passes, which is the worst shape a guard can take.
#
# The pattern was also duplicated verbatim in the two scan modules, so a fix to
# one silently left the other behind. It lives here now, and the ONLY way to get
# it is through ifa_private_data_pattern, which runs the positive control first.
# A caller that skips the control does not get a pattern at all.
#
# WHY THE SAMPLES LOOK LIKE THAT. This file is itself one of the files the scan
# covers. Spelling any of these tokens plainly here would make the scanner flag
# its own positive control on every run, so each sample is assembled from two
# adjacent quoted strings: the runtime VALUE is the real token, the SOURCE line
# is not. The pattern brackets one character per alternative for the same
# reason, and a bracketed single-character class matches exactly the text the
# bare character does.
#
# The samples are HAND-WRITTEN, one per alternative, and deliberately not
# derived from the pattern. A sample generated by un-bracketing the pattern
# tracks whatever the pattern happens to say, so renaming an alternative would
# rename its own control and prove nothing -- the same "measures itself" defect
# the exact-count pins exist to avoid.
#
# WHAT THIS DOES NOT CATCH, stated plainly: a sample REPLACED by a copy of
# another sample keeps the count at 14 and keeps every assertion passing, while
# the alternative it used to cover goes unguarded. The count catches deletion,
# not substitution. Closing that means the control deciding which alternative
# each sample belongs to, which is the derivation this file exists to avoid.

# ifa_private_data_pattern proves the pattern still detects one planted token per
# alternative, then assigns it to the caller's variable named by $1. It assigns
# rather than prints on purpose: returned through a command substitution, a
# `fail` inside here would exit only the subshell and the caller would scan on
# with an empty pattern -- fail-open, in the guard against fail-open.
ifa_private_data_pattern() {
	local -n _ifa_pdp_out="$1"
	local pattern sample probe_dir rc
	pattern='gh[p]_|github_pa[t]_|glpa[t]-|AKI[A]|ASI[A]|xo[x][baprs]-|arn:aw[s]:|(^|[^0-9])[0-9]{12}([^0-9]|$)|/[U]sers/|/[h]ome/[a-z]'
	local -a samples=(
		'gh''p_examplevalue'
		'github_pa''t_examplevalue'
		'glpa''t-examplevalue'
		'AKI''AIOSFODNN7EXAMPLE'
		'ASI''AIOSFODNN7EXAMPLE'
		'xo''xb-example'
		'xo''xa-example'
		'xo''xp-example'
		'xo''xr-example'
		'xo''xs-example'
		'arn:aw''s:iam::example:role/example'
		'account 1234''56789012 end'
		'/U''sers/example/path'
		'/h''ome/example/path'
	)
	# Hand-counted, deliberately not derived from the pattern: one sample per
	# alternative plus one per xo* sub-class. Adding an alternative means adding
	# its sample and bumping this number, and that is the point -- a control
	# whose size is read out of the thing it checks cannot notice a gap.
	[[ "${#samples[@]}" -eq 14 ]] \
		|| fail "private-data positive control carries ${#samples[@]} sample(s), expected 14 -- a sample was added or removed without re-checking it against the pattern's alternatives"
	probe_dir="$(mktemp -d -t ifa-private-data-probe.XXXXXX)"
	for sample in "${samples[@]}"; do
		printf '%s\n' "${sample}" >"${probe_dir}/sample.txt"
		# rc is captured rather than tested through `if`, for the same reason the
		# scan itself does it: an uncompilable pattern exits 2, and an `if` reads
		# that as "no match".
		rc=0
		rg --pcre2 --quiet -- "${pattern}" "${probe_dir}/sample.txt" || rc=$?
		[[ "${rc}" -eq 0 ]] || {
			rm -rf "${probe_dir}"
			fail "private-data pattern no longer detects a planted ${sample} (rg exit ${rc}); an alternative was removed, renamed, or made uncompilable, and the scan would report every file clean"
		}
	done
	rm -rf "${probe_dir}"
	_ifa_pdp_out="${pattern}"
}
