#!/usr/bin/env python3
"""Render Eshu's small native agent bindings from one role declaration."""

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path


ROOT = Path(os.environ.get("ESHU_AGENT_ROLES_REPO_ROOT", Path(__file__).resolve().parent.parent)).resolve()
SOURCE = ROOT / ".agents" / "roles.json"


def load_roles():
    data = json.loads(SOURCE.read_text())
    if data.get("version") != 1:
        raise ValueError("unsupported role manifest version")
    raw = data["roles"]
    resolved = {}

    def resolve(name, trail=()):
        if name in resolved:
            return resolved[name]
        if name in trail:
            raise ValueError("role inheritance cycle: " + " -> ".join(trail + (name,)))
        spec = dict(raw[name])
        base = spec.pop("base", None)
        if base:
            spec = {**resolve(base, trail + (name,)), **spec}
        if spec["tier"] not in data["models"]["codex"]:
            raise ValueError("unknown model tier for " + name)
        if spec["access"] not in ("read", "write"):
            raise ValueError("unknown access for " + name)
        skill = spec.get("skill")
        if skill and not (ROOT / ".agents" / "skills" / skill / "SKILL.md").is_file():
            raise ValueError("missing core skill for " + name + ": " + skill)
        resolved[name] = spec
        return spec

    for name in raw:
        resolve(name)
    return data["models"], resolved


def instructions(spec):
    lines = [
        "Follow the applicable Eshu root instructions. You are a leaf agent: do not dispatch other agents.",
    ]
    if spec.get("skill"):
        lines.append("Load the " + spec["skill"] + " skill and follow it.")
    if spec["access"] == "read":
        lines.append("Do not edit source files, change branches, or publish changes.")
        lines.append("If a required command is blocked, request its exact output from the coordinator; never infer a pass.")
    lines.append(spec["instructions"])
    return "\n".join(lines)


def render_codex(name, spec, model):
    lines = [
        "# Generated by scripts/agent-roles.py from .agents/roles.json; do not edit.",
        "name = " + json.dumps(name),
        "description = " + json.dumps(spec["description"]),
        "model = " + json.dumps(model["model"]),
        "model_reasoning_effort = " + json.dumps(model["effort"]),
    ]
    if spec["access"] == "read":
        lines += ["sandbox_mode = \"read-only\"", "approval_policy = \"on-request\""]
    lines += ["developer_instructions = " + json.dumps(instructions(spec))]
    return "\n".join(lines) + "\n"


def render_claude(name, spec, model):
    lines = [
        "---",
        "name: " + name,
        "description: " + json.dumps(spec["description"]),
    ]
    if spec["access"] == "read":
        lines.append("tools: Read, Glob, Grep, Bash, WebFetch, Skill")
    if spec.get("skill"):
        lines.append("skills: " + spec["skill"])
    lines += [
        "model: " + model["model"],
        "effort: " + model["effort"],
        "---",
        "",
        "<!-- Generated by scripts/agent-roles.py from .agents/roles.json; do not edit. -->",
        "",
        instructions(spec),
    ]
    return "\n".join(lines) + "\n"


def opencode_frontmatter(spec):
    edit = "allow" if spec["access"] == "write" else "deny"
    shell = "allow" if spec["access"] == "write" else "deny"
    return (
        "---\n"
        + "description: " + json.dumps(spec["description"]) + "\n"
        + "mode: all\npermission:\n"
        + "  edit: " + edit + "\n"
        + "  write: " + edit + "\n"
        + "  bash: " + shell + "\n"
        + "  task:\n    \"*\": deny\n"
        + "---\n"
    )


def render_opencode(spec):
    prefix = opencode_frontmatter(spec)
    return (
        prefix
        + "\n<!-- Generated by scripts/agent-roles.py from .agents/roles.json; do not edit. -->\n\n"
        + instructions(spec)
        + "\n"
    )


def bindings(models, roles):
    for name, spec in roles.items():
        tier = spec["tier"]
        yield ROOT / ".codex" / "agents" / (name + ".toml"), render_codex(
            name, spec, models["codex"][tier]
        )
        yield ROOT / ".claude" / "agents" / (name + ".md"), render_claude(
            name, spec, models["claude"][tier]
        )
        target = ROOT / ".opencode" / "agent" / (name + ".md")
        yield target, render_opencode(spec)


def generate_or_check(check):
    models, roles = load_roles()
    stale = []
    for path, expected in bindings(models, roles):
        actual = path.read_text() if path.exists() else None
        if actual == expected:
            continue
        if check:
            stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected)
            print("wrote", path.relative_to(ROOT))
    if stale:
        print("agent-roles: stale or missing bindings:", file=sys.stderr)
        for path in stale:
            print("  " + str(path), file=sys.stderr)
        return 1
    print("agent-roles: bindings " + ("match" if check else "generated from") + " .agents/roles.json")
    return 0


def muse_exec(role, task, dry_run):
    models, roles = load_roles()
    spec = roles[role]
    model = models["muse"][spec["tier"]]
    argv = [
        "muse", "exec", "--model", model["model"],
        "--reasoning-effort", model["effort"],
        "--workspace", str(ROOT), "--trust-workspace",
    ]
    if spec["access"] == "read":
        argv += ["--permission-profile", ":read-only"]
    prompt = "Act as the " + role + " role.\n" + instructions(spec) + "\n\nTask:\n" + task
    argv.append(prompt)
    if dry_run:
        print(json.dumps({"argv": argv[:-1], "prompt": prompt}, indent=2))
        return 0
    return subprocess.run(argv, cwd=ROOT, check=False).returncode


def codex_exec(role, task, dry_run):
    models, roles = load_roles()
    spec = roles[role]
    model = models["codex"][spec["tier"]]
    argv = [
        "codex", "exec", "--model", model["model"],
        "--config", "model_reasoning_effort=" + json.dumps(model["effort"]),
        "--sandbox", "read-only" if spec["access"] == "read" else "workspace-write",
        "--cd", str(ROOT),
    ]
    prompt = "Act as the " + role + " role.\n" + instructions(spec) + "\n\nTask:\n" + task
    argv.append(prompt)
    if dry_run:
        print(json.dumps({"argv": argv[:-1], "prompt": prompt}, indent=2))
        return 0
    return subprocess.run(argv, cwd=ROOT, check=False).returncode


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    commands.add_parser("generate")
    commands.add_parser("check")
    muse = commands.add_parser("muse-exec")
    muse.add_argument("role")
    muse.add_argument("task")
    muse.add_argument("--dry-run", action="store_true")
    codex = commands.add_parser("codex-exec")
    codex.add_argument("role")
    codex.add_argument("task")
    codex.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    if args.command == "generate":
        return generate_or_check(False)
    if args.command == "check":
        return generate_or_check(True)
    _, roles = load_roles()
    if args.role not in roles:
        parser.error("unknown role: " + args.role)
    if args.command == "muse-exec":
        return muse_exec(args.role, args.task, args.dry_run)
    return codex_exec(args.role, args.task, args.dry_run)


if __name__ == "__main__":
    sys.exit(main())
