#!/usr/bin/env bash
# generate-dirgate-grandfather-go.sh - regenerate
# tools/golangci-lint-dirgate/grandfather.go from
# scripts/lib/dirgate-grandfather.tsv (the cap ledger) joined with
# scripts/lib/dirgate-naming-exempt.tsv (the per-file naming-exemption
# ledger), the two sources of truth for the dirgate gate's grandfather
# ledger (issue #6054). To change a directory's pinned cap entry or a
# file's naming exemption, edit the relevant TSV, re-run this script, and
# commit the regenerated .go file -- never hand-edit grandfather.go itself.
#
# The test mirror scripts/test-generate-dirgate-grandfather-go.sh asserts
# the committed .go file is byte-identical to a fresh run (idempotency /
# drift) and that every TSV row has a corresponding Go map entry.
#
# Usage: scripts/generate-dirgate-grandfather-go.sh
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tsv="${DIRGATE_GRANDFATHER_TSV_INPUT:-${repo_root}/scripts/lib/dirgate-grandfather.tsv}"
naming_tsv="${DIRGATE_NAMING_EXEMPT_TSV_INPUT:-${repo_root}/scripts/lib/dirgate-naming-exempt.tsv}"
out="${DIRGATE_GRANDFATHER_GO_OUTPUT:-${repo_root}/tools/golangci-lint-dirgate/grandfather.go}"

[[ -f "${tsv}" ]] || { echo "generate-dirgate-grandfather-go: missing ${tsv}" >&2; exit 1; }
[[ -f "${naming_tsv}" ]] || { echo "generate-dirgate-grandfather-go: missing ${naming_tsv}" >&2; exit 1; }

# Fail BEFORE writing anything: every naming-exempt row's directory must
# already have a cap-ledger row. This is a static join-integrity check
# (data vs. data, no live tree needed); the separate freshness check --
# does the pinned file still exist and still violate naming -- is a gate
# concern, not a generation concern, and lives in
# dirgate_verify_naming_exempt_ledger (scripts/lib/dirgate-core.sh),
# exercised by `scripts/verify-dirgate.sh --all`.
join_errors="$(awk -F'\t' -v cap_tsv="${tsv}" '
	BEGIN {
		while ((getline line < cap_tsv) > 0) {
			if (line ~ /^#/ || line == "") continue
			split(line, f, "\t")
			if (f[1] != "") known[f[1]] = 1
		}
		close(cap_tsv)
	}
	/^#/ || NF != 2 || $1 == "" || $2 == "" { next }
	!($1 in known) { printf "%s\t%s\n", $1, $2 }
' "${naming_tsv}")"
if [[ -n "${join_errors}" ]]; then
	echo "generate-dirgate-grandfather-go: naming-exempt row(s) with no matching dirgate-grandfather.tsv directory:" >&2
	printf '%s\n' "${join_errors}" >&2
	exit 1
fi

{
	# SPDX and Copyright MUST be lines 1-2: scripts/verify-license-header.sh
	# is a blocking gate that reads exactly those two lines, and every other
	# generated .go file in this repo orders them the same way.
	printf '// SPDX-License-Identifier: MIT\n'
	printf '// Copyright (c) 2025-2026 eshu-hq\n'
	printf '//\n'
	printf '// Code generated by scripts/generate-dirgate-grandfather-go.sh from\n'
	printf '// scripts/lib/dirgate-grandfather.tsv and\n'
	printf '// scripts/lib/dirgate-naming-exempt.tsv; DO NOT EDIT BY HAND.\n'
	printf '\n'
	printf 'package main\n'
	printf '\n'
	printf '// grandfatheredDirectories is the digest-pinned ledger of package\n'
	printf '// directories that already exceeded the 40-non-test-.go-file cap when the\n'
	printf '// dirgate gate landed (issue #6054), so the gate lands green on today'"'"'s\n'
	printf '// tree instead of failing on the entire pre-existing sprawl it exists to\n'
	printf '// stop from growing further, merged with the per-file naming exemptions\n'
	printf '// pinned for the same directories. See grandfatherEntry and\n'
	printf '// evaluateCapViolation for the exact pass/fail rule FileCount/Digest are\n'
	printf '// checked with, namingExemptSet for how NamingExempt is checked, and\n'
	printf '// scripts/lib/dirgate-grandfather.tsv plus\n'
	printf '// scripts/lib/dirgate-naming-exempt.tsv for the sources of truth this map\n'
	printf '// is generated from -- edit those TSVs, then re-run\n'
	printf '// scripts/generate-dirgate-grandfather-go.sh, never this file directly.\n'
	printf 'var grandfatheredDirectories = map[string]grandfatherEntry{\n'

	# Emit rows sorted by dir key (column 1), skipping comments/blank lines,
	# joining in each directory's naming-exempt files (if any) from
	# naming_tsv. gofumpt aligns the struct literals' column widths on
	# `go fmt`; this generator does not attempt to match that alignment
	# byte-for-byte, so `gofumpt -l` (run by the go-fmt gate) is what keeps
	# the emitted file formatter-clean -- run it as part of this script so
	# the committed output never depends on a separate manual gofmt pass.
	awk -F'\t' -v naming_tsv="${naming_tsv}" '
		BEGIN {
			while ((getline line < naming_tsv) > 0) {
				if (line ~ /^#/ || line == "") continue
				split(line, f, "\t")
				d = f[1]; file = f[2]
				if (d == "" || file == "") continue
				n = ++count[d]
				exempt[d, n] = file
			}
			close(naming_tsv)
		}
		/^#/ || NF != 3 { next }
		{
			entry = sprintf("FileCount: %s, Digest: \"%s\"", $2, $3)
			if ($1 in count) {
				list = ""
				for (i = 1; i <= count[$1]; i++) {
					if (i > 1) list = list ", "
					list = list "\"" exempt[$1, i] "\""
				}
				entry = entry sprintf(", NamingExempt: []string{%s}", list)
			}
			printf "\t\"%s\": {%s},\n", $1, entry
		}
	' "${tsv}" | LC_ALL=C sort

	printf '}\n'
} > "${out}"

if command -v gofmt >/dev/null 2>&1; then
	gofmt -w "${out}"
fi

echo "generate-dirgate-grandfather-go: wrote ${out}"
