#!/usr/bin/env bash
# Generate the public Go code-coverage report and shields endpoint JSON.
# This is ordinary code test coverage, not replay, golden-corpus, or full-corpus
# proof. By default it runs `go test ./...` with a coverage profile; tests may
# pass ESHU_CODE_COVERAGE_RUN_TESTS=0 plus ESHU_CODE_COVERAGE_PROFILE_IN to
# render from a fixture profile.
set -euo pipefail

repo_root="${ESHU_CODE_COVERAGE_REPO_ROOT:-}"
if [[ -z "${repo_root}" ]]; then
	repo_root="$(git -C "$(dirname "$0")" rev-parse --show-toplevel 2>/dev/null \
		|| (cd "$(dirname "$0")/.." && pwd))"
fi

profile_in="${ESHU_CODE_COVERAGE_PROFILE_IN:-}"
profile_out="${ESHU_CODE_COVERAGE_PROFILE_OUT:-${repo_root}/go-code-coverage.out}"
report_out="${ESHU_CODE_COVERAGE_REPORT_OUT:-${repo_root}/docs/public/reference/code-coverage.md}"
shield_out="${ESHU_CODE_COVERAGE_SHIELD_OUT:-${repo_root}/docs/public/reference/code-coverage-shield.json}"
run_tests="${ESHU_CODE_COVERAGE_RUN_TESTS:-1}"

tmp_root="$(mktemp -d)"
trap 'rm -rf "${tmp_root}"' EXIT

profile="${profile_in:-${profile_out}}"
if [[ "${run_tests}" != "0" ]]; then
	(cd "${repo_root}/go" && go test ./... -covermode=count -coverprofile="${profile}")
elif [[ -z "${profile_in}" ]]; then
	printf 'generate-code-coverage-report: ESHU_CODE_COVERAGE_PROFILE_IN is required when ESHU_CODE_COVERAGE_RUN_TESTS=0\n' >&2
	exit 2
fi

summary_tsv="${tmp_root}/summary.tsv"

LC_ALL=C awk '
function excluded(path) {
	return path ~ /\/testdata\// ||
		path ~ /\/fixtures?\// ||
		path ~ /\/mocks?\// ||
		path ~ /\/vendor\// ||
		path ~ /\/docs\/site\// ||
		path ~ /\.pb\.go$/ ||
		path ~ /\.gen\.go$/ ||
		path ~ /zz_generated/
}
NR == 1 { next }
{
	colon = index($0, ":")
	if (colon == 0) {
		next
	}
	file = substr($0, 1, colon - 1)
	rest = substr($0, colon + 1)
	split(rest, fields, " ")
	statements = fields[2] + 0
	count = fields[3] + 0
	if (statements <= 0) {
		next
	}
	if (excluded(file)) {
		excluded_files[file] = 1
		excluded_statements += statements
		next
	}
	pkg = file
	sub("/[^/]+$", "", pkg)
	total[pkg] += statements
	if (count > 0) {
		covered[pkg] += statements
	}
	included_files[file] = 1
}
END {
	for (pkg in total) {
		pct = total[pkg] == 0 ? 0 : (covered[pkg] * 100 / total[pkg])
		printf "%s\t%d\t%d\t%.1f\n", pkg, total[pkg], covered[pkg], pct
		all_total += total[pkg]
		all_covered += covered[pkg]
	}
	included_count = 0
	for (file in included_files) {
		included_count++
	}
	excluded_count = 0
	for (file in excluded_files) {
		excluded_count++
	}
	all_pct = all_total == 0 ? 0 : (all_covered * 100 / all_total)
	printf "total\t%d\t%d\t%.1f\t%d\t%d\t%d\n", all_total, all_covered, all_pct, included_count, excluded_count, excluded_statements > "/dev/stderr"
}' "${profile}" >/dev/null 2>"${summary_tsv}"

read -r _ _total_statements _covered_statements total_pct included_files excluded_files excluded_statements <"${summary_tsv}"

canonical_pct="$(LC_ALL=C awk -v covered="${_covered_statements}" -v total="${_total_statements}" '
BEGIN {
	if (total <= 0) {
		print 0
		exit
	}
	printf "%d", covered * 100 / total
}
')"

color="red"
if awk "BEGIN { exit !(${canonical_pct} >= 70) }"; then
	color="yellow"
fi
if awk "BEGIN { exit !(${canonical_pct} >= 80) }"; then
	color="green"
fi

mkdir -p "$(dirname "${report_out}")" "$(dirname "${shield_out}")"
cat >"${shield_out}" <<EOF
{"schemaVersion":1,"label":"go coverage","message":"${canonical_pct}%","color":"${color}"}
EOF

{
	printf '# Code Coverage\n\n'
	printf '<!-- GENERATED by generate-code-coverage-report; do not edit by hand. -->\n\n'
	printf 'Total Go code coverage: **%s%%**.\n\n' "${canonical_pct}"
	printf 'This report is ordinary executable Go test coverage. It is one signal, not a replacement for replay, golden-corpus, or full-corpus proof.\n\n'
	printf '## Source Of Truth\n\n'
	printf '%s\n' '- Scope: Go package coverage from `go test ./... -covermode=count`.'
	printf '%s\n' '- Reproducibility: the checked-in summary conservatively floors the repository percentage to a whole percent. Exact covered-statement counts remain available in the uploaded raw profile, and the workflow log retains the one-decimal percentage, because equivalent passing concurrency tests can execute different scheduler branches.'
	printf '%s\n' '- Frontend/TypeScript coverage: not included yet; Vitest exists, but this baseline avoids adding new JS coverage infrastructure in #4227.'
	printf '%s\n' '- Policy: advisory baseline. The report exposes gaps without failing unrelated PRs solely because historical coverage is low.'
	printf '%s\n\n' '- Follow-up: make package-level no-regression checks blocking after the baseline is trustworthy.'
	printf '## Exclusions\n\n'
	printf 'The generator excludes Generated Go files (`*.pb.go`, `*.gen.go`, `zz_generated*`), vendored code, fixture corpora, `testdata`, mocks, and docs-site output. In this run it included %s files and excluded %s files (%s statements).\n\n' \
		"${included_files}" "${excluded_files}" "${excluded_statements}"
	printf '## Package Drilldown\n\n'
	printf 'The coverage workflow uploads the raw Go coverage profile for exact statement- and package-level drilldown. Those volatile counts are intentionally not copied into this checked-in summary: equivalent passing concurrency tests can execute different scheduler branches while preserving the same rounded repository-level signal.\n\n'
	printf '## Report Boundaries\n\n'
	printf 'The checked-in report stays canonical at conservative whole-percent repository precision. Use the workflow artifact and log for the one-decimal percentage, exact package rankings, and source-line detail.\n'
} >"${report_out}"

printf 'generate-code-coverage-report: Go coverage %s%% exact, %s%% canonical; report=%s shield=%s profile=%s\n' \
	"${total_pct}" "${canonical_pct}" "${report_out}" "${shield_out}" "${profile}"
