#!/usr/bin/env bash
# generate-dirgate-grandfather-go.sh - regenerate
# tools/golangci-lint-dirgate/grandfather.go from
# scripts/lib/dirgate-grandfather.tsv, the single source of truth for the
# dirgate gate's grandfather ledger (issue #6054). To change a directory's
# pinned entry, edit the TSV, re-run this script, and commit the
# regenerated .go file -- never hand-edit grandfather.go itself.
#
# The test mirror scripts/test-generate-dirgate-grandfather-go.sh asserts
# the committed .go file is byte-identical to a fresh run (idempotency /
# drift) and that every TSV row has a corresponding Go map entry.
#
# Usage: scripts/generate-dirgate-grandfather-go.sh
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tsv="${DIRGATE_GRANDFATHER_TSV_INPUT:-${repo_root}/scripts/lib/dirgate-grandfather.tsv}"
out="${DIRGATE_GRANDFATHER_GO_OUTPUT:-${repo_root}/tools/golangci-lint-dirgate/grandfather.go}"

[[ -f "${tsv}" ]] || { echo "generate-dirgate-grandfather-go: missing ${tsv}" >&2; exit 1; }

{
	printf '// Code generated by scripts/generate-dirgate-grandfather-go.sh from\n'
	printf '// scripts/lib/dirgate-grandfather.tsv; DO NOT EDIT BY HAND.\n'
	printf '//\n'
	printf '// SPDX-License-Identifier: MIT\n'
	printf '// Copyright (c) 2025-2026 eshu-hq\n'
	printf '\n'
	printf 'package main\n'
	printf '\n'
	printf '// grandfatheredDirectories is the digest-pinned ledger of package\n'
	printf '// directories that already exceeded the 40-non-test-.go-file cap when the\n'
	printf '// dirgate gate landed (issue #6054), so the gate lands green on today'"'"'s\n'
	printf '// tree instead of failing on the entire pre-existing sprawl it exists to\n'
	printf '// stop from growing further. See grandfatherEntry and evaluateCapViolation\n'
	printf '// for the exact pass/fail rule each entry is checked with, and\n'
	printf '// scripts/lib/dirgate-grandfather.tsv for the source of truth this map is\n'
	printf '// generated from -- edit the TSV, then re-run\n'
	printf '// scripts/generate-dirgate-grandfather-go.sh, never this file directly.\n'
	printf 'var grandfatheredDirectories = map[string]grandfatherEntry{\n'

	# Emit rows sorted by dir key (column 1), skipping comments/blank lines.
	# gofumpt aligns the struct literals' column widths on `go fmt`; this
	# generator does not attempt to match that alignment byte-for-byte, so
	# `gofumpt -l` (run by the go-fmt gate) is what keeps the emitted file
	# formatter-clean -- run it as part of this script so the committed
	# output never depends on a separate manual gofmt pass.
	awk -F'\t' '
		/^#/ || NF != 3 { next }
		{ printf "\t\"%s\": {FileCount: %s, Digest: \"%s\"},\n", $1, $2, $3 }
	' "${tsv}" | LC_ALL=C sort

	printf '}\n'
} > "${out}"

if command -v gofmt >/dev/null 2>&1; then
	gofmt -w "${out}"
fi

echo "generate-dirgate-grandfather-go: wrote ${out}"
