#!/usr/bin/env bash
# refresh-read-api-work-budgets.sh - render
# testdata/benchmarks/read-api-route-work-budgets.txt from GREEN work reports.
#
# The read-api latency gate (go/cmd/read-api-latency-gate) writes a per-route
# Postgres work report with -work-report. This script turns one or more GREEN
# reports (the same code that must pass, run on the runner class the gate
# enforces on) into the budget table, using the formulas below over the
# MAX of each counter across reports and routes:
#
#   calls = ceil(max_calls * 1.25) + 5   (+5 absorbs one added statement; a real
#                                         N+1 at 800 scopes is +800)
#   blks  = ceil(max_blks  * 3.0)        (absorbs ANALYZE sampling and minor plan
#                                         drift; a nested-loop flip is >= 10x)
#   rows  = ceil(max_rows  * 2.0)
#
# Named rows are the routes explicitly listed in the latency budget table
# (the SLO-critical routes) that appear in the reports; the default row applies
# the same formulas to the max over every other exercised route.
#
# FLOOR: no named row is rendered below the default row in any counter. Without it
# a route that reads almost nothing renders a budget of 0 rows and 3 buffers, and
# the meter window (which sums the whole database, not one route) turns a single
# stray statement into a blocking breach. The default row is already the formulas
# over the largest reading of the routes that read almost nothing (47 routes at
# most 8 buffers; across the three GREEN artifacts and the RED artifact their maximum
# is 6 calls, 7 buffers, 7 rows, identical in every report), so it is the measured
# noise scale with the same 1.25x+5 / 3x / 2x margins, not a chosen number. The floor
# never lifts a named row that reads real work: every changed status route's budget is
# over three orders of magnitude above it. Numbers are
# never edited by hand: re-run this script and commit the result.
#
# Usage:
#   scripts/refresh-read-api-work-budgets.sh [--named-from FILE] [--out FILE] REPORT.json...
#     --named-from FILE  latency budget table naming the routes that get their own
#                        row (default: testdata/benchmarks/read-api-route-budgets.txt)
#     --out FILE         write the table to FILE (default: stdout)
#
# Output is byte-identical for identical inputs (LC_ALL=C, sorted by route, no
# timestamps).
set -euo pipefail
export LC_ALL=C

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
named_from="${repo_root}/testdata/benchmarks/read-api-route-budgets.txt"
out=""

die() {
	printf 'refresh-read-api-work-budgets: %s\n' "$*" >&2
	exit "${2:-2}"
}

reports=()
while [[ $# -gt 0 ]]; do
	case "$1" in
		--named-from) named_from="${2:?--named-from needs a file}"; shift 2 ;;
		--out) out="${2:?--out needs a file}"; shift 2 ;;
		-h | --help) sed -n '2,32p' "${BASH_SOURCE[0]}"; exit 0 ;;
		-*) die "unknown flag: $1" ;;
		*) reports+=("$1"); shift ;;
	esac
done

command -v jq >/dev/null 2>&1 || die "missing required tool: jq"
[[ ${#reports[@]} -gt 0 ]] || die "at least one GREEN work report is required"
[[ -f "${named_from}" ]] || die "named-from file not found: ${named_from}"

for report in "${reports[@]}"; do
	[[ -f "${report}" ]] || die "report not found: ${report}"
	jq -e '
		(.routes | type == "array") and
		all(.routes[]; (.route | type == "string")
			and (.work.calls | type == "number")
			and (.work.blks | type == "number")
			and (.work.rows | type == "number"))
	' "${report}" >/dev/null 2>&1 || die "malformed work report (want {\"routes\":[{\"route\",\"work\":{calls,blks,rows}}]}): ${report}"
done

named_json="$(awk -F'\t' '!/^[[:space:]]*#/ && NF >= 2 && $1 != "default" && $1 != "" {print $1}' "${named_from}" | jq -R . | jq -s .)"

table="$(jq -s -r --argjson named "${named_json}" --arg n "${#reports[@]}" '
	def ceil5: (. * 1.25 | ceil) + 5;
	def per_route: [.[] | .routes[]] | group_by(.route)
		| map({
			route: .[0].route,
			calls: (map(.work.calls) | max),
			blks: (map(.work.blks) | max),
			rows: (map(.work.rows) | max)
		});
	def row($r): "\($r.calls | ceil5)\t\($r.blks * 3 | ceil)\t\($r.rows * 2 | ceil)";
	def floored($r; $f):
		"\([($r.calls | ceil5), $f.calls] | max)\t\([($r.blks * 3 | ceil), $f.blks] | max)\t\([($r.rows * 2 | ceil), $f.rows] | max)";
	def max_of($k): map(.[$k]) | max;

	per_route as $all
	| ($all | map(select(.route as $x | $named | index($x)))) as $named_rows
	| ($all | map(select(.route as $x | ($named | index($x)) | not))) as $unnamed
	| if ($unnamed | length) == 0 then error("no unnamed exercised route to derive the default row from") else . end
	| ({calls: ($unnamed | max_of("calls")), blks: ($unnamed | max_of("blks")), rows: ($unnamed | max_of("rows"))}) as $d
	| ({calls: ($d.calls | ceil5), blks: ($d.blks * 3 | ceil), rows: ($d.rows * 2 | ceil)}) as $floor
	| "# read-api-route-work-budgets.txt -- GENERATED by scripts/refresh-read-api-work-budgets.sh",
	  "# from \($n) GREEN work report(s). Do not edit by hand: re-run the script and commit the result.",
	  "#",
	  "# Per-request Postgres work budgets for the read-API latency gate. A route breaches when ANY",
	  "# counter exceeds its budget. Formulas over the max GREEN value: calls = ceil(max*1.25)+5,",
	  "# blks = ceil(max*3.0), rows = ceil(max*2.0). No named row is below the default row.",
	  "",
	  "default\t\(row($d))",
	  "",
	  ($named_rows | sort_by(.route)[] | "\(.route)\t\(floored(.; $floor))\tGREEN-derived work guard")
' "${reports[@]}")" || die "could not render the budget table from the reports" 3

if [[ -n "${out}" ]]; then
	tmp="$(mktemp "${out}.XXXXXX")"
	printf '%s\n' "${table}" >"${tmp}"
	mv "${tmp}" "${out}"
else
	printf '%s\n' "${table}"
fi
