#!/usr/bin/env bash
# Static structural test for the C-1/C-8/C-9/C-10 replay coverage gate (#4173, #4187, #4188, #4189): the verify
# script, its CI workflow, and the coverage manifest. Fast, no Docker, no Go
# build — it validates the contract that cannot silently drift: the verifier runs
# the gate over all registries, enforces blocking CI, emits the C-7 report
# artifact with C-8 depth summaries and C-9 CLI-surface coverage, and the
# workflow uploads it.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
script="${repo_root}/scripts/verify-replay-coverage-gate.sh"
workflow="${repo_root}/.github/workflows/replay-coverage-gate.yml"
manifest="${repo_root}/specs/replay-coverage-manifest.v1.yaml"
ci_gates="${repo_root}/specs/ci-gates.v1.yaml"

fail() {
	printf 'test-verify-replay-coverage-gate: %s\n' "$*" >&2
	exit 1
}

[[ -f "${script}" ]] || fail "missing ${script}"
[[ -x "${script}" ]] || fail "verify-replay-coverage-gate.sh must be executable"
bash -n "${script}" || fail "verify-replay-coverage-gate.sh has a syntax error"

require() {
	local label="$1" needle="$2" file="$3"
	rg --fixed-strings --quiet -- "${needle}" "${file}" || fail "missing ${label}: ${needle}"
}

# The verifier: strict mode, runs the gate command, asserts the gate logic first.
require "strict mode" "set -euo pipefail" "${script}"
require "gate command" "go run ./cmd/replay-coverage-gate" "${script}"
require "unit proof" "go test ./internal/replaycoverage/ ./cmd/replay-coverage-gate/" "${script}"
require "authz proof" "Test(AuthorizationReplayCoverageContract|SecretsIAMPostureSummaryScopedGrant|AuthMiddlewareWithScopedTokensAllowsSecretsIAMRoutes)" "${script}"

# All four registries are wired in: surface-inventory + fact-kind registry come
# from the embedded artifacts the command loads, the parser ledger and capability
# matrix come from specs-dir, and the snapshot backs correlation/query scenarios.
require "specs dir input" "-specs-dir" "${script}"
require "snapshot input" "e2e-20repo-snapshot.json" "${script}"
require "repo root for refs" "-repo-root" "${script}"
require "report artifact" "-report-out" "${script}"

# C-7 (#4179): blocking verifier runs refresh the committed, docs-discoverable
# coverage dashboard. Local advisory runs must not dirty it back to advisory
# mode.
require "dashboard artifact" "-dashboard-out" "${script}"
require "dashboard gated by blocking mode" 'if [[ -n "${blocking}" ]]' "${script}"
require "gate args array" "gate_args=(" "${script}"
dashboard="${repo_root}/docs/public/reference/replay-coverage.md"
[[ -f "${dashboard}" ]] || fail "missing committed coverage dashboard ${dashboard}"
require "dashboard generated marker" "GENERATED by replay-coverage-gate" "${dashboard}"
require "dashboard in docs nav" "reference/replay-coverage.md" "${repo_root}/docs/mkdocs.yml"

# Advisory local default: the verifier initializes blocking empty and only sets
# it from the opt-in --blocking flag.
require "advisory default" 'blocking=""' "${script}"
require "blocking is opt-in" "--blocking) blocking=" "${script}"

# The workflow: invokes the verifier and uploads the coverage report artifact.
[[ -f "${workflow}" ]] || fail "missing ${workflow}"
require "workflow runs verifier" "scripts/verify-replay-coverage-gate.sh" "${workflow}"
require "workflow runs blocking gate" "verify-replay-coverage-gate.sh --blocking" "${workflow}"
require "workflow uploads report" "upload-artifact" "${workflow}"
require "workflow report name" "replay-coverage-report" "${workflow}"
require "workflow watches inputtape depth proofs" "go/internal/replay/inputtape/**" "${workflow}"
require "workflow watches schedule depth proofs" "go/internal/replay/schedulereplay/**" "${workflow}"
require "workflow watches crash depth proofs" "go/internal/replay/crashreplay/**" "${workflow}"
require "workflow watches budget proof artifact" "specs/capability-budget-proof.v1.yaml" "${workflow}"
require "workflow watches language ledger" "specs/language-feature-parity-ledger.v1.yaml" "${workflow}"
require "workflow watches ci gate registry" "specs/ci-gates.v1.yaml" "${workflow}"
require "workflow watches parser fixtures" "go/internal/replay/parserfixture/**" "${workflow}"
require "workflow watches capability catalog" "specs/capability-catalog.v1.yaml" "${workflow}"
require "workflow watches capability matrix dir" "specs/capability-matrix/**" "${workflow}"
require "workflow watches product claims" "specs/product-claims.v1.yaml" "${workflow}"
require "workflow watches fact-kind registry" "specs/fact-kind-registry.v1.yaml" "${workflow}"
require "workflow watches golden assertions" "go/internal/goldengate/**" "${workflow}"
require "workflow watches CLI command tree" "go/cmd/eshu/**" "${workflow}"
require "workflow watches query authz tests" "go/internal/query/**" "${workflow}"
require "workflow watches mcp authz tests" "go/internal/mcp/**" "${workflow}"
require "workflow watches scoped-token authz code" "go/internal/scopedtoken/**" "${workflow}"
require "workflow watches ci gate loader" "go/internal/cigates/**" "${workflow}"
require "workflow watches authorization catalog" "specs/authorization-catalog.v1.yaml" "${workflow}"
require "workflow watches authorization replay proof" "specs/authorization-replay-coverage.v1.yaml" "${workflow}"
require "workflow watches cassettes" "testdata/cassettes/**" "${workflow}"

# The CI gate registry must agree with the workflow. The registry powers local
# gate selection, so it must fail on the same replay coverage gaps CI rejects.
[[ -f "${ci_gates}" ]] || fail "missing ${ci_gates}"
require "ci registry replay gate" "id: replay-coverage-gate" "${ci_gates}"
require "ci registry blocking command" 'command: "bash scripts/verify-replay-coverage-gate.sh --blocking"' "${ci_gates}"
require "ci registry known golden proof gate" "id: golden-corpus-gate" "${ci_gates}"
require "ci registry known parser fixture proof gate" "id: parserfixture-tests" "${ci_gates}"
require "ci registry known capability proof gate" "id: capability-inventory" "${ci_gates}"
require "ci registry known capability docs proof gate" "id: capability-inventory-docs" "${ci_gates}"
require "ci registry known authz proof gate" "id: authz-scoped-route-tests" "${ci_gates}"
require "ci registry known replay tier proof gate" "id: replay-tier" "${ci_gates}"
require "ci registry watches inputtape depth proofs" "go/internal/replay/inputtape/**" "${ci_gates}"
require "ci registry watches schedule depth proofs" "go/internal/replay/schedulereplay/**" "${ci_gates}"
require "ci registry watches crash depth proofs" "go/internal/replay/crashreplay/**" "${ci_gates}"
require "ci registry watches budget proof artifact" "specs/capability-budget-proof.v1.yaml" "${ci_gates}"
require "ci registry watches ci gate registry" "specs/ci-gates.v1.yaml" "${ci_gates}"
require "ci registry watches parser fixtures" "go/internal/replay/parserfixture/**" "${ci_gates}"
require "ci registry watches capability catalog" "specs/capability-catalog.v1.yaml" "${ci_gates}"
require "ci registry watches capability matrix dir" "specs/capability-matrix/**" "${ci_gates}"
require "ci registry watches product claims" "specs/product-claims.v1.yaml" "${ci_gates}"
require "ci registry watches fact-kind registry" "specs/fact-kind-registry.v1.yaml" "${ci_gates}"
require "ci registry watches golden assertions" "go/internal/goldengate/**" "${ci_gates}"
require "ci registry watches CLI command tree" "go/cmd/eshu/**" "${ci_gates}"
require "ci registry watches query authz tests" "go/internal/query/**" "${ci_gates}"
require "ci registry watches mcp authz tests" "go/internal/mcp/**" "${ci_gates}"
require "ci registry watches scoped-token authz code" "go/internal/scopedtoken/**" "${ci_gates}"
require "ci registry watches ci gate loader" "go/internal/cigates/**" "${ci_gates}"
require "ci registry watches authorization catalog" "specs/authorization-catalog.v1.yaml" "${ci_gates}"
require "ci registry watches authorization replay proof" "specs/authorization-replay-coverage.v1.yaml" "${ci_gates}"
require "ci registry watches cassettes" "testdata/cassettes/**" "${ci_gates}"
if ! rg --multiline --quiet 'id: replay-coverage-gate\n    name: C-1/C-8/C-9/C-10 Replay Coverage Gate\n    category: exactness\n    tier: pre-pr\n    blocking: true' "${ci_gates}"; then
	fail "replay-coverage-gate registry entry must be blocking"
fi

# The manifest exists, parses as the expected schema, and is not accidentally
# empty of its version marker.
[[ -f "${manifest}" ]] || fail "missing ${manifest}"
require "manifest version" "version:" "${manifest}"
require "manifest coverage section" "coverage:" "${manifest}"

printf 'PASS: replay-coverage-gate static contract\n'
