#!/usr/bin/env bash
# test-generate-dirgate-grandfather-go.sh - prove
# scripts/generate-dirgate-grandfather-go.sh is hermetic, idempotent, and
# keeps tools/golangci-lint-dirgate/grandfather.go in lockstep with
# scripts/lib/dirgate-grandfather.tsv (the cap ledger) joined with
# scripts/lib/dirgate-naming-exempt.tsv (the per-file naming-exemption
# ledger), issue #6054. Mirrors the test-generate-* shape
# scripts/test-generate-ci-gates-doc.sh already uses.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
generator="${repo_root}/scripts/generate-dirgate-grandfather-go.sh"
committed_tsv="${repo_root}/scripts/lib/dirgate-grandfather.tsv"
committed_naming_tsv="${repo_root}/scripts/lib/dirgate-naming-exempt.tsv"
committed_go="${repo_root}/tools/golangci-lint-dirgate/grandfather.go"

command -v awk >/dev/null 2>&1 || {
	echo "test-generate-dirgate-grandfather-go: awk is required" >&2
	exit 1
}

tmp_root="$(mktemp -d)"
trap 'rm -rf "${tmp_root}"' EXIT

pass_count=0
fail_count=0
record_pass() { pass_count=$((pass_count + 1)); printf 'ok - %s\n' "$1"; }
record_fail() { fail_count=$((fail_count + 1)); printf 'not ok - %s\n' "$1" >&2; }

run_generator() {
	local out="$1" cap="${2:-${committed_tsv}}" naming="${3:-${committed_naming_tsv}}"
	DIRGATE_GRANDFATHER_TSV_INPUT="${cap}" DIRGATE_NAMING_EXEMPT_TSV_INPUT="${naming}" \
		DIRGATE_GRANDFATHER_GO_OUTPUT="${out}" bash "${generator}" >/dev/null
}

# Case 1: the generator produces a well-formed Go source file: the
# generated-file marker, the package clause, and the map declaration.
out1="${tmp_root}/run1.go"
run_generator "${out1}"
if [[ -s "${out1}" ]] \
	&& grep -q '^// Code generated by scripts/generate-dirgate-grandfather-go.sh' "${out1}" \
	&& grep -q '^package main$' "${out1}" \
	&& grep -q '^var grandfatheredDirectories = map\[string\]grandfatherEntry{' "${out1}"; then
	record_pass "generator produces the expected generated-file shape"
else
	record_fail "generator output is missing the expected marker/package/map shape"
fi

# Case 2: idempotency -- re-running with the same inputs produces
# byte-identical output.
out2="${tmp_root}/run2.go"
run_generator "${out2}"
if cmp -s "${out1}" "${out2}"; then
	record_pass "generator is idempotent on a clean re-run"
else
	record_fail "generator output is not byte-for-byte deterministic across two runs"
fi

# Case 3: no drift -- the committed grandfather.go matches a fresh
# regeneration from the committed TSVs.
if [[ -f "${committed_go}" ]] && cmp -s "${out1}" "${committed_go}"; then
	record_pass "committed grandfather.go matches a fresh regeneration"
else
	record_fail "committed grandfather.go diverges from a fresh regeneration (run: bash scripts/generate-dirgate-grandfather-go.sh)"
fi

# Case 4: cross-link -- every non-comment dirgate-grandfather.tsv row's
# directory key appears as a map key in the generated Go with its
# FileCount/Digest. This is the link between "the source of truth changed"
# and "the artifact kept up".
missing=0
while IFS=$'\t' read -r dir count digest; do
	case "${dir}" in
		""|\#*) continue ;;
	esac
	[[ -n "${count}" && -n "${digest}" ]] || continue
	# gofmt column-aligns the map literal's values, so the key->brace gap
	# is not a single fixed-width space -- match whitespace-tolerantly.
	if ! grep -qE "\"${dir}\":[[:space:]]+\{FileCount: ${count}, Digest: \"${digest}\"" "${out1}"; then
		echo "test-generate-dirgate-grandfather-go: TSV row for ${dir} has no matching Go map entry" >&2
		missing=1
	fi
done < "${committed_tsv}"
if [[ "${missing}" -eq 0 ]]; then
	record_pass "every dirgate-grandfather.tsv row has a matching Go map entry"
else
	record_fail "at least one dirgate-grandfather.tsv row is missing its Go map entry"
fi

# Case 5: cross-link -- every non-comment dirgate-naming-exempt.tsv row
# appears inside its directory's NamingExempt literal. This is the link
# between the SEPARATE naming-exemption ledger and the merged artifact.
missing=0
while IFS=$'\t' read -r dir file; do
	case "${dir}" in
		""|\#*) continue ;;
	esac
	[[ -n "${file}" ]] || continue
	if ! grep -qE "\"${dir}\":.*NamingExempt: \[\]string\{[^}]*\"${file}\"" "${out1}"; then
		echo "test-generate-dirgate-grandfather-go: naming-exempt row ${dir}/${file} has no matching Go NamingExempt entry" >&2
		missing=1
	fi
done < "${committed_naming_tsv}"
if [[ "${missing}" -eq 0 ]]; then
	record_pass "every dirgate-naming-exempt.tsv row has a matching Go NamingExempt entry"
else
	record_fail "at least one dirgate-naming-exempt.tsv row is missing its Go NamingExempt entry"
fi

# Case 6: negative case -- a NamingExempt field is only emitted for
# directories with a naming-exempt row, proving the generator does not
# leak an empty NamingExempt: []string{} into every row (the exemption is
# meant to look and act like an opt-in, not a default field).
if grep -q '"cmd/eshu":.*NamingExempt' "${out1}"; then
	record_fail "cmd/eshu has no naming-exempt row but got a NamingExempt field anyway"
else
	record_pass "a directory with no naming-exempt rows emits no NamingExempt field"
fi

# Case 7: negative case -- a cap TSV with a malformed row (wrong column
# count) is silently skipped rather than corrupting the map (proves the
# generator can fail closed on bad input instead of emitting garbage).
bad_tsv="${tmp_root}/bad.tsv"
printf 'internal/only-two-columns\t41\n' > "${bad_tsv}"
printf 'internal/good\t41\tabc123\n' >> "${bad_tsv}"
empty_naming_tsv="${tmp_root}/empty-naming.tsv"
printf '# empty\n' > "${empty_naming_tsv}"
bad_out="${tmp_root}/bad.go"
run_generator "${bad_out}" "${bad_tsv}" "${empty_naming_tsv}"
if grep -qE '"internal/good":[[:space:]]+\{FileCount: 41, Digest: "abc123"\}' "${bad_out}" \
	&& ! grep -q 'only-two-columns' "${bad_out}"; then
	record_pass "a malformed cap-TSV row is skipped, not emitted as a broken map entry"
else
	record_fail "malformed-row handling did not behave as expected"
fi

# Case 8: negative case -- a naming-exempt row is joined into its
# directory's entry when the directory has a matching cap-ledger row.
join_tsv="${tmp_root}/join-cap.tsv"
printf 'internal/good\t41\tabc123\n' > "${join_tsv}"
join_naming_tsv="${tmp_root}/join-naming.tsv"
printf 'internal/good\tfoo_bar.go\ninternal/good\tfoo_baz.go\n' > "${join_naming_tsv}"
join_out="${tmp_root}/join.go"
run_generator "${join_out}" "${join_tsv}" "${join_naming_tsv}"
if grep -qE '"internal/good":[[:space:]]+\{FileCount: 41, Digest: "abc123", NamingExempt: \[\]string\{"foo_bar.go", "foo_baz.go"\}\}' "${join_out}"; then
	record_pass "a naming-exempt row is joined into the matching cap-ledger directory's entry"
else
	record_fail "naming-exempt join did not produce the expected NamingExempt literal"
fi

# Case 9: negative case -- a naming-exempt row for a directory with NO
# matching cap-ledger row makes the generator FAIL before writing any
# output, rather than silently dropping the row or emitting a synthetic
# entry (issue #6054 follow-up: today every real exemption lives inside an
# already cap-grandfathered directory, so an orphaned row is a ledger
# authoring error, not a case to render output for).
orphan_naming_tsv="${tmp_root}/orphan-naming.tsv"
printf 'internal/does-not-exist\tfoo.go\n' > "${orphan_naming_tsv}"
orphan_out="${tmp_root}/orphan.go"
rm -f "${orphan_out}"
if DIRGATE_GRANDFATHER_TSV_INPUT="${join_tsv}" DIRGATE_NAMING_EXEMPT_TSV_INPUT="${orphan_naming_tsv}" \
	DIRGATE_GRANDFATHER_GO_OUTPUT="${orphan_out}" bash "${generator}" >/dev/null 2>"${tmp_root}/orphan.err"; then
	record_fail "generator should have failed on an orphaned naming-exempt row"
else
	if [[ ! -e "${orphan_out}" ]] && grep -q "internal/does-not-exist" "${tmp_root}/orphan.err"; then
		record_pass "an orphaned naming-exempt row fails generation before writing any output"
	else
		record_fail "orphaned-row failure did not behave as expected"
	fi
fi

printf '\ntest-generate-dirgate-grandfather-go passed: %d/%d\n' "${pass_count}" "$((pass_count + fail_count))"
[[ "${fail_count}" -eq 0 ]]
