#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp_root="$(mktemp -d)"
trap 'rm -rf "$tmp_root"' EXIT

# Create a minimal contract spec in a temp directory.
spec_dir="${tmp_root}/specs"
mkdir -p "$spec_dir"
spec="${spec_dir}/collector_fact_contract.v1.yaml"
cat >"$spec" <<'YAML'
version: "1.0.0"
collectors:
  aws:
    collector_kind: aws
    fact_kinds:
      aws_resource:
        required_payload_keys:
          - account_id
          - arn
          - resource_type
YAML

# Generate.
ESHU_CONTRACTTEST_REPO_ROOT="$tmp_root" \
  ESHU_CONTRACTTEST_GO_DIR="${repo_root}/go" \
  ESHU_CONTRACTTEST_SPEC="$spec" \
  "${repo_root}/scripts/generate-contracttest.sh" >/tmp/eshu-contracttest-generate.out

gen_file="${tmp_root}/go/internal/collector/contracttest/contract_data.go"
if [ ! -f "$gen_file" ]; then
  printf 'generate-contracttest: expected generated file %s not found\n' "$gen_file" >&2
  exit 1
fi

# Verify generated output contains expected content.
if ! rg -q 'Code generated by' "$gen_file"; then
  printf 'generated file missing "Code generated by" header\n' >&2
  exit 1
fi
if ! rg -q 'package contracttest' "$gen_file"; then
  printf 'generated file missing "package contracttest" declaration\n' >&2
  exit 1
fi
if ! rg -q 'var AWSContract = Contract' "$gen_file"; then
  printf 'generated file missing AWSContract variable\n' >&2
  exit 1
fi
if ! rg -q 'CollectorKind: "aws"' "$gen_file"; then
  printf 'generated file missing CollectorKind\n' >&2
  exit 1
fi
if ! rg -q 'Kind: "aws_resource"' "$gen_file"; then
  printf 'generated file missing aws_resource fact kind\n' >&2
  exit 1
fi
if ! rg -q 'func Contracts()' "$gen_file"; then
  printf 'generated file missing Contracts() function\n' >&2
  exit 1
fi

# Verify idempotency.
cp "$gen_file" "${gen_file}.bak"
ESHU_CONTRACTTEST_REPO_ROOT="$tmp_root" \
  ESHU_CONTRACTTEST_GO_DIR="${repo_root}/go" \
  ESHU_CONTRACTTEST_SPEC="$spec" \
  "${repo_root}/scripts/generate-contracttest.sh" >/tmp/eshu-contracttest-generate-2.out

if ! cmp -s "$gen_file" "${gen_file}.bak"; then
  printf 'generate-contracttest is not idempotent on a clean re-run\n' >&2
  diff "$gen_file" "${gen_file}.bak" >&2 || true
  exit 1
fi

# Verify -check passes.
ESHU_CONTRACTTEST_REPO_ROOT="$tmp_root" \
  ESHU_CONTRACTTEST_GO_DIR="${repo_root}/go" \
  ESHU_CONTRACTTEST_SPEC="$spec" \
  "${repo_root}/scripts/verify-contracttest.sh" >/tmp/eshu-contracttest-verify.out

# Corrupt output and verify -check fails.
printf 'package contracttest\n' >"$gen_file"
if ESHU_CONTRACTTEST_REPO_ROOT="$tmp_root" \
  ESHU_CONTRACTTEST_GO_DIR="${repo_root}/go" \
  ESHU_CONTRACTTEST_SPEC="$spec" \
  "${repo_root}/scripts/verify-contracttest.sh" >/tmp/eshu-contracttest-stale.out 2>/tmp/eshu-contracttest-stale.err; then
  printf 'expected stale generated contracttest check to fail\n' >&2
  exit 1
fi

if ! rg -q 'stale' /tmp/eshu-contracttest-stale.err; then
  printf 'expected stale generated file error, got:\n' >&2
  sed -n '1,20p' /tmp/eshu-contracttest-stale.err >&2
  exit 1
fi

printf 'test-verify-contracttest tests passed\n'
