#!/usr/bin/env bash
# test-generate-dirgate-grandfather-go.sh - prove
# scripts/generate-dirgate-grandfather-go.sh is hermetic, idempotent, and
# keeps tools/golangci-lint-dirgate/grandfather.go in lockstep with
# scripts/lib/dirgate-grandfather.tsv (issue #6054). Mirrors the
# test-generate-* shape scripts/test-generate-ci-gates-doc.sh already uses.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
generator="${repo_root}/scripts/generate-dirgate-grandfather-go.sh"
committed_tsv="${repo_root}/scripts/lib/dirgate-grandfather.tsv"
committed_go="${repo_root}/tools/golangci-lint-dirgate/grandfather.go"

command -v awk >/dev/null 2>&1 || {
	echo "test-generate-dirgate-grandfather-go: awk is required" >&2
	exit 1
}

tmp_root="$(mktemp -d)"
trap 'rm -rf "${tmp_root}"' EXIT

pass_count=0
fail_count=0
record_pass() { pass_count=$((pass_count + 1)); printf 'ok - %s\n' "$1"; }
record_fail() { fail_count=$((fail_count + 1)); printf 'not ok - %s\n' "$1" >&2; }

run_generator() {
	local out="$1"
	DIRGATE_GRANDFATHER_TSV_INPUT="${committed_tsv}" DIRGATE_GRANDFATHER_GO_OUTPUT="${out}" \
		bash "${generator}" >/dev/null
}

# Case 1: the generator produces a well-formed Go source file: the
# generated-file marker, the package clause, and the map declaration.
out1="${tmp_root}/run1.go"
run_generator "${out1}"
if [[ -s "${out1}" ]] \
	&& grep -q '^// Code generated by scripts/generate-dirgate-grandfather-go.sh' "${out1}" \
	&& grep -q '^package main$' "${out1}" \
	&& grep -q '^var grandfatheredDirectories = map\[string\]grandfatherEntry{' "${out1}"; then
	record_pass "generator produces the expected generated-file shape"
else
	record_fail "generator output is missing the expected marker/package/map shape"
fi

# Case 2: idempotency -- re-running with the same inputs produces
# byte-identical output.
out2="${tmp_root}/run2.go"
run_generator "${out2}"
if cmp -s "${out1}" "${out2}"; then
	record_pass "generator is idempotent on a clean re-run"
else
	record_fail "generator output is not byte-for-byte deterministic across two runs"
fi

# Case 3: no drift -- the committed grandfather.go matches a fresh
# regeneration from the committed TSV.
if [[ -f "${committed_go}" ]] && cmp -s "${out1}" "${committed_go}"; then
	record_pass "committed grandfather.go matches a fresh regeneration"
else
	record_fail "committed grandfather.go diverges from a fresh regeneration (run: bash scripts/generate-dirgate-grandfather-go.sh)"
fi

# Case 4: cross-link -- every non-comment TSV row's directory key appears
# as a map key in the generated Go. This is the link between "the source
# of truth changed" and "the artifact kept up".
missing=0
while IFS=$'\t' read -r dir count digest; do
	case "${dir}" in
		""|\#*) continue ;;
	esac
	[[ -n "${count}" && -n "${digest}" ]] || continue
	# gofmt column-aligns the map literal's values, so the key->brace gap
	# is not a single fixed-width space -- match whitespace-tolerantly.
	if ! grep -qE "\"${dir}\":[[:space:]]+\{FileCount: ${count}, Digest: \"${digest}\"\}" "${out1}"; then
		echo "test-generate-dirgate-grandfather-go: TSV row for ${dir} has no matching Go map entry" >&2
		missing=1
	fi
done < "${committed_tsv}"
if [[ "${missing}" -eq 0 ]]; then
	record_pass "every dirgate-grandfather.tsv row has a matching Go map entry"
else
	record_fail "at least one TSV row is missing its Go map entry"
fi

# Case 5: negative case -- a TSV with a malformed row (wrong column count)
# is silently skipped rather than corrupting the map (proves the
# generator can fail closed on bad input instead of emitting garbage).
bad_tsv="${tmp_root}/bad.tsv"
printf 'internal/only-two-columns\t41\n' > "${bad_tsv}"
printf 'internal/good\t41\tabc123\n' >> "${bad_tsv}"
bad_out="${tmp_root}/bad.go"
DIRGATE_GRANDFATHER_TSV_INPUT="${bad_tsv}" DIRGATE_GRANDFATHER_GO_OUTPUT="${bad_out}" bash "${generator}" >/dev/null
if grep -qE '"internal/good":[[:space:]]+\{FileCount: 41, Digest: "abc123"\}' "${bad_out}" \
	&& ! grep -q 'only-two-columns' "${bad_out}"; then
	record_pass "a malformed TSV row is skipped, not emitted as a broken map entry"
else
	record_fail "malformed-row handling did not behave as expected"
fi

printf '\ntest-generate-dirgate-grandfather-go passed: %d/%d\n' "${pass_count}" "$((pass_count + fail_count))"
[[ "${fail_count}" -eq 0 ]]
