// qrCode.test.ts — golden-vector accuracy gate for the vendored byte-mode QR
// encoder (issue #5072). The oracle fixture (qrCodeGolden.fixture.json) was
// generated by the pure-Python `segno` reference encoder (ECC-M, byte mode,
// standard QR, boost_error=False, micro=False) as an INDEPENDENT oracle —
// this proves the vendored encoder is spec-correct across three QR versions
// without relying on hand-transcribed expected output.
import { describe, expect, it } from "vitest";

import { encodeQrMatrix } from "./qrCode";
import golden from "./qrCodeGolden.fixture.json";

interface GoldenVector {
  readonly text: string;
  readonly version: number;
  readonly ecc: string;
  readonly mode: string;
  readonly size: number;
  readonly rows: readonly string[];
}

const vectors: Record<string, GoldenVector> = golden as Record<string, GoldenVector>;

describe("encodeQrMatrix golden vectors", () => {
  for (const [name, vector] of Object.entries(vectors)) {
    it(`matches the segno oracle for the "${name}" vector (version ${vector.version})`, () => {
      const matrix = encodeQrMatrix(vector.text);

      expect(matrix.length).toBe(vector.size);
      for (const row of matrix) {
        expect(row.length).toBe(vector.size);
      }

      for (let r = 0; r < vector.size; r++) {
        for (let c = 0; c < vector.size; c++) {
          const expected = vector.rows[r][c] === "1";
          if (matrix[r][c] !== expected) {
            throw new Error(
              `mismatch at row ${r}, col ${c} for vector "${name}": expected ${expected}, got ${matrix[r][c]}`,
            );
          }
        }
      }
    });
  }
});

describe("encodeQrMatrix input validation", () => {
  it("throws on an empty string", () => {
    expect(() => encodeQrMatrix("")).toThrow();
  });
});
