// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package parser

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/eshu-hq/eshu/go/internal/parser/shared"
)

// bareCREOLVariants are the three line terminators a repository file can use.
// "cr" is the classic-Mac form that carries no '\n' anywhere, which every
// '\n'-only scanner and tree-sitter's own row counter read as a single line
// (issue #6306).
var bareCREOLVariants = []struct {
	name string
	eol  string
}{
	{name: "lf", eol: "\n"},
	{name: "crlf", eol: "\r\n"},
	{name: "cr", eol: "\r"},
}

// joinWithEOL renders lines with the given terminator, including a trailing one.
func joinWithEOL(eol string, lines ...string) string {
	return strings.Join(lines, eol) + eol
}

// writeRepoFile writes body under a fresh repo root and returns both paths.
func writeRepoFile(t *testing.T, name string, body string) (string, string) {
	t.Helper()
	repoRoot := t.TempDir()
	path := filepath.Join(repoRoot, name)
	if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
		t.Fatalf("MkdirAll(%q) error = %v, want nil", filepath.Dir(path), err)
	}
	if err := os.WriteFile(path, []byte(body), 0o600); err != nil {
		t.Fatalf("WriteFile(%q) error = %v, want nil", path, err)
	}
	return repoRoot, path
}

// comparablePayload renders a parser payload as stable JSON with every
// absolute-path artifact of the test's temp directory replaced by a fixed
// token, so payloads produced from different temp directories compare on
// parsed truth alone. Some payloads (yaml helm_values, for one) carry the
// absolute file path in a nested bucket row, so deleting the two top-level
// path keys is not enough on its own.
func comparablePayload(t *testing.T, payload map[string]any, repoRoot string) string {
	t.Helper()
	clone := make(map[string]any, len(payload))
	for key, value := range payload {
		if key == "path" || key == "repo_path" || key == "source" {
			continue
		}
		clone[key] = value
	}
	encoded, err := json.Marshal(clone)
	if err != nil {
		t.Fatalf("json.Marshal(payload) error = %v, want nil", err)
	}
	rendered := strings.ReplaceAll(string(encoded), repoRoot, "<repo>")
	if resolved, err := filepath.EvalSymlinks(repoRoot); err == nil {
		rendered = strings.ReplaceAll(rendered, resolved, "<repo>")
	}
	return rendered
}

// TestParsePathBareCRMatchesLFTruth is the production-path regression for
// issue #6306. It drives Engine.ParsePath -- the real entry point every
// collector uses -- once per line-ending style over the same logical file, and
// requires the parsed truth to be identical. A bare-CR file is the same source
// as its LF twin; any difference is data the parser silently lost.
func TestParsePathBareCRMatchesLFTruth(t *testing.T) {
	cases := []struct {
		name     string
		fileName string
		lines    []string
	}{
		{
			name:     "c_function_line_numbers",
			fileName: "widget.c",
			lines: []string{
				"int alpha(void) { return 1; }",
				"int beta(void) { return 2; }",
				"int gamma(void) { return 3; }",
			},
		},
		{
			name:     "go_sum_checksum_rows",
			fileName: "go.sum",
			lines: []string{
				"github.com/example/one v1.0.0 h1:abcdefghijklmnopqrstuvwxyz0123456789ABCDEFG=",
				"github.com/example/one v1.0.0/go.mod h1:bbcdefghijklmnopqrstuvwxyz0123456789ABCDEFG=",
				"github.com/example/two v2.0.0 h1:cbcdefghijklmnopqrstuvwxyz0123456789ABCDEFG=",
			},
		},
		{
			name:     "yarn_classic_dependencies",
			fileName: "yarn.lock",
			lines: []string{
				"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.",
				"# yarn lockfile v1",
				"",
				`"lodash@^4.17.0":`,
				`  version "4.17.21"`,
				`  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"`,
			},
		},
		{
			name:     "pip_requirements_rows",
			fileName: "requirements.txt",
			lines: []string{
				"# runtime dependencies",
				"requests==2.31.0",
				"urllib3==2.0.7",
			},
		},
		{
			name:     "dockerfile_metadata",
			fileName: "Dockerfile",
			lines: []string{
				"# syntax=docker/dockerfile:1",
				"FROM alpine:3.19 AS build",
				"RUN echo hello",
				"FROM alpine:3.19",
				"COPY --from=build /bin/true /bin/true",
			},
		},
		{
			// JSONC, Gradle and SQL are the three scanners #6268 patched
			// individually on its own branch. That work is not on main, so
			// these cases stand unfixed on this base and prove the single
			// read-boundary normalization covers the same ground.
			name:     "jsonc_line_comment_terminator",
			fileName: "tsconfig.json",
			lines: []string{
				"{",
				`  // compiler options for the app`,
				`  "compilerOptions": {`,
				`    "baseUrl": "./src"`,
				"  }",
				"}",
			},
		},
		{
			name:     "gradle_dependency_block",
			fileName: "build.gradle",
			lines: []string{
				"// build script for the service",
				"dependencies {",
				`    implementation "com.example:widget:1.2.3"`,
				`    implementation "com.example:gadget:4.5.6"`,
				"}",
			},
		},
		{
			name:     "sql_statements_after_a_line_comment",
			fileName: "migration.sql",
			lines: []string{
				"-- create the widget tables",
				"CREATE TABLE widget (id int);",
				"CREATE TABLE gadget (id int);",
			},
		},
		{
			// Control. yaml.v3 honours a bare CR as a line break on its own,
			// so this case passes with and without the normalization; it is
			// here to prove normalization does not perturb a language that
			// was already correct, not as a regression for one that was not.
			name:     "yaml_bare_cr_control",
			fileName: "values.yaml",
			lines: []string{
				"# top banner comment",
				"alpha: one",
				"beta: two",
				"gamma: three",
			},
		},
	}

	for _, testCase := range cases {
		t.Run(testCase.name, func(t *testing.T) {
			want := ""
			for _, variant := range bareCREOLVariants {
				body := joinWithEOL(variant.eol, testCase.lines...)
				repoRoot, path := writeRepoFile(t, testCase.fileName, body)
				got := comparablePayload(t, mustParsePath(t, repoRoot, path), repoRoot)
				if variant.name == "lf" {
					want = got
					continue
				}
				if got != want {
					t.Fatalf("ParsePath(%s, eol=%s) truth = %s, want the lf truth %s",
						testCase.fileName, variant.name, got, want)
				}
			}
		})
	}
}

// TestParsePathBareCRCFunctionLines pins the concrete symptom the payload
// equality above would also catch, so a failure names the defect directly: on
// a bare-CR file every tree-sitter StartPosition().Row is 0, so every function
// is stamped line 1.
func TestParsePathBareCRCFunctionLines(t *testing.T) {
	body := joinWithEOL("\r",
		"int alpha(void) { return 1; }",
		"int beta(void) { return 2; }",
		"int gamma(void) { return 3; }",
	)
	repoRoot, path := writeRepoFile(t, "widget.c", body)
	payload := mustParsePath(t, repoRoot, path)

	wantLines := map[string]int{"alpha": 1, "beta": 2, "gamma": 3}
	functions, _ := payload["functions"].([]map[string]any)
	if len(functions) != len(wantLines) {
		t.Fatalf("functions count = %d, want %d (%#v)", len(functions), len(wantLines), functions)
	}
	for _, function := range functions {
		name, _ := function["name"].(string)
		want, ok := wantLines[name]
		if !ok {
			t.Fatalf("unexpected function %q in %#v", name, functions)
		}
		if got := intFromPayload(function["line_number"]); got != want {
			t.Fatalf("function %q line_number = %d, want %d", name, got, want)
		}
	}
}

// TestParsePathBareCRCPPPublicHeaderRoots covers the highest-blast-radius
// scanner in issue #6306: cpp/header_roots.go strips line comments with
// `(?m)//.*$`, which on a bare-CR header deletes from the first `//` to EOF
// and leaves zero public-header roots. The header is read by
// AnnotatePublicHeaderRoots's own os.ReadFile, not through shared.ReadSource,
// so it needs its own normalization.
func TestParsePathBareCRCPPPublicHeaderRoots(t *testing.T) {
	repoRoot := t.TempDir()
	header := joinWithEOL("\r",
		"// public surface of the widget module",
		"int render_widget(int width);",
		"int measure_widget(int width);",
	)
	if err := os.WriteFile(filepath.Join(repoRoot, "widget.h"), []byte(header), 0o600); err != nil {
		t.Fatalf("WriteFile(widget.h) error = %v, want nil", err)
	}
	source := joinWithEOL("\n",
		`#include "widget.h"`,
		"int render_widget(int width) { return width; }",
		"int measure_widget(int width) { return width + 1; }",
	)
	sourcePath := filepath.Join(repoRoot, "widget.cpp")
	if err := os.WriteFile(sourcePath, []byte(source), 0o600); err != nil {
		t.Fatalf("WriteFile(widget.cpp) error = %v, want nil", err)
	}

	payload := mustParsePath(t, repoRoot, sourcePath)
	functions, _ := payload["functions"].([]map[string]any)
	rooted := 0
	for _, function := range functions {
		kinds, _ := function["dead_code_root_kinds"].([]string)
		for _, kind := range kinds {
			if kind == "cpp.public_header_api" {
				rooted++
			}
		}
	}
	if rooted != 2 {
		t.Fatalf("cpp.public_header_api roots = %d, want 2 (%#v)", rooted, functions)
	}
}

// TestParsePathBareCRCPublicHeaderRoots is the C twin of the C++ header-root
// regression above; c/dead_code_roots.go carries the identical `(?m)//.*$`
// strip over its own os.ReadFile of the header.
func TestParsePathBareCRCPublicHeaderRoots(t *testing.T) {
	repoRoot := t.TempDir()
	header := joinWithEOL("\r",
		"// public surface of the gadget module",
		"int render_gadget(int width);",
		"int measure_gadget(int width);",
	)
	if err := os.WriteFile(filepath.Join(repoRoot, "gadget.h"), []byte(header), 0o600); err != nil {
		t.Fatalf("WriteFile(gadget.h) error = %v, want nil", err)
	}
	source := joinWithEOL("\n",
		`#include "gadget.h"`,
		"int render_gadget(int width) { return width; }",
		"int measure_gadget(int width) { return width + 1; }",
	)
	sourcePath := filepath.Join(repoRoot, "gadget.c")
	if err := os.WriteFile(sourcePath, []byte(source), 0o600); err != nil {
		t.Fatalf("WriteFile(gadget.c) error = %v, want nil", err)
	}

	payload := mustParsePath(t, repoRoot, sourcePath)
	functions, _ := payload["functions"].([]map[string]any)
	rooted := 0
	for _, function := range functions {
		kinds, _ := function["dead_code_root_kinds"].([]string)
		for _, kind := range kinds {
			if kind == "c.public_header_api" {
				rooted++
			}
		}
	}
	if rooted != 2 {
		t.Fatalf("c.public_header_api roots = %d, want 2 (%#v)", rooted, functions)
	}
}

// intFromPayload converts the numeric shapes a parser payload can carry.
func intFromPayload(value any) int {
	switch typed := value.(type) {
	case int:
		return typed
	case int64:
		return int(typed)
	case float64:
		return int(typed)
	default:
		return -1
	}
}

// TestParsePathBareCRUnderCollectorPrimedSource reproduces the sequence the
// git collector actually runs, which no other test here covers. In
// production ParsePath is never reached with a cold cache: the collector
// reads the file itself and primes those RAW bytes first, so that ParsePath's
// own read is a cache hit rather than a second physical read (see
// go/internal/collector/gitrepo/git_snapshot_parse_partitions.go, the
// os.ReadFile + shared.PrimeSource pair). Normalizing only ReadSource's disk
// path would therefore leave the entire production parse path broken while
// every cold-cache test in this file still passed -- the same shape of false
// green that #6268 shipped.
func TestParsePathBareCRUnderCollectorPrimedSource(t *testing.T) {
	body := joinWithEOL("\r",
		"int alpha(void) { return 1; }",
		"int beta(void) { return 2; }",
		"int gamma(void) { return 3; }",
	)
	repoRoot, path := writeRepoFile(t, "widget.c", body)

	// Mirror the collector: read the raw bytes, prime them under the
	// absolute path ParsePath will resolve to, then parse.
	raw, err := os.ReadFile(path) // #nosec G304 -- test fixture written by this test
	if err != nil {
		t.Fatalf("ReadFile(%q) error = %v, want nil", path, err)
	}
	absPath, err := filepath.Abs(path)
	if err != nil {
		t.Fatalf("Abs(%q) error = %v, want nil", path, err)
	}
	shared.PrimeSource(absPath, raw)
	defer shared.ClearSource(absPath)

	payload := mustParsePath(t, repoRoot, path)

	wantLines := map[string]int{"alpha": 1, "beta": 2, "gamma": 3}
	functions, _ := payload["functions"].([]map[string]any)
	if len(functions) != len(wantLines) {
		t.Fatalf("functions count = %d, want %d (%#v)", len(functions), len(wantLines), functions)
	}
	for _, function := range functions {
		name, _ := function["name"].(string)
		if got := intFromPayload(function["line_number"]); got != wantLines[name] {
			t.Fatalf("function %q line_number = %d, want %d (primed-source path)", name, got, wantLines[name])
		}
	}

	// The collector hands these same raw bytes to shapeFileFromParsed, whose
	// digest becomes content identity. Parsing must not have touched them.
	if string(raw) != body {
		t.Fatalf("ParsePath mutated the collector's primed bytes; content identity would move")
	}
}

// TestParsePathBareCRGoModuleImportPath covers goModulePath, which reads
// go.mod with its own os.ReadFile and splits it on '\n'. On a bare-CR go.mod
// the whole file is one line, strings.Fields sees far more than the two
// tokens the module directive is recognised by, and the module path resolves
// empty -- costing every Go package under that module its import path
// (issue #6306).
func TestParsePathBareCRGoModuleImportPath(t *testing.T) {
	for _, variant := range bareCREOLVariants {
		t.Run(variant.name, func(t *testing.T) {
			repoRoot := t.TempDir()
			goMod := joinWithEOL(variant.eol,
				"module github.com/example/widget",
				"",
				"go 1.25",
			)
			if err := os.WriteFile(filepath.Join(repoRoot, "go.mod"), []byte(goMod), 0o600); err != nil {
				t.Fatalf("WriteFile(go.mod) error = %v, want nil", err)
			}
			if got := goModulePath(repoRoot); got != "github.com/example/widget" {
				t.Fatalf("goModulePath(eol=%s) = %q, want %q", variant.name, got, "github.com/example/widget")
			}
		})
	}
}

// TestParsePathBareCRPythonPackageInitExports covers
// pythonPackageInitExportedNames, which reads __init__.py with its own
// os.ReadFile and splits it on '\n'. On a bare-CR __init__.py the whole file
// is one line, no `from ... import` statement is recognised, and every symbol
// the package re-exports loses its python.package_init_export dead-code root
// -- so a live public class reads as dead (issue #6306).
func TestParsePathBareCRPythonPackageInitExports(t *testing.T) {
	for _, variant := range bareCREOLVariants {
		t.Run(variant.name, func(t *testing.T) {
			repoRoot := t.TempDir()
			packageDir := filepath.Join(repoRoot, "service")
			if err := os.MkdirAll(packageDir, 0o750); err != nil {
				t.Fatalf("MkdirAll(%q) error = %v, want nil", packageDir, err)
			}
			initBody := joinWithEOL(variant.eol,
				"\"\"\"Package surface.\"\"\"",
				"from .models import PublicService as Service",
			)
			if err := os.WriteFile(filepath.Join(packageDir, "__init__.py"), []byte(initBody), 0o600); err != nil {
				t.Fatalf("WriteFile(__init__.py) error = %v, want nil", err)
			}
			modelsPath := filepath.Join(packageDir, "models.py")
			models := joinWithEOL("\n",
				"class PublicService:",
				"    def run(self):",
				`        return "ok"`,
			)
			if err := os.WriteFile(modelsPath, []byte(models), 0o600); err != nil {
				t.Fatalf("WriteFile(models.py) error = %v, want nil", err)
			}

			payload := mustParsePath(t, repoRoot, modelsPath)
			classes, _ := payload["classes"].([]map[string]any)
			found := false
			for _, class := range classes {
				if name, _ := class["name"].(string); name != "PublicService" {
					continue
				}
				kinds, _ := class["dead_code_root_kinds"].([]string)
				for _, kind := range kinds {
					if kind == "python.package_init_export" {
						found = true
					}
				}
			}
			if !found {
				t.Fatalf("PublicService missing python.package_init_export for eol=%s (%#v)", variant.name, classes)
			}
		})
	}
}
