// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package nodelockfile

import (
	"testing"

	"github.com/eshu-hq/eshu/go/internal/parser/shared"
)

// TestParseYarnClassicLockfileEmitsExactVersions covers Yarn classic v1 lockfile
// shape - the canonical yarn.lock format generated by Yarn 1.x. We assert that
// each dependency descriptor block ("lodash@^4.17.21:" style) lands as one row
// with the resolved exact version, package_manager flavor "yarn", and the npm
// ecosystem identity preserved as the package_manager_flavor companion field.
func TestParseYarnClassicLockfileEmitsExactVersions(t *testing.T) {
	t.Parallel()

	path := writeTestFile(t, "yarn.lock", `# THIS FILE IS GENERATED, DO NOT EDIT DIRECTLY.
# yarn lockfile v1


lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
  integrity sha512-AbCdEf==

"@types/node@^20.0.0", "@types/node@^20.1.0":
  version "20.5.0"
  resolved "https://registry.yarnpkg.com/@types/node/-/node-20.5.0.tgz"

vite@^5.0.0:
  version "5.0.0"
  resolved "https://registry.yarnpkg.com/vite/-/vite-5.0.0.tgz"
  dependencies:
    rollup "^4.0.0"

rollup@^4.0.0:
  version "4.0.0"
  resolved "https://registry.yarnpkg.com/rollup/-/rollup-4.0.0.tgz"
`)

	rows := parseAndExtractRows(t, path)
	got := rowsByName(rows)

	wantVersions := map[string]string{
		"lodash":      "4.17.21",
		"@types/node": "20.5.0",
		"vite":        "5.0.0",
		"rollup":      "4.0.0",
	}
	for name, version := range wantVersions {
		row, ok := got[name]
		if !ok {
			t.Fatalf("expected yarn dependency row for %q, got %#v", name, rows)
		}
		if row["value"] != version {
			t.Fatalf("%s value = %#v, want %q", name, row["value"], version)
		}
		if row["package_manager"] != "npm" {
			t.Fatalf("%s package_manager = %#v, want canonical npm ecosystem", name, row["package_manager"])
		}
		if row["package_manager_flavor"] != "yarn" {
			t.Fatalf("%s package_manager_flavor = %#v, want yarn", name, row["package_manager_flavor"])
		}
		if row["config_kind"] != "dependency" {
			t.Fatalf("%s config_kind = %#v, want dependency", name, row["config_kind"])
		}
		if row["section"] != "yarn.lock" {
			t.Fatalf("%s section = %#v, want yarn.lock", name, row["section"])
		}
		if row["lockfile"] != true {
			t.Fatalf("%s lockfile flag = %#v, want true", name, row["lockfile"])
		}
		if row["lockfile_format"] != "yarn-classic" {
			t.Fatalf("%s lockfile_format = %#v, want yarn-classic", name, row["lockfile_format"])
		}
	}
}

// TestParseYarnClassicLockfilePreservesDependencyChain pins the transitive
// dependency evidence requirement from issue #644: vulnerability impact must
// be able to say "rollup is here because vite depends on it".
func TestParseYarnClassicLockfilePreservesDependencyChain(t *testing.T) {
	t.Parallel()

	path := writeTestFile(t, "yarn.lock", `# yarn lockfile v1

vite@^5.0.0:
  version "5.0.0"
  dependencies:
    rollup "^4.0.0"

rollup@^4.0.0:
  version "4.0.0"
  dependencies:
    fsevents "~2.3.3"

fsevents@~2.3.3:
  version "2.3.3"
`)

	got := rowsByName(parseAndExtractRows(t, path))
	assertChain(t, got["vite"], []string{"vite"}, 1, true)
	assertChain(t, got["rollup"], []string{"vite", "rollup"}, 2, false)
	assertChain(t, got["fsevents"], []string{"vite", "rollup", "fsevents"}, 3, false)
}

// TestParseYarnBerryLockfileEmitsExactVersions covers Yarn Berry (v2+) format
// where lockfiles are YAML-compatible. Berry uses "name@npm:range" descriptors
// and a resolution string with the exact version.
func TestParseYarnBerryLockfileEmitsExactVersions(t *testing.T) {
	t.Parallel()

	path := writeTestFile(t, "yarn.lock", `# This file is generated by running "yarn install"
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10c0

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"
  checksum: 10c0/...
  languageName: node
  linkType: hard

"@types/node@npm:^20.0.0":
  version: 20.5.0
  resolution: "@types/node@npm:20.5.0"
  languageName: node
  linkType: hard

"workspace-inner@workspace:packages/inner":
  version: 0.0.0-use.local
  resolution: "workspace-inner@workspace:packages/inner"
  languageName: unknown
  linkType: soft
`)

	rows := parseAndExtractRows(t, path)
	got := rowsByName(rows)

	for name, version := range map[string]string{
		"lodash":      "4.17.21",
		"@types/node": "20.5.0",
	} {
		row, ok := got[name]
		if !ok {
			t.Fatalf("expected yarn-berry dependency row for %q in %#v", name, rows)
		}
		if row["value"] != version {
			t.Fatalf("%s value = %#v, want %q", name, row["value"], version)
		}
		if row["lockfile_format"] != "yarn-berry" {
			t.Fatalf("%s lockfile_format = %#v, want yarn-berry", name, row["lockfile_format"])
		}
		if row["package_manager"] != "npm" {
			t.Fatalf("%s package_manager = %#v, want canonical npm ecosystem", name, row["package_manager"])
		}
		if row["package_manager_flavor"] != "yarn" {
			t.Fatalf("%s package_manager_flavor = %#v, want yarn", name, row["package_manager_flavor"])
		}
	}

	// Workspace/local entries with no real package version must NOT smuggle a
	// remote dependency row through Parse; otherwise vulnerability impact
	// would mistake a local workspace for a registry package.
	if _, ok := got["workspace-inner"]; ok {
		t.Fatalf("workspace-only entry was emitted as remote dependency: %#v", got["workspace-inner"])
	}
}

// TestParseMalformedYarnLockfileEmitsNoDependencyRows enforces the safety rule
// from issue #571: until a parser actually understands the lockfile, no fake
// dependency row may leak into the fact stream. A malformed yarn.lock that
// fails parsing must produce zero dependency rows, not a partial guess.
func TestParseMalformedYarnLockfileEmitsNoDependencyRows(t *testing.T) {
	t.Parallel()

	path := writeTestFile(t, "yarn.lock", `# THIS FILE IS NOT VALID
:::garbage{}{}{not a real lockfile
`)

	payload, err := Parse(path, false, shared.Options{})
	if err != nil {
		t.Fatalf("Parse(malformed yarn.lock) error = %v, want nil parser-level error", err)
	}
	rows, _ := payload["variables"].([]map[string]any)
	for _, row := range rows {
		if row["config_kind"] == "dependency" {
			t.Fatalf("malformed yarn.lock leaked dependency row %#v", row)
		}
	}
	if got := payload["lockfile_parse_state"]; got != "malformed" {
		t.Fatalf("lockfile_parse_state = %#v, want malformed for unparseable yarn.lock", got)
	}
}

// TestParseUnsupportedYarnBerryFeatureIsRecorded covers the
// "malformed/unsupported state" acceptance criterion. A Yarn Berry lockfile
// that names a non-npm protocol Eshu does not yet match (for example
// patch:, exec:, portal:) must not invent a remote package; the parser must
// record the unsupported state so readiness can surface it.
func TestParseUnsupportedYarnBerryFeatureIsRecorded(t *testing.T) {
	t.Parallel()

	path := writeTestFile(t, "yarn.lock", `__metadata:
  version: 8

"patched-lib@patch:patched-lib@npm:1.0.0#./patches/fix.diff":
  version: 1.0.0
  resolution: "patched-lib@patch:patched-lib@npm:1.0.0#./patches/fix.diff"
  languageName: node
  linkType: hard

"plain-lib@npm:^2.0.0":
  version: 2.0.0
  resolution: "plain-lib@npm:2.0.0"
  languageName: node
  linkType: hard
`)

	payload, err := Parse(path, false, shared.Options{})
	if err != nil {
		t.Fatalf("Parse() error = %v", err)
	}
	rows, _ := payload["variables"].([]map[string]any)
	got := rowsByName(rows)

	if _, ok := got["plain-lib"]; !ok {
		t.Fatalf("expected supported npm-protocol row for plain-lib in %#v", rows)
	}
	row, ok := got["patched-lib"]
	if !ok {
		t.Fatalf("expected patched-lib row recorded with unsupported marker in %#v", rows)
	}
	if row["lockfile_unsupported_feature"] != "patch" {
		t.Fatalf("patched-lib lockfile_unsupported_feature = %#v, want patch", row["lockfile_unsupported_feature"])
	}
	if row["lockfile_resolution_protocol"] != "patch" {
		t.Fatalf("patched-lib lockfile_resolution_protocol = %#v, want patch", row["lockfile_resolution_protocol"])
	}
	if row["config_kind"] != "unsupported_dependency" {
		t.Fatalf("patched-lib config_kind = %#v, want unsupported_dependency so the reducer cannot admit it as precise consumption", row["config_kind"])
	}
}
