-- Let the cross-repo dead-code route ask "does this producer entity have an
-- active consumer outside the caller's grant?" as a seek instead of a group
-- scan (#5167).
--
-- POST /api/v0/code/dead-code/cross-repo runs two consumer reads for a scoped
-- caller that names no consumers. The evidence page is bound to the grant and
-- has to rank a producer entity's consumers by confidence, so it reads the
-- group; that cost is inherent to what the page returns. The second read is
-- not: it only has to answer whether ONE out-of-grant consumer exists, and it
-- used to answer that by re-running the page statement with no grant bound.
-- Ordering by (entity_id, confidence DESC, ...) makes an Incremental Sort
-- consume a producer entity's whole fan-in group before it can emit a row, so
-- an entity with a million consumer rows cost a million-row scan per request.
--
-- code_reachability_entity_lookup_idx leads with entity_id but carries state
-- and confidence next, not repository_id, so a consumer-repository predicate
-- can only be a heap filter under it, and nothing can walk an entity's
-- consumer repositories in order. With this index the probe is a loose index
-- scan: seek to the entity's smallest consumer repository, then to the
-- smallest one strictly greater, and stop at the first the grant does not
-- contain. Each step is an Index Cond of the form (entity_id = ?,
-- repository_id > ?) that returns one row, so a producer entity costs one
-- probe per distinct consumer repository the grant contains, plus one --
-- never a second row of any repository, however many rows it has.
--
-- Measured in a throwaway PostgreSQL 16.15 container, data-plane schema
-- applied from schema/data-plane/postgres (001, 002, 027), synthetic rows
-- only, VACUUM ANALYZE after seeding, SET jit = off, warm run reported.
-- 2,201,196 code_reachability_rows; one active scope and generation; a
-- 250-entity producer page whose middle entity carries 1,000,000
-- active-generation consumer rows across five consumer repositories:
--
--   shipped unrestricted signal read     757.6 / 756.9 / 779.5 ms
--     (generic plan)                     950.2 / 951.3 / 1021.2 ms
--     1,000,497 rows under the driving Index Scan
--     buffers hit=646 read=26929
--   bounded walk, every consumer granted    4.95 / 4.62 / 4.65 ms
--     (generic plan)                         4.72 / 4.58 / 4.78 ms
--     0 rows from the hot group, buffers hit=4886
--   bounded walk, an out-of-grant consumer  3.13 / 2.99 / 2.89 ms
--     (generic plan)                         3.12 / 2.96 / 2.90 ms
--     buffers hit=3006
--
-- The walk's cost does not follow the caller's grant, and that is the reason
-- it is the shape here. An earlier version of the probe asked the same
-- question as repository_id ranges around the sorted grant, one range per gap.
-- It used this index and was correct, but a range per gap is a probe per
-- granted repository, so on the same page it took 6.8 ms at a 5-repository
-- grant, 60 ms at 50, 248 ms at 200 and 633 ms at 500, while the walk stays at
-- 4.6-5.2 ms across all four and reads hit=4886 buffers at every one of them.
-- The walk's own axis is the entity's DISTINCT consumer repositories: a
-- producer entity consumed by 300 of them, all granted, costs 7.8 ms, where
-- the ranges cost 632 ms.
--
-- The index alone is not the fix. With this index in place but the predicate
-- left as NOT (repository_id = ANY(grant)), the planner takes a Parallel Seq
-- Scan and removes 733,732 rows by filter in 105 ms; a shape that seeks is
-- what turns it into an index read. The withdrawn shapes and the full
-- grant-size table are in
-- docs/internal/evidence/5167-code-family-batch-1.md.
--
-- 16 MB against a 139 MB code_reachability_entity_lookup_idx and a 1,154 MB
-- table on that seed: both key columns repeat heavily within an entity, so
-- btree deduplication compresses this index far better than the existing ones.
-- depth is deliberately absent. It is a range predicate, so nothing after it
-- in the key could be used as an Index Cond anyway, and depth = 0 rows are the
-- root's own row -- at most one per consumer repository per entity, which the
-- filter discards without a measurable scan. The walk needs exactly this key
-- order: entity_id equality first so one entity's rows are contiguous, then
-- repository_id so they are ordered by the column the walk steps through.
--
-- CONCURRENTLY, so building it does not block the reducer's reachability
-- writes. The usual objection -- that a failed concurrent build leaves an
-- INVALID index that IF NOT EXISTS then skips forever -- does not apply: the
-- schema apply path drops invalid concurrent indexes by name before executing
-- each definition (SQLDB.dropInvalidConcurrentIndexes, db.go) and runs each
-- statement outside any transaction on a dedicated bootstrap connection, which
-- CONCURRENTLY requires. That is also why it cannot join
-- 027_code_reachability.sql: that definition is multi-statement, and a
-- multi-statement Exec is sent as an implicit transaction.
CREATE INDEX CONCURRENTLY IF NOT EXISTS code_reachability_entity_repository_idx
    ON code_reachability_rows (entity_id, repository_id);
