-- Let the cross-repo dead-code consumer-evidence PAGE stop at its own LIMIT
-- instead of reading a producer entity's whole consumer fan-in first (#6527).
--
-- buildCrossRepoDeadCodeConsumerEvidenceQuery selects one page of consumer
-- evidence for the producer entities on a dead-code page, ordered
-- (entity_id, confidence DESC, depth, repository_id, root_entity_id) and capped
-- at 1,001 rows. The LIMIT bounds what comes back, not what is read: to return
-- an entity's strongest consumers Postgres has to rank that entity's whole
-- group, so the read costs the entity's fan-in rather than the page's cap.
--
-- No existing index carries that order. code_reachability_entity_lookup_idx is
-- (entity_id, state, confidence DESC) and no read in the tree constrains state,
-- so confidence is unreachable as a sort key behind it; migration 101's index
-- is (entity_id, repository_id, scope_id, generation_id), which is why the
-- shipped plan puts an Incremental Sort presorted on entity_id above it and
-- feeds that sort the whole group. This index's five key columns ARE the
-- statement's ORDER BY with entity_id pinned by the IN list, so the scan is
-- already in output order and the LIMIT stops it. depth sits third because it
-- is an ORDER BY column here, not the range predicate it is in migration 101.
--
-- Measured in a throwaway PostgreSQL 16.15 container, data-plane schema applied
-- from schema/data-plane/postgres (001, 002, 027) plus migrations 101 and 102,
-- synthetic rows only, VACUUM ANALYZE after seeding, SET jit = off, warm, three
-- samples, both plan modes. The seed is the one #6527's measurements were filed
-- from: 2,207,196 rows, one ingestion scope, one generation, a 251-entity
-- producer page whose middle entity carries 1,000,000 active-generation
-- consumer rows across five consumer repositories, and 1.2M rows on entity ids
-- off the page. Custom plan, the plan every execution of this statement gets:
--
--   consumer-repository grant          five of five      four of five
--   rows under the driving scan
--     without this index                  1,000,497           800,497
--     with this index                         1,124             1,124
--   shared buffers
--     without this index                    113,832           113,832
--     with this index                           929               929
--   execution time
--     without this index      815.3/869.2/825.5 ms  853.3/719.6/724.0 ms
--     with this index             1.68/4.56/1.66 ms     1.59/1.59/1.62 ms
--
-- The answer does not move: the statement is unchanged, and the rows it returns
-- were captured position by position with and without the index on four page and
-- grant shapes -- symmetric difference 0/0 and zero position mismatches on all
-- four. Details and the rejected alternatives are in
-- docs/internal/evidence/5167-cross-repo-consumer-page-bound.md.
--
-- Which plan production gets was measured rather than assumed. pgx runs these
-- reads as server-side prepared statements, so the question is what Postgres's
-- plan cache decides. PREPARE plus twelve EXECUTEs under the default
-- plan_cache_mode = auto leaves pg_prepared_statements at generic_plans = 0 and
-- custom_plans = 12: the cache never promotes the generic plan, because the
-- generic estimate is far above the custom average, which is the comparison
-- choose_custom_plan makes. Under a forced generic plan the planner keeps the
-- shape it uses today and this index is not read -- no better there, and no
-- worse.
--
-- Cost. On that seed the index is 163 MB built in 6.4 s CONCURRENTLY, against a
-- 367 MB heap and 808 MB of existing indexes, so the relation's footprint grows
-- about 14%. The reducer's write path maintains one more btree: a 200,000-row
-- reachability insert takes 6.02/6.06 s without it and 7.24/7.47 s with it,
-- about +15-20%, alternated so both arms saw the table grow. Nothing is dropped
-- to pay for it. code_reachability_entity_lookup_idx looks superseded on paper
-- and is not dropped here: removing it would need its own before/after on the
-- reads that use it, and this migration's proof does not cover that.
--
-- Replay. This directory has no applied-migration ledger: BootstrapDefinitions
-- enumerates every file under migrations/ and ApplyDefinitions Execs all of
-- them, in filename order, on EVERY bootstrap (schema.go, pinned by
-- TestApplyBootstrapExecutesDefinitionsInOrder). A migration is therefore a
-- desired-state statement that has to be a no-op once the state it wants
-- already holds. This file only creates, and no file in this directory drops
-- this name, so a bootstrap over an install that already has the index does no
-- index work. TestCodeReachabilityPageRankIndexIsCreatedOnceAndNeverDropped
-- pins that statically and
-- TestCodeReachabilityIndexMigrationsReapplyWithoutRebuildLive proves it on a
-- populated store.
--
-- CONCURRENTLY, so building it does not block the reducer's reachability
-- writes, and the lone statement in this file because the runner Execs each
-- file as one simple-query string and Postgres treats a multi-statement string
-- as an implicit transaction block, which CONCURRENTLY cannot run inside. That
-- is also why it cannot join 027_code_reachability.sql. The usual objection to
-- CONCURRENTLY -- that a failed build leaves an INVALID index that IF NOT
-- EXISTS then skips forever -- does not apply: the schema apply path drops
-- invalid concurrent indexes by name before executing each definition
-- (SQLDB.dropInvalidConcurrentIndexes, db.go) and runs each statement outside
-- any transaction on a dedicated bootstrap connection, which CONCURRENTLY
-- requires.
CREATE INDEX CONCURRENTLY IF NOT EXISTS code_reachability_entity_confidence_rank_idx
    ON code_reachability_rows (entity_id, confidence DESC, depth, repository_id, root_entity_id);
