// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package skillgen

import (
	"fmt"
	"strings"
)

// codexAdapter renders the .codex/skills/eshu/SKILL.md file the Codex
// loader expects. Codex's always-on layer is the project AGENTS.md, which
// is not regenerated by S2; the skill body augments that always-on layer.
//
// The output format mirrors Claude Code (name, description, full body,
// byte-citation block) so the two host skills are byte-comparable except
// for the host-specific always-on layer file, which lives outside the
// generated output.
//
// The YAML frontmatter is at byte 0 because Codex discovers skills from
// the leading `---` block; the byte-citation block follows the frontmatter
// so the loader reads the metadata before any HTML comment is parsed.
// This is the only host whose discovery contract requires frontmatter-at-
// byte-0; the other two hosts accept the citation block above the
// frontmatter but we keep all three hosts on the same shape for symmetry.
type codexAdapter struct{}

func (codexAdapter) Host() Host { return HostCodex }

func (codexAdapter) OutputPath() string { return ".codex/skills/eshu/SKILL.md" }

func (a codexAdapter) Render(in RenderInput) ([]byte, error) {
	commentBlock, err := normalizeCommentBlock(in.CommentBlock, in.Fragments)
	if err != nil {
		return nil, fmt.Errorf("codex adapter: %w", err)
	}
	var b strings.Builder
	b.WriteString("---\n")
	b.WriteString("name: eshu\n")
	b.WriteString("description: |\n")
	for _, line := range wrapDescription(combinedDescription(in.Fragments), 72) {
		b.WriteString("  ")
		b.WriteString(line)
		b.WriteString("\n")
	}
	b.WriteString("---\n\n")
	if commentBlock != "" {
		b.WriteString(commentBlock)
		b.WriteString("\n\n")
	}
	b.WriteString("# Eshu Agent Skill\n\n")
	b.WriteString("This skill is auto-generated from `skill-fragments/`. Do not edit it by hand; run `go run ./cmd/skillgen gen` to regenerate.\n\n")
	for _, fragment := range in.Fragments {
		b.WriteString(fragmentSection(fragment, in.Capabilities))
		b.WriteString("\n")
	}
	return []byte(b.String()), nil
}
