// SPDX-License-Identifier: MIT
// Copyright (c) 2025-2026 eshu-hq

package skillgen

import (
	"fmt"
	"sort"
	"strings"
)

// Host is the bounded set of skill-file targets S2 emits. The S1 design opened
// with three hosts; #4059 extended the matrix to six after confirming each
// added host's loader contract against its vendor documentation. A host earns
// a place here only when its discovery path and always-on layer are known, so
// the generator never guesses where a loader looks.
type Host string

const (
	// HostClaudeCode writes to .claude/skills/eshu/SKILL.md. The always-on
	// layer is the project CLAUDE.md, which is not regenerated by S2.
	HostClaudeCode Host = "claude-code"
	// HostCursor writes to .cursor/rules/eshu.mdc. The .mdc file is the
	// always-on layer; Cursor has no separate CLAUDE.md-style file.
	HostCursor Host = "cursor"
	// HostCodex writes to .codex/skills/eshu/SKILL.md. The always-on layer
	// is the project AGENTS.md, which is not regenerated by S2.
	HostCodex Host = "codex"
	// HostCopilot writes to .github/instructions/eshu.instructions.md, the
	// path-specific instructions file GitHub Copilot discovers. Its
	// frontmatter carries the required applyTo glob. The always-on layer is
	// .github/copilot-instructions.md, which is not regenerated by S2.
	HostCopilot Host = "copilot"
	// HostAider writes to .aider/eshu-conventions.md. Aider has no
	// auto-discovered conventions path: the operator points at the file
	// through the read key in .aider.conf.yml, which is not regenerated by
	// S2. The file therefore carries no frontmatter.
	HostAider Host = "aider"
	// HostGeminiCLI writes to GEMINI.md, the workspace context file the
	// Gemini CLI loads hierarchically. Like Cursor, the generated file IS
	// the always-on layer, and the format carries no frontmatter.
	HostGeminiCLI Host = "gemini-cli"
)

// AllHosts returns the supported hosts in deterministic order. The order is
// the canonical render order for `gen` and the canonical check order for
// `check`. The original three keep their positions so a baseline diff stays
// readable when the matrix grows.
func AllHosts() []Host {
	return []Host{
		HostClaudeCode,
		HostCursor,
		HostCodex,
		HostCopilot,
		HostAider,
		HostGeminiCLI,
	}
}

// LoaderParsesFrontmatter reports whether the host's loader reads a leading
// YAML `---` block to discover or configure the file.
//
// This is a property of the loader, not a style choice. Claude Code, Cursor,
// Codex, and Copilot all parse frontmatter, so their generated files must open
// with it and nothing may precede it. Aider and the Gemini CLI define no
// frontmatter schema and hand the file to the model as prose, so a `---` block
// there would arrive as literal content rather than configuration; those files
// open with the byte-citation comment instead.
//
// The shared invariant across all six is the same underneath: nothing precedes
// whatever the loader needs to find the file.
func (h Host) LoaderParsesFrontmatter() bool {
	switch h {
	case HostClaudeCode, HostCursor, HostCodex, HostCopilot:
		return true
	case HostAider, HostGeminiCLI:
		return false
	default:
		return false
	}
}

// HostAdapter is the per-host render contract. Each adapter owns the file
// shape, the frontmatter schema, and the per-host comments; the fragment
// pipeline is host-agnostic and the byte-citation block is stable across
// hosts.
type HostAdapter interface {
	// Host is the stable host id used as the output subdirectory name under
	// the configured expected/ root.
	Host() Host
	// OutputPath is the relative output path of the generated skill. S2
	// joins it onto the configured expected/ root.
	OutputPath() string
	// Render returns the host-shaped skill bytes for the given fragments
	// and capability summary. The byte-citation block has already been
	// formatted and is passed in pre-normalized form; the adapter must
	// stamp it at the top of the output.
	Render(input RenderInput) ([]byte, error)
}

// RenderInput is the host-agnostic input to a HostAdapter.Render call.
type RenderInput struct {
	// Fragments is the loaded, validated set of fragments in deterministic
	// id-sorted order.
	Fragments []Fragment
	// CommentBlock is the pre-formatted, sorted, deduplicated byte-citation
	// block. It does not end with a trailing newline.
	CommentBlock string
	// Capabilities is the optional per-deployment capability summary. The
	// per-collector-matrix fragment is the only fragment that consumes
	// Capabilities today.
	Capabilities Capabilities
}

// hostRegistry maps each supported host to its adapter implementation.
// Add a new host by appending a constructor to this map, adding a constant in
// the Host block above, and adding it to AllHosts in render order.
var hostRegistry = map[Host]HostAdapter{
	HostClaudeCode: claudeCodeAdapter{},
	HostCursor:     cursorAdapter{},
	HostCodex:      codexAdapter{},
	HostCopilot:    copilotAdapter{},
	HostAider:      aiderAdapter{},
	HostGeminiCLI:  geminiCLIAdapter{},
}

// AdapterFor returns the registered adapter for the given host. It returns
// an error if the host is not registered; this is the only allowed way for
// callers to look up an adapter.
func AdapterFor(host Host) (HostAdapter, error) {
	if a, ok := hostRegistry[host]; ok {
		return a, nil
	}
	return nil, fmt.Errorf("skillgen: no adapter registered for host %q", host)
}

// HostFromString parses a case-insensitive host name. Accepts
// "claude-code" and "claude_code" interchangeably so contributors do not
// trip over the dash/underscore distinction.
func HostFromString(s string) (Host, error) {
	normalized := strings.ToLower(strings.TrimSpace(s))
	normalized = strings.ReplaceAll(normalized, "_", "-")
	for _, h := range AllHosts() {
		if string(h) == normalized {
			return h, nil
		}
	}
	return "", fmt.Errorf("skillgen: unknown host %q (supported: %s)", s, joinHosts(AllHosts()))
}

func joinHosts(hosts []Host) string {
	parts := make([]string, 0, len(hosts))
	for _, h := range hosts {
		parts = append(parts, string(h))
	}
	sort.Strings(parts)
	return strings.Join(parts, ", ")
}
