apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eshu.fullname" . }}-eshuignore
  labels:
    {{- include "eshu.labels" . | nindent 4 }}
data:
  .eshuignore: |
    {{- .Values.eshuignore | nindent 4 }}
